["The_Fighter", [["Christian_Bale", 3906000000.0], ["Amy_Adams", -1], ["Melissa_Leo", -1], ["Jack_McGee_(actor)", -1]]]
["Black_Swan_(film)", [["Natalie_Portman", -1], ["Vincent_Cassel", 3294000000.0], ["Mila_Kunis", -1], ["Barbara_Hershey", 3695000003.0], ["Winona_Ryder", -1]]]
["The_King%27s_Speech", [["Colin_Firth", -1], ["Geoffrey_Rush", 10685000000.0], ["Helena_Bonham_Carter", -1], ["Guy_Pearce", -1], ["Timothy_Spall", -1], ["Derek_Jacobi", -1], ["Jennifer_Ehle", -1], ["Michael_Gambon", -1]]]
["Captain_Phillips_(film)", [["Tom_Hanks", -1], ["Barkhad_Abdi", 2188000000.0]]]
["Twilight_of_Honor", [["Richard_Chamberlain", -1], ["Nick_Adams_(actor,_born_1931)", -1]]]
["Amadeus_(film)", [["F._Murray_Abraham", -1], ["Tom_Hulce", 520000000.0], ["Elizabeth_Berridge_(actress)", -1], ["Simon_Callow", -1], ["Roy_Dotrice", -1], ["Christine_Ebersole", -1], ["Jeffrey_Jones", -1], ["Charles_Kay", -1]]]
["American_Hustle", [["Christian_Bale", 3906000000.0], ["Bradley_Cooper", -1], ["Amy_Adams", -1], ["Jeremy_Renner", -1], ["Jennifer_Lawrence", -1], ["Louis_C._K.", -1], ["Michael_Pe%C3%B1a", -1], ["Alessandro_Nivola", -1]]]
["The_Story_of_Adele_H.", [["Isabelle_Adjani", 0], ["Bruce_Robinson", -1]]]
["House_of_Sand_and_Fog_(film)", [["Ben_Kingsley", -1], ["Shohreh_Aghdashloo", -1], ["Jennifer_Connelly", -1], ["Ron_Eldard", -1], ["Frances_Fisher", -1], ["Kim_Dickens", -1]]]
["Juarez_(film)", [["Paul_Muni", 0], ["Bette_Davis", -1], ["Brian_Aherne", -1], ["John_Garfield", 0]]]
["Manchester_by_the_Sea_(film)", [["Casey_Affleck", -1], ["Michelle_Williams_(actress)", -1], ["Kyle_Chandler", -1], ["Gretchen_Mol", -1], ["Lucas_Hedges", -1]]]
["Do_the_Right_Thing", [["Danny_Aiello", -1], ["Ossie_Davis", -1], ["Ruby_Dee", -1], ["Richard_Edson", -1], ["Giancarlo_Esposito", -1], ["Bill_Nunn", -1], ["John_Turturro", -1], ["John_Savage_(actor)", -1]]]
["Roman_Holiday", [["Gregory_Peck", -1], ["Audrey_Hepburn", 120000000.0]]]
["The_Subject_Was_Roses_(film)", [["Patricia_Neal", -1], ["Jack_Albertson", -1], ["Martin_Sheen", -1]]]
["A_Man_and_a_Woman", [["Anouk_Aim%C3%A9e", 14000000.0], ["Jean-Louis_Trintignant", 14000000.0]]]
["Gaby:_A_True_Story", [["Liv_Ullmann", -1], ["Norma_Aleandro", 125400.0], ["Robert_Loggia", -1], ["Lawrence_Monoson", -1], ["Rachel_Chagall", -1]]]
["The_Great_White_Hope_(film)", [["James_Earl_Jones", -1], ["Jane_Alexander", -1]]]
["The_Aviator_(2004_film)", [["Leonardo_DiCaprio", -1], ["Cate_Blanchett", -1], ["Kate_Beckinsale", -1], ["John_C._Reilly", -1], ["Alec_Baldwin", -1], ["Alan_Alda", -1], ["Ian_Holm", -1], ["Danny_Huston", -1], ["Gwen_Stefani", -1], ["Jude_Law", -1]]]
["The_Contender_(2000_film)", [["Gary_Oldman", -1], ["Joan_Allen", -1], ["Jeff_Bridges", -1], ["Christian_Slater", -1], ["William_Petersen", -1], ["Philip_Baker_Hall", -1], ["Saul_Rubinek", -1], ["Sam_Elliott", -1]]]
["Cocoon_(film)", [["Don_Ameche", 878000000.0], ["Wilford_Brimley", -1], ["Hume_Cronyn", -1], ["Brian_Dennehy", -1], ["Jack_Gilford", -1], ["Steve_Guttenberg", -1], ["Maureen_Stapleton", -1], ["Jessica_Tandy", -1], ["Gwen_Verdon", 853000000.0], ["Herta_Ware", -1], ["Tahnee_Welch", 853000000.0]]]
["Moonlight_(2016_film)", [["Trevante_Rhodes", -1], ["Andr%C3%A9_Holland", -1], ["Janelle_Mon%C3%A1e", 652000000.0], ["Ashton_Sanders", -1], ["Naomie_Harris", -1], ["Mahershala_Ali", -1]]]
["Annie_Hall", [["Diane_Keaton", -1], ["Tony_Roberts_(actor)", -1], ["Carol_Kane", -1], ["Paul_Simon", -1], ["Janet_Margolin", -1], ["Shelley_Duvall", -1], ["Christopher_Walken", 383000000.0], ["Colleen_Dewhurst", -1]]]
["How_Green_Was_My_Valley_(film)", [["Walter_Pidgeon", -1], ["Maureen_O%27Hara", -1], ["Donald_Crisp", 28000000.0], ["Anna_Lee", -1], ["Roddy_McDowall", -1]]]
["Rebecca_(1940_film)", [["Laurence_Olivier", -1], ["Joan_Fontaine", 10.5]]]
["Tommy_(1975_film)", [["Ann-Margret", 343000000.0], ["Oliver_Reed", -1], ["Roger_Daltrey", -1], ["Elton_John", 343000000.0], ["Eric_Clapton", -1], ["John_Entwistle", -1], ["Keith_Moon", -1], ["Paul_Nicholas", -1], ["Jack_Nicholson", -1], ["Robert_Powell", -1], ["Arthur_Brown_(musician)", -1], ["Pete_Townshend", -1], ["Tina_Turner", -1]]]
["Mary_Poppins_(film)", [["Julie_Andrews", -1], ["Dick_Van_Dyke", -1], ["David_Tomlinson", -1], ["Glynis_Johns", -1], ["Hermione_Baddeley", -1], ["Karen_Dotrice", -1], ["Matthew_Garber", 1023000000.0], ["Elsa_Lanchester", -1], ["Arthur_Treacher", -1], ["Reginald_Owen", -1], ["Ed_Wynn", -1]]]
["Fatal_Attraction", [["Michael_Douglas", -1], ["Glenn_Close", -1], ["Anne_Archer", -1]]]
["Mildred_Pierce_(film)", [["Joan_Crawford", -1], ["Jack_Carson", -1], ["Zachary_Scott", -1], ["Eve_Arden", -1], ["Ann_Blyth", -1], ["Bruce_Bennett", -1]]]
["Roma_(2018_film)", [["Yalitza_Aparicio", 41000000.0], ["Marina_de_Tavira", 41000000.0]]]
["Disraeli_(1929_film)", [["George_Arliss", 0], ["Doris_Lloyd", -1], ["David_Torrence", 0], ["Joan_Bennett", -1]]]
["The_More_the_Merrier", [["Jean_Arthur", -1], ["Joel_McCrea", 18000000.0], ["Charles_Coburn", 18000000.0]]]
["Little_Miss_Sunshine", [["Greg_Kinnear", -1], ["Steve_Carell", -1], ["Toni_Collette", -1], ["Paul_Dano", -1], ["Abigail_Breslin", -1], ["Alan_Arkin", -1]]]
["A_Passage_to_India_(film)", [["Peggy_Ashcroft", -1], ["Judy_Davis", -1], ["James_Fox", -1], ["Alec_Guinness", -1], ["Nigel_Havers", -1], ["Victor_Banerjee", -1], ["Roshan_Seth", 272000000.0]]]
["The_Great_Lie", [["Bette_Davis", -1], ["George_Brent", -1], ["Mary_Astor", -1]]]
["Boyhood_(film)", [["Patricia_Arquette", -1], ["Ellar_Coltrane", 573000000.0], ["Lorelei_Linklater", 573000000.0], ["Ethan_Hawke", 573000000.0]]]
["The_Towering_Inferno", [["Steve_McQueen", -1], ["Paul_Newman", -1], ["William_Holden", -1], ["Faye_Dunaway", -1], ["Fred_Astaire", -1], ["Susan_Blakely", -1], ["Richard_Chamberlain", -1], ["Jennifer_Jones", 1597000005.0], ["O._J._Simpson", -1], ["Robert_Vaughn", -1], ["Robert_Wagner", -1]]]
["My_Man_Godfrey", [["William_Powell", 0], ["Carole_Lombard", 0], ["Alice_Brady", 25000000.0], ["Gail_Patrick", -1], ["Eugene_Pallette", 0], ["Jean_Dixon", 0], ["Alan_Mowbray", -1]]]
["The_Color_Purple_(film)", [["Danny_Glover", 1769000000.0], ["Adolph_Caesar", 1420000000.0], ["Margaret_Avery", -1], ["Rae_Dawn_Chong", -1], ["Whoopi_Goldberg", -1]]]
["Driving_Miss_Daisy", [["Morgan_Freeman", -1], ["Jessica_Tandy", -1], ["Dan_Aykroyd", -1], ["Patti_LuPone", -1], ["Esther_Rolle", -1]]]
["Johnny_Belinda_(1948_film)", [["Jane_Wyman", -1], ["Lew_Ayres", -1], ["Charles_Bickford", -1], ["Agnes_Moorehead", -1]]]
["The_Mirror_Has_Two_Faces", [["Jeff_Bridges", -1], ["Pierce_Brosnan", -1], ["George_Segal", -1], ["Mimi_Rogers", -1], ["Brenda_Vaccaro", -1], ["Lauren_Bacall", 704610201.0]]]
["Room_at_the_Top_(1959_film)", [["Laurence_Harvey", 2400000.0], ["Simone_Signoret", -1], ["Heather_Sears", 2400000.0], ["Donald_Wolfit", 2400000.0], ["Hermione_Baddeley", -1]]]
["To_Kill_a_Mockingbird_(film)", [["Gregory_Peck", -1], ["Mary_Badham", 131000000.0], ["Phillip_Alford", -1], ["John_Megna", -1], ["Ruth_White_(actress)", -1], ["Paul_Fix", -1], ["Brock_Peters", -1], ["Frank_Overton", -1]]]
["Jezebel_(film)", [["Bette_Davis", -1], ["Henry_Fonda", -1], ["George_Brent", -1], ["Margaret_Lindsay", 0], ["Donald_Crisp", 28000000.0], ["Fay_Bainter", 0], ["Richard_Cromwell_(actor)", 0], ["Henry_O%27Neill", 0], ["Spring_Byington", -1], ["John_Litel", 0]]]
["Baby_Doll", [["Karl_Malden", -1], ["Carroll_Baker", 23000000.0], ["Eli_Wallach", -1]]]
["The_Cooler", [["William_H._Macy", -1], ["Alec_Baldwin", -1], ["Maria_Bello", -1], ["Shawn_Hatosy", -1], ["Ron_Livingston", -1]]]
["A_Thousand_Clowns", [["Jason_Robards", -1], ["Barbara_Harris_(actress)", -1], ["Martin_Balsam", -1], ["Barry_Gordon", -1]]]
["The_Miracle_Worker_(1962_film)", [["Anne_Bancroft", -1], ["Patty_Duke", -1]]]
["Thunderbolt_(1929_film)", [["George_Bancroft_(actor)", 0], ["Fay_Wray", -1], ["Richard_Arlen", -1], ["Tully_Marshall", 0], ["Eugenie_Besserer", 0]]]
["The_Flight_of_the_Phoenix_(1965_film)", [["James_Stewart", -1], ["Richard_Attenborough", -1], ["Hardy_Kr%C3%BCger", -1], ["Peter_Finch", 3.0], ["Ernest_Borgnine", -1], ["Ian_Bannen", -1]]]
["Cousin_Cousine", [["Marie-Christine_Barrault", -1], ["Victor_Lanoux", 87000000.0], ["Marie-France_Pisier", 87000000.0]]]
["Babel_(film)", [["Brad_Pitt", -1], ["Cate_Blanchett", -1], ["Gael_Garc%C3%ADa_Bernal", -1], ["K%C5%8Dji_Yakusho", 1353000000.0], ["Adriana_Barraza", -1], ["Rinko_Kikuchi", -1]]]
["The_Patent_Leather_Kid", [["Richard_Barthelmess", 12000000.0]]]
["None_but_the_Lonely_Heart_(film)", [["Cary_Grant", -1], ["Ethel_Barrymore", 42000000.0], ["Barry_Fitzgerald", 0], ["June_Duprez", 0], ["Jane_Wyatt", -1], ["George_Coulouris", 0], ["Dan_Duryea", -1]]]
["No_Country_for_Old_Men_(film)", [["Tommy_Lee_Jones", -1], ["Javier_Bardem", -1], ["Josh_Brolin", -1]]]
["A_Free_Soul", [["Norma_Shearer", 0]]]
["The_Turning_Point_(1977_film)", [["Shirley_MacLaine", -1], ["Anne_Bancroft", -1], ["Tom_Skerritt", -1], ["Mikhail_Baryshnikov", -1], ["Leslie_Browne", 336000000.0]]]
["What%27s_Love_Got_to_Do_with_It_(film)", [["Angela_Bassett", -1], ["Laurence_Fishburne", -1]]]
["The_Fixer_(1968_film)", [["Alan_Bates", -1], ["Dirk_Bogarde", 0], ["Georgia_Brown_(English_singer)", -1]]]
["Foreign_Correspondent_(film)", [["Joel_McCrea", 18000000.0], ["Laraine_Day", -1], ["Herbert_Marshall", 5.0], ["George_Sanders", -1], ["Albert_Basserman", 0]]]
["L.A._Confidential_(film)", [["Kevin_Spacey", -1], ["Russell_Crowe", -1], ["Guy_Pearce", -1], ["James_Cromwell", -1], ["David_Strathairn", -1], ["Kim_Basinger", -1], ["Danny_DeVito", -1]]]
["Misery_(film)", [["James_Caan", -1], ["Kathy_Bates", -1], ["Frances_Sternhagen", -1], ["Richard_Farnsworth", -1], ["Lauren_Bacall", 704610201.0]]]
["The_Razor%27s_Edge_(1946_film)", [["Tyrone_Power", 25000005.0], ["Gene_Tierney", -1], ["John_Payne_(actor)", -1], ["Herbert_Marshall", 5.0], ["Anne_Baxter", -1], ["Clifton_Webb", 5.0]]]
["In_Old_Arizona", [["Warner_Baxter", 13000000.0], ["Edmund_Lowe", 13000000.0], ["Dorothy_Burgess", 13000000.0]]]
["The_Champ_(1931_film)", [["Wallace_Beery", 16000002.0], ["Jackie_Cooper", -1], ["Irene_Rich", 16000000.0], ["Roscoe_Ates", -1]]]
["Bonnie_and_Clyde_(film)", [["Faye_Dunaway", -1], ["Michael_J._Pollard", -1], ["Gene_Hackman", 2292000000.0], ["Estelle_Parsons", -1]]]
["The_Awful_Truth", [["Irene_Dunne", -1], ["Cary_Grant", -1], ["Ralph_Bellamy", -1], ["Alexander_D%27Arcy", -1]]]
["Wake_Island_(film)", [["Brian_Donlevy", -1], ["Robert_Preston_(actor)", 35000000.0], ["William_Bendix", -1]]]
["Starting_Over_(1979_film)", [["Burt_Reynolds", -1], ["Jill_Clayburgh", -1], ["Candice_Bergen", -1], ["Charles_Durning", -1], ["Frances_Sternhagen", -1], ["Austin_Pendleton", -1], ["Mary_Kay_Place", -1]]]
["Life_Is_Beautiful", [["Nicoletta_Braschi", 2292000000.0]]]
["Gaslight_(1944_film)", [["Charles_Boyer", -1], ["Ingrid_Bergman", 6387000.0], ["Joseph_Cotten", -1], ["May_Whitty", 0], ["Angela_Lansbury", -1]]]
["Platoon_(film)", [["Tom_Berenger", -1], ["Willem_Dafoe", 5384000000.0], ["Charlie_Sheen", -1]]]
["Escape_Me_Never_(1935_film)", [["Elisabeth_Bergner", 0], ["Hugh_Sinclair_(actor)", -1], ["Griffith_Jones_(actor)", -1], ["Penelope_Dudley-Ward", 0]]]
["The_Heartbreak_Kid_(1972_film)", [["Charles_Grodin", -1], ["Cybill_Shepherd", -1], ["Jeannie_Berlin", -1], ["Eddie_Albert", -1], ["Audra_Lindley", -1]]]
["American_Beauty_(1999_film)", [["Kevin_Spacey", -1], ["Annette_Bening", -1], ["Thora_Birch", -1], ["Allison_Janney", -1], ["Peter_Gallagher", -1], ["Mena_Suvari", -1], ["Wes_Bentley", 3563000000.0], ["Chris_Cooper", 4831000000.0]]]
["Monster%27s_Ball", [["Billy_Bob_Thornton", -1], ["Halle_Berry", -1], ["Heath_Ledger", -1], ["Peter_Boyle", -1], ["Sean_Combs", -1], ["Mos_Def", -1]]]
["A_Better_Life", [["Demi%C3%A1n_Bichir", 0]]]
["The_Song_of_Bernadette_(film)", [["Jennifer_Jones", 1597000005.0], ["William_Eythe", -1], ["Charles_Bickford", -1], ["Vincent_Price", -1], ["Lee_J._Cobb", 96000005.0], ["Gladys_Cooper", -1]]]
["The_Defiant_Ones_(film)", [["Sidney_Poitier", -1], ["Tony_Curtis", -1]]]
["The_English_Patient_(film)", [["Ralph_Fiennes", -1], ["Juliette_Binoche", 2320000000.0], ["Willem_Dafoe", 5384000000.0], ["Kristin_Scott_Thomas", -1], ["Naveen_Andrews", -1], ["Colin_Firth", -1], ["Julian_Wadham", -1], ["J%C3%BCrgen_Prochnow", -1]]]
["Five_Easy_Pieces", [["Jack_Nicholson", -1], ["Karen_Black", -1], ["Susan_Anspach", -1]]]
["Nashville_(film)", [["Ned_Beatty", -1], ["Ronee_Blakley", 100000000.0], ["Keith_Carradine", -1], ["Geraldine_Chaplin", -1], ["Henry_Gibson", -1], ["Michael_Murphy_(actor)", -1], ["Lily_Tomlin", -1]]]
["Blue_Jasmine", [["Cate_Blanchett", -1], ["Alec_Baldwin", -1], ["Louis_C.K.", -1], ["Bobby_Cannavale", -1], ["Andrew_Dice_Clay", -1], ["Sally_Hawkins", -1], ["Peter_Sarsgaard", 975000000.0], ["Michael_Stuhlbarg", -1]]]
["Secrets_%26_Lies_(film)", [["Timothy_Spall", -1], ["Brenda_Blethyn", -1], ["Phyllis_Logan", -1], ["Marianne_Jean-Baptiste", -1], ["Claire_Rushbrook", -1], ["Ron_Cook", -1], ["Lesley_Manville", -1], ["Elizabeth_Berrington", -1], ["Michele_Austin", -1], ["Lee_Ross_(actor)", -1], ["Emma_Amos_(actress)", -1]]]
["The_Blue_Veil_(1951_film)", [["Jane_Wyman", -1], ["Charles_Laughton", 0], ["Joan_Blondell", 3.0]]]
["Mudbound_(film)", [["Carey_Mulligan", -1], ["Jason_Clarke", -1], ["Jason_Mitchell_(actor)", 0], ["Mary_J._Blige", -1], ["Rob_Morgan_(actor)", -1], ["Jonathan_Banks", -1], ["Garrett_Hedlund", 0]]]
["The_Gorgeous_Hussy", [["Joan_Crawford", -1], ["Robert_Taylor_(actor)", -1], ["Lionel_Barrymore", 2137575.0], ["Franchot_Tone", -1]]]
["The_African_Queen_(film)", [["Humphrey_Bogart", 0], ["Katharine_Hepburn", -1], ["Robert_Morley", 0]]]
["The_Wings_of_the_Dove_(1997_film)", [["Helena_Bonham_Carter", -1], ["Linus_Roache", -1], ["Alison_Elliott", -1], ["Elizabeth_McGovern", -1], ["Michael_Gambon", -1], ["Alex_Jennings", -1], ["Charlotte_Rampling", -1]]]
["Come_Back,_Little_Sheba_(1952_film)", [["Burt_Lancaster", 35000000.0], ["Shirley_Booth", -1], ["Terry_Moore_(actress)", -1]]]
["Conquest_(1937_film)", [["Greta_Garbo", 2141000.0], ["Charles_Boyer", -1], ["Reginald_Owen", -1], ["Alan_Marshal_(actor)", 2141000.0]]]
["In_Old_Chicago", [["Tyrone_Power", 25000005.0], ["Alice_Faye", 25000000.0], ["Don_Ameche", 878000000.0], ["Alice_Brady", 25000000.0]]]
["Henry_V_(1989_film)", [["Paul_Scofield", -1], ["Derek_Jacobi", -1], ["Ian_Holm", -1], ["Emma_Thompson", -1], ["Alec_McCowen", -1], ["Judi_Dench", -1], ["Christian_Bale", 3906000000.0]]]
["Goodfellas", [["Robert_De_Niro", 3813000000.0], ["Ray_Liotta", -1], ["Joe_Pesci", 468000000.0], ["Lorraine_Bracco", -1], ["Paul_Sorvino", -1]]]
["Out_of_Africa_(film)", [["Robert_Redford", 2275000000.0], ["Meryl_Streep", -1], ["Klaus_Maria_Brandauer", 2275000000.0]]]
["Come_and_Get_It_(1936_film)", [["Edward_Arnold_(actor)", 2137575.0], ["Joel_McCrea", 18000000.0], ["Frances_Farmer", -1], ["Walter_Brennan", -1]]]
["On_the_Waterfront", [["Marlon_Brando", -1], ["Karl_Malden", -1], ["Lee_J._Cobb", 96000005.0], ["Rod_Steiger", -1], ["Pat_Henning", -1], ["Eva_Marie_Saint", -1]]]
["Iris_(2001_film)", [["Judi_Dench", -1], ["Kate_Winslet", -1], ["Jim_Broadbent", -1], ["Hugh_Bonneville", -1]]]
["Crazy_Heart", [["Jeff_Bridges", -1], ["Maggie_Gyllenhaal", -1], ["Colin_Farrell", -1]]]
["The_Pianist_(2002_film)", [["Adrien_Brody", 1201000000.0], ["Thomas_Kretschmann", -1], ["Frank_Finlay", -1], ["Maureen_Lipman", -1], ["Emilia_Fox", -1], ["Micha%C5%82_%C5%BBebrowski", 1201000000.0]]]
["Milk_(film)", [["Sean_Penn", -1], ["Emile_Hirsch", -1], ["Josh_Brolin", -1], ["Diego_Luna", -1], ["Alison_Pill", -1], ["Victor_Garber", -1], ["Denis_O%27Hare", -1], ["Joseph_Cross_(actor)", -1], ["James_Franco", -1]]]
["Anne_of_the_Thousand_Days", [["Richard_Burton", 766134264.0], ["Genevi%C3%A8ve_Bujold", -1], ["Anthony_Quayle", -1], ["John_Colicos", -1], ["Irene_Papas", 6134264.0]]]
["The_Blind_Side_(film)", [["Sandra_Bullock", -1], ["Tim_McGraw", 3092000000.0], ["Quinton_Aaron", -1], ["Jae_Head", 3092000000.0], ["Lily_Collins", -1], ["Ray_McKinnon_(actor)", -1], ["Kathy_Bates", -1]]]
["Merrily_We_Live", [["Constance_Bennett", 0], ["Brian_Aherne", -1]]]
["Last_Summer", [["Catherine_Burns", -1], ["Barbara_Hershey", 3695000003.0], ["Bruce_Davison", -1], ["Richard_Thomas_(actor)", -1]]]
["The_Sunshine_Boys_(1975_film)", [["Walter_Matthau", -1], ["George_Burns", -1], ["Richard_Benjamin", -1], ["Lee_Meredith", -1]]]
["The_Buddy_Holly_Story", [["Gary_Busey", -1], ["Don_Stroud", -1], ["Charles_Martin_Smith", -1], ["Conrad_Janis", -1], ["Paul_Mooney_(comedian)", -1]]]
["The_Robe_(film)", [["Richard_Burton", 766134264.0], ["Jean_Simmons", -1], ["Victor_Mature", -1], ["Michael_Rennie", -1]]]
["Sayonara", [["Marlon_Brando", -1], ["Patricia_Owens", -1], ["James_Garner", -1], ["Martha_Scott", -1], ["Miiko_Taka", -1], ["Miyoshi_Umeki", -1], ["Red_Buttons", -1], ["Ricardo_Montalb%C3%A1n", -1]]]
["You_Can%27t_Take_It_with_You_(film)", [["Jean_Arthur", -1], ["Lionel_Barrymore", 2137575.0], ["James_Stewart", -1], ["Edward_Arnold_(actor)", 2137575.0]]]
["A_Soldier%27s_Story", [["Howard_Rollins", -1], ["Adolph_Caesar", 1420000000.0]]]
["Leaving_Las_Vegas", [["Nicolas_Cage", 1632000000.0], ["Elisabeth_Shue", -1], ["Julian_Sands", -1]]]
["Hannah_and_Her_Sisters", [["Michael_Caine", -1], ["Mia_Farrow", -1], ["Carrie_Fisher", -1], ["Barbara_Hershey", 3695000003.0], ["Lloyd_Nolan", -1], ["Maureen_O%27Sullivan", -1], ["Daniel_Stern_(actor)", -1], ["Max_von_Sydow", -1], ["Dianne_Wiest", -1]]]
["The_Magnificent_Yankee_(1950_film)", [["Louis_Calhern", 0], ["Ann_Harding", -1], ["Eduard_Franz", -1], ["Philip_Ober", -1]]]
["Yankee_Doodle_Dandy", [["James_Cagney", -1], ["Joan_Leslie", -1], ["Walter_Huston", 0], ["Richard_Whorf", -1]]]
["The_Godfather", [["Marlon_Brando", -1], ["Al_Pacino", 0], ["James_Caan", -1], ["Richard_Castellano", -1], ["Robert_Duvall", -1], ["Sterling_Hayden", -1], ["John_Marley", -1], ["Richard_Conte", -1], ["Diane_Keaton", -1]]]
["Faces_(film)", [["John_Marley", -1], ["Gena_Rowlands", -1], ["Lynn_Carlin", -1], ["Seymour_Cassel", -1], ["Fred_Draper", -1], ["Val_Avery", -1], ["Dorothy_Gulliver", 0]]]
["Foxcatcher", [["Steve_Carell", -1], ["Channing_Tatum", -1], ["Mark_Ruffalo", -1], ["Vanessa_Redgrave", -1]]]
["Harry_and_Tonto", [["Art_Carney", -1], ["Herbert_Berghof", 46000000.0], ["Philip_Bruns", -1], ["Ellen_Burstyn", -1], ["Geraldine_Fitzgerald", -1], ["Larry_Hagman", -1], ["Chief_Dan_George", -1], ["Melanie_Mayron", -1], ["Josh_Mostel", 46000000.0], ["Arthur_Hunnicutt", 46000000.0], ["Barbara_Rhoades", -1], ["Cliff_DeYoung", -1], ["Avon_Long", -1]]]
["Lili", [["Leslie_Caron", -1], ["Mel_Ferrer", 0], ["Jean-Pierre_Aumont", 0], ["Zsa_Zsa_Gabor", -1]]]
["Claudine_(film)", [["Diahann_Carroll", -1], ["James_Earl_Jones", -1], ["Lawrence_Hilton-Jacobs", -1], ["Adam_Wade_(singer)", -1], ["Roxie_Roker", -1]]]
["Auntie_Mame_(film)", [["Rosalind_Russell", 93000000.0], ["Forrest_Tucker", -1], ["Coral_Browne", -1], ["Roger_Smith_(actor)", -1], ["Peggy_Cass", -1], ["Joanna_Barnes", -1], ["Robin_Hughes", -1], ["Pippa_Scott", -1]]]
["The_Devil%27s_Holiday", [["Nancy_Carroll", -1]]]
["The_Dirty_Dozen", [["Lee_Marvin", -1], ["Ernest_Borgnine", -1], ["Charles_Bronson", -1], ["Jim_Brown", -1], ["John_Cassavetes", 453000000.0], ["Richard_Jaeckel", -1], ["George_Kennedy", -1], ["Trini_Lopez", -1], ["Ralph_Meeker", -1], ["Robert_Ryan", -1], ["Telly_Savalas", -1], ["Clint_Walker", -1], ["Robert_Webber", -1]]]
["Lovers_and_Other_Strangers", [["Beatrice_Arthur", -1], ["Richard_S._Castellano", -1], ["Bonnie_Bedelia", -1], ["Gig_Young", -1]]]
["Whale_Rider", [["Keisha_Castle-Hughes", -1], ["Rawiri_Paratene", -1], ["Cliff_Curtis", -1]]]
["Broken_Arrow_(1950_film)", [["James_Stewart", -1], ["Jeff_Chandler", 3550000.0], ["Debra_Paget", -1]]]
["West_Side_Story_(film)", [["Natalie_Wood", -1], ["Richard_Beymer", -1], ["Rita_Moreno", -1], ["George_Chakiris", -1], ["Russ_Tamblyn", -1]]]
["Thoroughly_Modern_Millie", [["Julie_Andrews", -1], ["Mary_Tyler_Moore", -1], ["Carol_Channing", -1], ["James_Fox", -1], ["John_Gavin", -1], ["Beatrice_Lillie", 400000000.0]]]
["Six_Degrees_of_Separation_(film)", [["Stockard_Channing", -1], ["Will_Smith", -1], ["Donald_Sutherland", -1], ["Mary_Beth_Hurt", -1], ["Bruce_Davison", -1], ["Ian_McKellen", -1]]]
["The_Great_Dictator", [["Paulette_Goddard", -1], ["Jack_Oakie", 5.0], ["Henry_Daniell", -1], ["Reginald_Gardiner", -1], ["Billy_Gilbert", 5.0], ["Maurice_Moscovich", 5.0]]]
["Madame_X_(1929_film)", [["Ruth_Chatterton", -1], ["Lewis_Stone", 0]]]
["Zero_Dark_Thirty", [["Jessica_Chastain", -1], ["Jason_Clarke", -1], ["Joel_Edgerton", -1], ["Kyle_Chandler", -1], ["Mark_Strong", -1], ["Chris_Pratt", -1], ["James_Gandolfini", -1]]]
["Call_Me_by_Your_Name_(film)", [["Armie_Hammer", -1], ["Timoth%C3%A9e_Chalamet", -1], ["Michael_Stuhlbarg", -1], ["Amira_Casar", 419000000.0], ["Esther_Garrel", 419000000.0], ["Victoire_Du_Bois", -1]]]
["Moonstruck", [["Cher", -1], ["Nicolas_Cage", 1632000000.0], ["Vincent_Gardenia", -1], ["Olympia_Dukakis", -1], ["Danny_Aiello", -1]]]
["Hotel_Rwanda", [["Don_Cheadle", -1], ["Sophie_Okonedo", -1], ["Joaquin_Phoenix", -1], ["Nick_Nolte", -1]]]
["The_Love_Parade", [["Maurice_Chevalier", 0], ["Jeanette_MacDonald", 0], ["Lillian_Roth", 0], ["Eugene_Pallette", 0]]]
["Spellbound_(1945_film)", [["Ingrid_Bergman", 6387000.0], ["Gregory_Peck", -1], ["Michael_Chekhov", 6387000.0]]]
["Darling_(1965_film)", [["Julie_Christie", -1], ["Laurence_Harvey", 2400000.0], ["Dirk_Bogarde", 0]]]
["An_Unmarried_Woman", [["Jill_Clayburgh", -1], ["Alan_Bates", -1], ["Michael_Murphy_(actor)", -1], ["Cliff_Gorman", -1]]]
["Tom_Jones_(1963_film)", [["Albert_Finney", -1], ["Susannah_York", -1], ["Hugh_Griffith", -1], ["Edith_Evans", 37600000.0], ["Joan_Greenwood", -1], ["Diane_Cilento", 37600000.0], ["George_Devine", 37600000.0], ["David_Tomlinson", -1]]]
["Pieces_of_April", [["Katie_Holmes", -1], ["Derek_Luke_(actor)", -1], ["Sean_Hayes_(actor)", -1], ["Alison_Pill", -1], ["Oliver_Platt", -1], ["Patricia_Clarkson", -1]]]
["American_Graffiti", [["Richard_Dreyfuss", -1], ["Ron_Howard", -1], ["Paul_Le_Mat", -1], ["Charles_Martin_Smith", -1], ["Candy_Clark", -1], ["Mackenzie_Phillips", -1], ["Cindy_Williams", -1], ["Wolfman_Jack", -1]]]
["The_Search", [["Aline_MacMahon", 0], ["Jarmila_Novotn%C3%A1", -1], ["Wendell_Corey", -1], ["Ivan_Jandl", 0]]]
["Syriana", [["George_Clooney", -1], ["Matt_Damon", 940000000.0], ["Jeffrey_Wright_(actor)", -1], ["Chris_Cooper", 4831000000.0], ["William_Hurt", 972632093.0], ["Mazhar_Munir", -1], ["Tim_Blake_Nelson", -1], ["Amanda_Peet", -1], ["Christopher_Plummer", -1], ["Alexander_Siddig", 940000000.0]]]
["Affliction_(1997_film)", [["Nick_Nolte", -1], ["Sissy_Spacek", 62000000.0], ["James_Coburn", -1], ["Willem_Dafoe", 5384000000.0], ["Mary_Beth_Hurt", -1], ["Jim_True-Frost", -1]]]
["It_Happened_One_Night", [["Clark_Gable", 0], ["Claudette_Colbert", -1]]]
["The_Sixth_Sense", [["Bruce_Willis", -1], ["Toni_Collette", -1], ["Olivia_Williams", -1], ["Haley_Joel_Osment", -1]]]
["Shirley_Valentine_(film)", [["Pauline_Collins", -1], ["Tom_Conti", 6353913.0]]]
["The_Little_Foxes_(film)", [["Bette_Davis", -1], ["Herbert_Marshall", 5.0], ["Teresa_Wright", -1]]]
["The_Barker", [["Milton_Sills", 0], ["Dorothy_Mackaill", -1], ["Betty_Compson", 0], ["Douglas_Fairbanks_Jr.", 0]]]
["Reuben,_Reuben", [["Tom_Conti", 6353913.0], ["Kelly_McGillis", -1]]]
["The_Favourite", [["Olivia_Colman", -1], ["Emma_Stone", -1], ["Rachel_Weisz", -1], ["Nicholas_Hoult", -1], ["Joe_Alwyn", 826000000.0]]]
["A_Beautiful_Mind_(film)", [["Russell_Crowe", -1], ["Ed_Harris", -1], ["Jennifer_Connelly", -1], ["Paul_Bettany", 3130000000.0], ["Adam_Goldberg", -1], ["Judd_Hirsch", -1], ["Josh_Lucas", -1], ["Anthony_Rapp", -1], ["Christopher_Plummer", -1]]]
["Sergeant_York_(film)", [["Gary_Cooper", -1], ["Walter_Brennan", -1], ["Joan_Leslie", -1]]]
["Adaptation_(film)", [["Nicolas_Cage", 1632000000.0], ["Meryl_Streep", -1], ["Chris_Cooper", 4831000000.0], ["Brian_Cox_(actor)", -1], ["Tilda_Swinton", -1], ["Ron_Livingston", -1], ["Maggie_Gyllenhaal", -1]]]
["Now,_Voyager", [["Bette_Davis", -1], ["Paul_Henreid", 22000000.0], ["Claude_Rains", -1], ["Gladys_Cooper", -1]]]
["Silver_Linings_Playbook", [["Bradley_Cooper", -1], ["Jennifer_Lawrence", -1], ["Robert_De_Niro", 3813000000.0], ["Jacki_Weaver", -1], ["Anupam_Kher", 2364000000.0], ["Chris_Tucker", -1]]]
["Skippy_(film)", [["Jackie_Cooper", -1], ["Robert_Coogan", -1], ["Mitzi_Green", -1], ["Jackie_Searl", -1]]]
["La_Vie_en_rose_(film)", [["Marion_Cotillard", -1], ["G%C3%A9rard_Depardieu", 1276000000.0], ["Sylvie_Testud", 863000000.0]]]
["Day_for_Night_(film)", [["Jacqueline_Bisset", -1], ["Valentina_Cortese", -1], ["Dani_(singer)", -1], ["Alexandra_Stewart", -1], ["Jean-Pierre_Aumont", 0], ["Jean_Champion", 0], ["Jean-Pierre_L%C3%A9aud", 0], ["Fran%C3%A7ois_Truffaut", 3061000000.0]]]
["Dances_with_Wolves", [["Mary_McDonnell", -1], ["Graham_Greene_(actor)", -1], ["Rodney_A._Grant", -1]]]
["Pinky_(film)", [["Jeanne_Crain", -1], ["Ethel_Barrymore", 42000000.0], ["Ethel_Waters", 42000000.0]]]
["Trumbo_(2015_film)", [["Bryan_Cranston", -1], ["Adewale_Akinnuoye-Agbaje", -1], ["Louis_C.K.", -1], ["David_James_Elliott", -1], ["Elle_Fanning", -1], ["John_Goodman", -1], ["Diane_Lane", -1], ["Michael_Stuhlbarg", -1], ["Alan_Tudyk", -1], ["Helen_Mirren", -1]]]
["All_the_King%27s_Men_(1949_film)", [["Broderick_Crawford", -1], ["John_Ireland_(actor)", -1], ["Mercedes_McCambridge", -1], ["Joanne_Dru", -1], ["John_Derek", -1], ["Shepperd_Strudwick", -1]]]
["The_Seventh_Cross_(film)", [["Spencer_Tracy", 36000000.0], ["Signe_Hasso", -1], ["Hume_Cronyn", -1], ["Jessica_Tandy", -1], ["Agnes_Moorehead", -1], ["Herbert_Rudley", -1], ["Felix_Bressart", -1], ["Ray_Collins_(actor)", -1]]]
["Babe_(film)", [["James_Cromwell", -1], ["Magda_Szubanski", -1]]]
["The_Reivers_(film)", [["Steve_McQueen", -1], ["Sharon_Farrell", -1], ["Mitch_Vogel", -1], ["Rupert_Crosse", -1], ["Burgess_Meredith", -1], ["Will_Geer", -1]]]
["Places_in_the_Heart", [["Sally_Field", -1], ["Lindsay_Crouse", -1], ["Ed_Harris", -1], ["Ray_Baker_(actor)", -1], ["Amy_Madigan", -1], ["John_Malkovich", -1], ["Danny_Glover", 1769000000.0], ["Terry_O%27Quinn", -1]]]
["Vicky_Cristina_Barcelona", [["Javier_Bardem", -1], ["Pen%C3%A9lope_Cruz", -1], ["Scarlett_Johansson", -1], ["Patricia_Clarkson", -1], ["Kevin_Dunn", -1], ["Rebecca_Hall", -1], ["Chris_Messina", -1]]]
["Born_on_the_Fourth_of_July_(film)", [["Tom_Cruise", 1610000000.0], ["Kyra_Sedgwick", -1], ["Raymond_J._Barry", -1], ["Jerry_Levine", -1], ["Frank_Whaley", -1], ["Willem_Dafoe", 5384000000.0]]]
["Gladiator_(2000_film)", [["Russell_Crowe", -1], ["Joaquin_Phoenix", -1], ["Connie_Nielsen", -1], ["Oliver_Reed", -1], ["Derek_Jacobi", -1], ["Djimon_Hounsou", -1], ["Richard_Harris", 6197000000.0]]]
["The_Imitation_Game", [["Benedict_Cumberbatch", -1], ["Keira_Knightley", -1], ["Matthew_Goode", -1], ["Rory_Kinnear", -1], ["Charles_Dance", -1], ["Mark_Strong", -1]]]
["When_My_Baby_Smiles_at_Me_(film)", [["Betty_Grable", -1], ["Dan_Dailey", -1]]]
["At_Eternity%27s_Gate_(film)", [["Willem_Dafoe", 5384000000.0], ["Rupert_Friend", -1], ["Mads_Mikkelsen", -1], ["Mathieu_Amalric", -1], ["Emmanuelle_Seigner", -1], ["Oscar_Isaac", -1]]]
["The_Corn_Is_Green_(1945_film)", [["Bette_Davis", -1], ["Nigel_Bruce", -1], ["John_Dall", -1]]]
["Captain_Newman,_M.D.", [["Gregory_Peck", -1], ["Tony_Curtis", -1], ["Angie_Dickinson", -1], ["Robert_Duvall", -1], ["Eddie_Albert", -1], ["Bobby_Darin", 42500000.0]]]
["Carmen_Jones_(film)", [["Harry_Belafonte", -1], ["Dorothy_Dandridge", -1], ["Pearl_Bailey", -1]]]
["Good_Will_Hunting", [["Robin_Williams", -1], ["Stellan_Skarsg%C3%A5rd", -1], ["Minnie_Driver", -1]]]
["The_Crying_Game", [["Stephen_Rea", -1], ["Miranda_Richardson", -1], ["Jaye_Davidson", 625000000.0], ["Forest_Whitaker", -1]]]
["Dangerous_(film)", [["Bette_Davis", -1], ["Franchot_Tone", -1], ["Margaret_Lindsay", 0]]]
["The_Grapes_of_Wrath_(film)", [["Henry_Fonda", -1], ["Jane_Darwell", 25000000.0], ["John_Carradine", -1], ["Shirley_Mills", -1], ["John_Qualen", -1], ["Eddie_Quillan", -1]]]
["The_Accidental_Tourist_(film)", [["William_Hurt", 972632093.0], ["Kathleen_Turner", 32632093.0], ["Geena_Davis", -1]]]
["Fences_(film)", [["Viola_Davis", -1], ["Stephen_Henderson_(actor)", -1], ["Jovan_Adepo", -1], ["Russell_Hornsby", -1], ["Mykelti_Williamson", -1], ["Saniyya_Sidney", -1]]]
["Longtime_Companion", [["Stephen_Caffrey_(actor)", -1], ["Patrick_Cassidy_(actor)", -1], ["Bruce_Davison", -1], ["John_Dossett", -1], ["Mark_Lamos", -1], ["Dermot_Mulroney", -1], ["Mary-Louise_Parker", -1], ["Michael_Schoeffling", -1], ["Campbell_Scott", -1]]]
["Pillow_Talk_(film)", [["Rock_Hudson", -1], ["Doris_Day", -1], ["Tony_Randall", -1], ["Thelma_Ritter", -1]]]
["To_Each_His_Own_(film)", [["Olivia_de_Havilland", -1], ["Mary_Anderson_(actress,_born_1918)", -1], ["John_Lund_(actor)", -1]]]
["My_Left_Foot", [["Daniel_Day-Lewis", -1], ["Ray_McAnally", -1], ["Brenda_Fricker", -1], ["Cyril_Cusack", -1], ["Fiona_Shaw", -1], ["Hugh_O%27Conor", -1], ["Adrian_Dunbar", -1]]]
["A_Farewell_to_Arms_(1957_film)", [["Rock_Hudson", -1], ["Jennifer_Jones", 1597000005.0], ["Vittorio_De_Sica", 200000000.0], ["Elaine_Stritch", -1]]]
["Raging_Bull", [["Robert_De_Niro", 3813000000.0]]]
["East_of_Eden_(film)", [["James_Dean", -1], ["Julie_Harris_(actress)", -1], ["Raymond_Massey", 5.0], ["Jo_Van_Fleet", 5.0]]]
["The_Jolson_Story", [["Larry_Parks", 8.0], ["Evelyn_Keyes", -1], ["William_Demarest", -1], ["Bill_Goodwin", -1]]]
["American_Gangster_(film)", [["Denzel_Washington", 2665000000.0], ["Russell_Crowe", -1], ["Chiwetel_Ejiofor", -1], ["Cuba_Gooding_Jr.", -1], ["Josh_Brolin", -1], ["Ted_Levine", -1], ["Armand_Assante", -1], ["John_Ortiz", -1], ["John_Hawkes_(actor)", -1], ["Rza", -1]]]
["Indochine_(film)", [["Catherine_Deneuve", -1], ["Vincent_P%C3%A9rez", -1], ["Linh_Dan_Pham", -1], ["Jean_Yanne", -1], ["Dominique_Blanc", -1]]]
["Cyrano_de_Bergerac_(1990_film)", [["G%C3%A9rard_Depardieu", 1276000000.0], ["Anne_Brochet", -1], ["Vincent_P%C3%A9rez", -1], ["Jacques_Weber", -1]]]
["Who%27s_Afraid_of_Virginia_Woolf%3F_(film)", [["Elizabeth_Taylor", -1], ["Richard_Burton", 766134264.0], ["George_Segal", -1], ["Sandy_Dennis", -1]]]
["Nebraska_(film)", [["Bruce_Dern", -1], ["Will_Forte", -1], ["June_Squibb", -1], ["Stacy_Keach", -1], ["Bob_Odenkirk", -1]]]
["Rambling_Rose_(film)", [["Laura_Dern", -1], ["Diane_Ladd", -1], ["Lukas_Haas", -1], ["Robert_Duvall", -1], ["John_Heard_(actor)", -1]]]
["Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", [["Johnny_Depp", -1], ["Geoffrey_Rush", 10685000000.0], ["Orlando_Bloom", -1], ["Keira_Knightley", -1], ["Jonathan_Pryce", -1]]]
["Morocco_(film)", [["Gary_Cooper", -1], ["Marlene_Dietrich", -1], ["Adolphe_Menjou", 0]]]
["The_Revenant_(2015_film)", [["Leonardo_DiCaprio", -1], ["Tom_Hardy", -1], ["Domhnall_Gleeson", -1], ["Will_Poulter", -1]]]
["Cimarron_(1931_film)", [["Richard_Dix", 0], ["Irene_Dunne", -1]]]
["Goodbye,_Mr._Chips_(1939_film)", [["Robert_Donat", 0], ["Greer_Garson", -1], ["Terry_Kilburn", -1]]]
["Beau_Geste_(1939_film)", [["Gary_Cooper", -1], ["Ray_Milland", -1], ["Robert_Preston_(actor)", 35000000.0], ["Brian_Donlevy", -1], ["Susan_Hayward", -1]]]
["Close_Encounters_of_the_Third_Kind", [["Richard_Dreyfuss", -1], ["Teri_Garr", -1], ["Melinda_Dillon", -1], ["Fran%C3%A7ois_Truffaut", 3061000000.0]]]
["Champion_(1949_film)", [["Kirk_Douglas", -1], ["Marilyn_Maxwell", -1], ["Arthur_Kennedy", 25000000.0]]]
["Hud_(1963_film)", [["Paul_Newman", -1], ["Melvyn_Douglas", -1], ["Patricia_Neal", -1], ["Brandon_deWilde", -1]]]
["Wall_Street_(1987_film)", [["Michael_Douglas", -1], ["Charlie_Sheen", -1], ["Daryl_Hannah", -1], ["Martin_Sheen", -1], ["Hal_Holbrook", -1], ["Terence_Stamp", -1]]]
["One_Flew_Over_the_Cuckoo%27s_Nest_(film)", [["Jack_Nicholson", -1], ["Louise_Fletcher", -1], ["William_Redfield_(actor)", -1]]]
["A_Ship_Comes_In", [["Rudolph_Schildkraut", -1], ["Louise_Dresser", 0], ["index.php?title=Milton_Holmes&action=edit&redlink=1", -1], ["index.php?title=Linda_Landi&action=edit&redlink=1", -1]]]
["Min_and_Bill", [["Marie_Dressler", 2.0], ["Wallace_Beery", 16000002.0]]]
["BlacKkKlansman", [["John_David_Washington", -1], ["Adam_Driver", -1], ["Laura_Harrier", -1], ["Topher_Grace", -1]]]
["The_Green_Mile_(film)", [["Tom_Hanks", -1], ["David_Morse_(actor)", -1], ["Bonnie_Hunt", -1], ["Michael_Clarke_Duncan", -1], ["James_Cromwell", -1], ["Michael_Jeter", -1], ["Graham_Greene_(actor)", -1], ["Doug_Hutchison", -1], ["Sam_Rockwell", 2907000000.0], ["Barry_Pepper", -1], ["Jeffrey_DeMunn", -1], ["Patricia_Clarkson", -1], ["Harry_Dean_Stanton", -1]]]
["A_Tree_Grows_in_Brooklyn_(1945_film)", [["Dorothy_McGuire", -1], ["Joan_Blondell", 3.0], ["James_Dunn_(actor)", -1], ["Lloyd_Nolan", -1], ["Peggy_Ann_Garner", -1], ["Ted_Donaldson", -1], ["James_Gleason", -1], ["Ruth_Nelson_(actress)", -1], ["John_Alexander_(actor)", -1], ["B.S._Pully", -1]]]
["Ship_of_Fools_(film)", [["Vivien_Leigh", 3500000.0], ["Jos%C3%A9_Ferrer", 22500000.0], ["Lee_Marvin", -1], ["Simone_Signoret", -1]]]
["Death_of_a_Salesman_(1951_film)", [["Fredric_March", 12000000.0], ["Mildred_Dunnock", -1], ["Kevin_McCarthy_(actor)", -1], ["Cameron_Mitchell_(actor)", -1]]]
["The_Best_Little_Whorehouse_in_Texas_(film)", [["Burt_Reynolds", -1], ["Dolly_Parton", -1], ["Dom_DeLuise", -1], ["Charles_Durning", -1], ["Jim_Nabors", -1]]]
["The_Letter_(1929_film)", [["Jeanne_Eagels", 0], ["O._P._Heggie", -1]]]
["The_Collector_(1965_film)", [["Terence_Stamp", -1], ["Samantha_Eggar", -1], ["Mona_Washbourne", -1]]]
["Tender_Mercies", [["Robert_Duvall", -1], ["Tess_Harper", -1], ["Betty_Buckley", -1], ["Wilford_Brimley", -1], ["Ellen_Barkin", -1]]]
["Unforgiven", [["Gene_Hackman", 2292000000.0], ["Morgan_Freeman", -1], ["Richard_Harris", 6197000000.0]]]
["A_Room_with_a_View_(1985_film)", [["Maggie_Smith", -1], ["Denholm_Elliott", -1], ["Judi_Dench", -1], ["Simon_Callow", -1], ["Helena_Bonham_Carter", -1], ["Julian_Sands", -1], ["Daniel_Day-Lewis", -1], ["Fabia_Drake", -1], ["Patrick_Godfrey", -1], ["Rupert_Graves", -1], ["Rosemary_Leach", -1]]]
["12_Years_a_Slave_(film)", [["Chiwetel_Ejiofor", -1], ["Michael_Fassbender", -1], ["Benedict_Cumberbatch", -1], ["Paul_Dano", -1], ["Paul_Giamatti", -1], ["Lupita_Nyong%27o", -1], ["Sarah_Paulson", -1], ["Brad_Pitt", -1], ["Alfre_Woodard", -1]]]
["Caged", [["Eleanor_Parker", -1], ["Agnes_Moorehead", -1], ["Betty_Garde", -1], ["Hope_Emerson", -1], ["Ellen_Corby", -1]]]
["Pigskin_Parade", [["Stuart_Erwin", -1], ["Patsy_Kelly", -1], ["Jack_Haley", -1], ["Betty_Grable", -1], ["Judy_Garland", -1]]]
["The_Social_Network", [["Jesse_Eisenberg", -1], ["Andrew_Garfield", -1], ["Justin_Timberlake", -1], ["Armie_Hammer", -1], ["Max_Minghella", -1]]]
["A_Star_Is_Born_(2018_film)", [["Lady_Gaga", -1], ["Andrew_Dice_Clay", -1], ["Dave_Chappelle", -1], ["Sam_Elliott", -1]]]
["The_Whisperers", [["Edith_Evans", 37600000.0]]]
["Murder,_Inc._(1960_film)", [["Stuart_Whitman", -1], ["May_Britt", -1], ["Henry_Morgan_(comedian)", -1], ["Peter_Falk", -1]]]
["The_Straight_Story", [["Richard_Farnsworth", -1], ["Sissy_Spacek", 62000000.0], ["Harry_Dean_Stanton", -1]]]
["Cyrano_de_Bergerac_(1950_film)", [["Jos%C3%A9_Ferrer", 22500000.0], ["Mala_Powers", -1], ["William_Prince_(actor)", -1]]]
["Norma_Rae", [["Sally_Field", -1], ["Beau_Bridges", -1], ["Ron_Leibman", -1]]]
["Up_in_the_Air_(2009_film)", [["George_Clooney", -1], ["Vera_Farmiga", -1], ["Anna_Kendrick", -1], ["Danny_McBride", -1]]]
["Steve_Jobs_(film)", [["Michael_Fassbender", -1], ["Kate_Winslet", -1], ["Seth_Rogen", -1], ["Jeff_Daniels", -1]]]
["Othello_(1965_British_film)", [["Laurence_Olivier", -1], ["Maggie_Smith", -1], ["Joyce_Redman", -1], ["Frank_Finlay", -1]]]
["Equus_(film)", [["Richard_Burton", 766134264.0], ["Peter_Firth", -1], ["Jenny_Agutter", -1], ["Joan_Plowright", -1], ["Colin_Blakely", -1]]]
["Wuthering_Heights_(1939_film)", [["Merle_Oberon", 0], ["Laurence_Olivier", -1], ["David_Niven", -1], ["Geraldine_Fitzgerald", -1]]]
["On_Golden_Pond_(1981_film)", [["Katharine_Hepburn", -1], ["Henry_Fonda", -1], ["Jane_Fonda", -1], ["Doug_McKeon", -1], ["Dabney_Coleman", -1], ["William_Lanteau", -1]]]
["Klute", [["Jane_Fonda", -1], ["Donald_Sutherland", -1], ["Charles_Cioffi", -1], ["Roy_Scheider", -1]]]
["Ulee%27s_Gold", [["Peter_Fonda", -1], ["Patricia_Richardson", -1], ["Jessica_Biel", -1], ["J._Kenneth_Campbell", -1], ["Christine_Dunford", -1], ["Thomas_Mills_Wood", -1], ["Vanessa_Zima", -1]]]
["Suspicion_(1941_film)", [["Cary_Grant", -1], ["Joan_Fontaine", 10.5], ["Cedric_Hardwicke", -1], ["Nigel_Bruce", -1], ["Dame_May_Whitty", -1]]]
["The_Guardsman", [["Alfred_Lunt", -1], ["Lynn_Fontanne", -1]]]
["Witness_(1985_film)", [["Harrison_Ford", -1]]]
["The_Rose_(film)", [["Bette_Midler", -1], ["Alan_Bates", -1], ["Frederic_Forrest", -1], ["Harry_Dean_Stanton", -1]]]
["Jackie_Brown", [["Pam_Grier", -1], ["Samuel_L._Jackson", -1], ["Robert_Forster", -1], ["Bridget_Fonda", -1], ["Michael_Keaton", -1], ["Robert_De_Niro", 3813000000.0]]]
["The_Accused_(1988_film)", [["Jodie_Foster", -1], ["Kelly_McGillis", -1], ["Bernie_Coulson", -1], ["Leo_Rossi", -1], ["Ann_Hearn", -1], ["Carmen_Argenziano", -1], ["Steve_Antin", -1]]]
["A_Hatful_of_Rain", [["Don_Murray_(actor)", -1], ["Eva_Marie_Saint", -1], ["Anthony_Franciosa", -1]]]
["Ray_(film)", [["Jamie_Foxx", -1], ["Kerry_Washington", -1], ["Clifton_Powell", -1], ["Harry_Lennix", -1], ["Terrence_Howard", -1], ["Larenz_Tate", -1], ["Richard_Schiff", -1], ["Regina_King", -1]]]
["127_Hours", [["James_Franco", -1], ["Kate_Mara", -1], ["Amber_Tamblyn", -1]]]
["Fiddler_on_the_Roof_(film)", [["Chaim_Topol", 833000000.0], ["Norma_Crane", -1], ["Leonard_Frey", -1], ["Molly_Picon", -1], ["Paul_Mann", -1]]]
["Christian_Bale", [["The_Fighter", 3906000000.0], ["American_Hustle", 3906000000.0], ["Henry_V_(1989_film)", 3906000000.0]]]
["Amy_Adams", [["The_Fighter", -1], ["American_Hustle", -1]]]
["Melissa_Leo", [["The_Fighter", -1]]]
["Jack_McGee_(actor)", [["The_Fighter", -1]]]
["Natalie_Portman", [["Black_Swan_(film)", -1]]]
["Vincent_Cassel", [["Black_Swan_(film)", 3294000000.0]]]
["Mila_Kunis", [["Black_Swan_(film)", -1]]]
["Barbara_Hershey", [["Black_Swan_(film)", 3695000003.0], ["Last_Summer", 3695000003.0], ["Hannah_and_Her_Sisters", 3695000003.0]]]
["Winona_Ryder", [["Black_Swan_(film)", -1]]]
["Colin_Firth", [["The_King%27s_Speech", -1], ["The_English_Patient_(film)", -1]]]
["Geoffrey_Rush", [["The_King%27s_Speech", 10685000000.0], ["Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", 10685000000.0]]]
["Helena_Bonham_Carter", [["The_King%27s_Speech", -1], ["The_Wings_of_the_Dove_(1997_film)", -1], ["A_Room_with_a_View_(1985_film)", -1]]]
["Guy_Pearce", [["The_King%27s_Speech", -1], ["L.A._Confidential_(film)", -1]]]
["Timothy_Spall", [["The_King%27s_Speech", -1], ["Secrets_%26_Lies_(film)", -1]]]
["Derek_Jacobi", [["The_King%27s_Speech", -1], ["Henry_V_(1989_film)", -1], ["Gladiator_(2000_film)", -1]]]
["Jennifer_Ehle", [["The_King%27s_Speech", -1]]]
["Michael_Gambon", [["The_King%27s_Speech", -1], ["The_Wings_of_the_Dove_(1997_film)", -1]]]
["Tom_Hanks", [["Captain_Phillips_(film)", -1], ["The_Green_Mile_(film)", -1]]]
["Barkhad_Abdi", [["Captain_Phillips_(film)", 2188000000.0]]]
["Richard_Chamberlain", [["Twilight_of_Honor", -1], ["The_Towering_Inferno", -1]]]
["Nick_Adams_(actor,_born_1931)", [["Twilight_of_Honor", -1]]]
["F._Murray_Abraham", [["Amadeus_(film)", -1]]]
["Tom_Hulce", [["Amadeus_(film)", 520000000.0]]]
["Elizabeth_Berridge_(actress)", [["Amadeus_(film)", -1]]]
["Simon_Callow", [["Amadeus_(film)", -1], ["A_Room_with_a_View_(1985_film)", -1]]]
["Roy_Dotrice", [["Amadeus_(film)", -1]]]
["Christine_Ebersole", [["Amadeus_(film)", -1]]]
["Jeffrey_Jones", [["Amadeus_(film)", -1]]]
["Charles_Kay", [["Amadeus_(film)", -1]]]
["Bradley_Cooper", [["American_Hustle", -1], ["Silver_Linings_Playbook", -1]]]
["Jeremy_Renner", [["American_Hustle", -1]]]
["Jennifer_Lawrence", [["American_Hustle", -1], ["Silver_Linings_Playbook", -1]]]
["Louis_C._K.", [["American_Hustle", -1]]]
["Michael_Pe%C3%B1a", [["American_Hustle", -1]]]
["Alessandro_Nivola", [["American_Hustle", -1]]]
["Isabelle_Adjani", [["The_Story_of_Adele_H.", 0]]]
["Bruce_Robinson", [["The_Story_of_Adele_H.", -1]]]
["Ben_Kingsley", [["House_of_Sand_and_Fog_(film)", -1]]]
["Shohreh_Aghdashloo", [["House_of_Sand_and_Fog_(film)", -1]]]
["Jennifer_Connelly", [["House_of_Sand_and_Fog_(film)", -1], ["A_Beautiful_Mind_(film)", -1]]]
["Ron_Eldard", [["House_of_Sand_and_Fog_(film)", -1]]]
["Frances_Fisher", [["House_of_Sand_and_Fog_(film)", -1]]]
["Kim_Dickens", [["House_of_Sand_and_Fog_(film)", -1]]]
["Paul_Muni", [["Juarez_(film)", 0]]]
["Bette_Davis", [["Juarez_(film)", -1], ["The_Great_Lie", -1], ["Jezebel_(film)", -1], ["The_Little_Foxes_(film)", -1], ["Now,_Voyager", -1], ["The_Corn_Is_Green_(1945_film)", -1], ["Dangerous_(film)", -1]]]
["Brian_Aherne", [["Juarez_(film)", -1], ["Merrily_We_Live", -1]]]
["John_Garfield", [["Juarez_(film)", 0]]]
["Casey_Affleck", [["Manchester_by_the_Sea_(film)", -1]]]
["Michelle_Williams_(actress)", [["Manchester_by_the_Sea_(film)", -1]]]
["Kyle_Chandler", [["Manchester_by_the_Sea_(film)", -1], ["Zero_Dark_Thirty", -1]]]
["Gretchen_Mol", [["Manchester_by_the_Sea_(film)", -1]]]
["Lucas_Hedges", [["Manchester_by_the_Sea_(film)", -1]]]
["Danny_Aiello", [["Do_the_Right_Thing", -1], ["Moonstruck", -1]]]
["Ossie_Davis", [["Do_the_Right_Thing", -1]]]
["Ruby_Dee", [["Do_the_Right_Thing", -1]]]
["Richard_Edson", [["Do_the_Right_Thing", -1]]]
["Giancarlo_Esposito", [["Do_the_Right_Thing", -1]]]
["Bill_Nunn", [["Do_the_Right_Thing", -1]]]
["John_Turturro", [["Do_the_Right_Thing", -1]]]
["John_Savage_(actor)", [["Do_the_Right_Thing", -1]]]
["Gregory_Peck", [["Roman_Holiday", -1], ["To_Kill_a_Mockingbird_(film)", -1], ["Spellbound_(1945_film)", -1], ["Captain_Newman,_M.D.", -1]]]
["Audrey_Hepburn", [["Roman_Holiday", 120000000.0]]]
["Patricia_Neal", [["The_Subject_Was_Roses_(film)", -1], ["Hud_(1963_film)", -1]]]
["Jack_Albertson", [["The_Subject_Was_Roses_(film)", -1]]]
["Martin_Sheen", [["The_Subject_Was_Roses_(film)", -1], ["Wall_Street_(1987_film)", -1]]]
["Anouk_Aim%C3%A9e", [["A_Man_and_a_Woman", 14000000.0]]]
["Jean-Louis_Trintignant", [["A_Man_and_a_Woman", 14000000.0]]]
["Liv_Ullmann", [["Gaby:_A_True_Story", -1]]]
["Norma_Aleandro", [["Gaby:_A_True_Story", 125400.0]]]
["Robert_Loggia", [["Gaby:_A_True_Story", -1]]]
["Lawrence_Monoson", [["Gaby:_A_True_Story", -1]]]
["Rachel_Chagall", [["Gaby:_A_True_Story", -1]]]
["James_Earl_Jones", [["The_Great_White_Hope_(film)", -1], ["Claudine_(film)", -1]]]
["Jane_Alexander", [["The_Great_White_Hope_(film)", -1]]]
["Leonardo_DiCaprio", [["The_Aviator_(2004_film)", -1], ["The_Revenant_(2015_film)", -1]]]
["Cate_Blanchett", [["The_Aviator_(2004_film)", -1], ["Babel_(film)", -1], ["Blue_Jasmine", -1]]]
["Kate_Beckinsale", [["The_Aviator_(2004_film)", -1]]]
["John_C._Reilly", [["The_Aviator_(2004_film)", -1]]]
["Alec_Baldwin", [["The_Aviator_(2004_film)", -1], ["The_Cooler", -1], ["Blue_Jasmine", -1]]]
["Alan_Alda", [["The_Aviator_(2004_film)", -1]]]
["Ian_Holm", [["The_Aviator_(2004_film)", -1], ["Henry_V_(1989_film)", -1]]]
["Danny_Huston", [["The_Aviator_(2004_film)", -1]]]
["Gwen_Stefani", [["The_Aviator_(2004_film)", -1]]]
["Jude_Law", [["The_Aviator_(2004_film)", -1]]]
["Gary_Oldman", [["The_Contender_(2000_film)", -1]]]
["Joan_Allen", [["The_Contender_(2000_film)", -1]]]
["Jeff_Bridges", [["The_Contender_(2000_film)", -1], ["The_Mirror_Has_Two_Faces", -1], ["Crazy_Heart", -1]]]
["Christian_Slater", [["The_Contender_(2000_film)", -1]]]
["William_Petersen", [["The_Contender_(2000_film)", -1]]]
["Philip_Baker_Hall", [["The_Contender_(2000_film)", -1]]]
["Saul_Rubinek", [["The_Contender_(2000_film)", -1]]]
["Sam_Elliott", [["The_Contender_(2000_film)", -1], ["A_Star_Is_Born_(2018_film)", -1]]]
["Don_Ameche", [["Cocoon_(film)", 878000000.0], ["In_Old_Chicago", 878000000.0]]]
["Wilford_Brimley", [["Cocoon_(film)", -1], ["Tender_Mercies", -1]]]
["Hume_Cronyn", [["Cocoon_(film)", -1], ["The_Seventh_Cross_(film)", -1]]]
["Brian_Dennehy", [["Cocoon_(film)", -1]]]
["Jack_Gilford", [["Cocoon_(film)", -1]]]
["Steve_Guttenberg", [["Cocoon_(film)", -1]]]
["Maureen_Stapleton", [["Cocoon_(film)", -1]]]
["Jessica_Tandy", [["Cocoon_(film)", -1], ["Driving_Miss_Daisy", -1], ["The_Seventh_Cross_(film)", -1]]]
["Gwen_Verdon", [["Cocoon_(film)", 853000000.0]]]
["Herta_Ware", [["Cocoon_(film)", -1]]]
["Tahnee_Welch", [["Cocoon_(film)", 853000000.0]]]
["Trevante_Rhodes", [["Moonlight_(2016_film)", -1]]]
["Andr%C3%A9_Holland", [["Moonlight_(2016_film)", -1]]]
["Janelle_Mon%C3%A1e", [["Moonlight_(2016_film)", 652000000.0]]]
["Ashton_Sanders", [["Moonlight_(2016_film)", -1]]]
["Naomie_Harris", [["Moonlight_(2016_film)", -1]]]
["Mahershala_Ali", [["Moonlight_(2016_film)", -1]]]
["Diane_Keaton", [["Annie_Hall", -1], ["The_Godfather", -1]]]
["Tony_Roberts_(actor)", [["Annie_Hall", -1]]]
["Carol_Kane", [["Annie_Hall", -1]]]
["Paul_Simon", [["Annie_Hall", -1]]]
["Janet_Margolin", [["Annie_Hall", -1]]]
["Shelley_Duvall", [["Annie_Hall", -1]]]
["Christopher_Walken", [["Annie_Hall", 383000000.0]]]
["Colleen_Dewhurst", [["Annie_Hall", -1]]]
["Walter_Pidgeon", [["How_Green_Was_My_Valley_(film)", -1]]]
["Maureen_O%27Hara", [["How_Green_Was_My_Valley_(film)", -1]]]
["Donald_Crisp", [["How_Green_Was_My_Valley_(film)", 28000000.0], ["Jezebel_(film)", 28000000.0]]]
["Anna_Lee", [["How_Green_Was_My_Valley_(film)", -1]]]
["Roddy_McDowall", [["How_Green_Was_My_Valley_(film)", -1]]]
["Laurence_Olivier", [["Rebecca_(1940_film)", -1], ["Othello_(1965_British_film)", -1], ["Wuthering_Heights_(1939_film)", -1]]]
["Joan_Fontaine", [["Rebecca_(1940_film)", 10.5], ["Suspicion_(1941_film)", 10.5]]]
["Ann-Margret", [["Tommy_(1975_film)", 343000000.0]]]
["Oliver_Reed", [["Tommy_(1975_film)", -1], ["Gladiator_(2000_film)", -1]]]
["Roger_Daltrey", [["Tommy_(1975_film)", -1]]]
["Elton_John", [["Tommy_(1975_film)", 343000000.0]]]
["Eric_Clapton", [["Tommy_(1975_film)", -1]]]
["John_Entwistle", [["Tommy_(1975_film)", -1]]]
["Keith_Moon", [["Tommy_(1975_film)", -1]]]
["Paul_Nicholas", [["Tommy_(1975_film)", -1]]]
["Jack_Nicholson", [["Tommy_(1975_film)", -1], ["Five_Easy_Pieces", -1], ["One_Flew_Over_the_Cuckoo%27s_Nest_(film)", -1]]]
["Robert_Powell", [["Tommy_(1975_film)", -1]]]
["Arthur_Brown_(musician)", [["Tommy_(1975_film)", -1]]]
["Pete_Townshend", [["Tommy_(1975_film)", -1]]]
["Tina_Turner", [["Tommy_(1975_film)", -1]]]
["Julie_Andrews", [["Mary_Poppins_(film)", -1], ["Thoroughly_Modern_Millie", -1]]]
["Dick_Van_Dyke", [["Mary_Poppins_(film)", -1]]]
["David_Tomlinson", [["Mary_Poppins_(film)", -1], ["Tom_Jones_(1963_film)", -1]]]
["Glynis_Johns", [["Mary_Poppins_(film)", -1]]]
["Hermione_Baddeley", [["Mary_Poppins_(film)", -1], ["Room_at_the_Top_(1959_film)", -1]]]
["Karen_Dotrice", [["Mary_Poppins_(film)", -1]]]
["Matthew_Garber", [["Mary_Poppins_(film)", 1023000000.0]]]
["Elsa_Lanchester", [["Mary_Poppins_(film)", -1]]]
["Arthur_Treacher", [["Mary_Poppins_(film)", -1]]]
["Reginald_Owen", [["Mary_Poppins_(film)", -1], ["Conquest_(1937_film)", -1]]]
["Ed_Wynn", [["Mary_Poppins_(film)", -1]]]
["Michael_Douglas", [["Fatal_Attraction", -1], ["Wall_Street_(1987_film)", -1]]]
["Glenn_Close", [["Fatal_Attraction", -1]]]
["Anne_Archer", [["Fatal_Attraction", -1]]]
["Joan_Crawford", [["Mildred_Pierce_(film)", -1], ["The_Gorgeous_Hussy", -1]]]
["Jack_Carson", [["Mildred_Pierce_(film)", -1]]]
["Zachary_Scott", [["Mildred_Pierce_(film)", -1]]]
["Eve_Arden", [["Mildred_Pierce_(film)", -1]]]
["Ann_Blyth", [["Mildred_Pierce_(film)", -1]]]
["Bruce_Bennett", [["Mildred_Pierce_(film)", -1]]]
["Yalitza_Aparicio", [["Roma_(2018_film)", 41000000.0]]]
["Marina_de_Tavira", [["Roma_(2018_film)", 41000000.0]]]
["George_Arliss", [["Disraeli_(1929_film)", 0]]]
["Doris_Lloyd", [["Disraeli_(1929_film)", -1]]]
["David_Torrence", [["Disraeli_(1929_film)", 0]]]
["Joan_Bennett", [["Disraeli_(1929_film)", -1]]]
["Jean_Arthur", [["The_More_the_Merrier", -1], ["You_Can%27t_Take_It_with_You_(film)", -1]]]
["Joel_McCrea", [["The_More_the_Merrier", 18000000.0], ["Foreign_Correspondent_(film)", 18000000.0], ["Come_and_Get_It_(1936_film)", 18000000.0]]]
["Charles_Coburn", [["The_More_the_Merrier", 18000000.0]]]
["Greg_Kinnear", [["Little_Miss_Sunshine", -1]]]
["Steve_Carell", [["Little_Miss_Sunshine", -1], ["Foxcatcher", -1]]]
["Toni_Collette", [["Little_Miss_Sunshine", -1], ["The_Sixth_Sense", -1]]]
["Paul_Dano", [["Little_Miss_Sunshine", -1], ["12_Years_a_Slave_(film)", -1]]]
["Abigail_Breslin", [["Little_Miss_Sunshine", -1]]]
["Alan_Arkin", [["Little_Miss_Sunshine", -1]]]
["Peggy_Ashcroft", [["A_Passage_to_India_(film)", -1]]]
["Judy_Davis", [["A_Passage_to_India_(film)", -1]]]
["James_Fox", [["A_Passage_to_India_(film)", -1], ["Thoroughly_Modern_Millie", -1]]]
["Alec_Guinness", [["A_Passage_to_India_(film)", -1]]]
["Nigel_Havers", [["A_Passage_to_India_(film)", -1]]]
["Victor_Banerjee", [["A_Passage_to_India_(film)", -1]]]
["Roshan_Seth", [["A_Passage_to_India_(film)", 272000000.0]]]
["George_Brent", [["The_Great_Lie", -1], ["Jezebel_(film)", -1]]]
["Mary_Astor", [["The_Great_Lie", -1]]]
["Patricia_Arquette", [["Boyhood_(film)", -1]]]
["Ellar_Coltrane", [["Boyhood_(film)", 573000000.0]]]
["Lorelei_Linklater", [["Boyhood_(film)", 573000000.0]]]
["Ethan_Hawke", [["Boyhood_(film)", 573000000.0]]]
["Steve_McQueen", [["The_Towering_Inferno", -1], ["The_Reivers_(film)", -1]]]
["Paul_Newman", [["The_Towering_Inferno", -1], ["Hud_(1963_film)", -1]]]
["William_Holden", [["The_Towering_Inferno", -1]]]
["Faye_Dunaway", [["The_Towering_Inferno", -1], ["Bonnie_and_Clyde_(film)", -1]]]
["Fred_Astaire", [["The_Towering_Inferno", -1]]]
["Susan_Blakely", [["The_Towering_Inferno", -1]]]
["Jennifer_Jones", [["The_Towering_Inferno", 1597000005.0], ["The_Song_of_Bernadette_(film)", 1597000005.0], ["A_Farewell_to_Arms_(1957_film)", 1597000005.0]]]
["O._J._Simpson", [["The_Towering_Inferno", -1]]]
["Robert_Vaughn", [["The_Towering_Inferno", -1]]]
["Robert_Wagner", [["The_Towering_Inferno", -1]]]
["William_Powell", [["My_Man_Godfrey", 0]]]
["Carole_Lombard", [["My_Man_Godfrey", 0]]]
["Alice_Brady", [["My_Man_Godfrey", 25000000.0], ["In_Old_Chicago", 25000000.0]]]
["Gail_Patrick", [["My_Man_Godfrey", -1]]]
["Eugene_Pallette", [["My_Man_Godfrey", 0], ["The_Love_Parade", 0]]]
["Jean_Dixon", [["My_Man_Godfrey", 0]]]
["Alan_Mowbray", [["My_Man_Godfrey", -1]]]
["Danny_Glover", [["The_Color_Purple_(film)", 1769000000.0], ["Places_in_the_Heart", 1769000000.0]]]
["Adolph_Caesar", [["The_Color_Purple_(film)", 1420000000.0], ["A_Soldier%27s_Story", 1420000000.0]]]
["Margaret_Avery", [["The_Color_Purple_(film)", -1]]]
["Rae_Dawn_Chong", [["The_Color_Purple_(film)", -1]]]
["Whoopi_Goldberg", [["The_Color_Purple_(film)", -1]]]
["Morgan_Freeman", [["Driving_Miss_Daisy", -1], ["Unforgiven", -1]]]
["Dan_Aykroyd", [["Driving_Miss_Daisy", -1]]]
["Patti_LuPone", [["Driving_Miss_Daisy", -1]]]
["Esther_Rolle", [["Driving_Miss_Daisy", -1]]]
["Jane_Wyman", [["Johnny_Belinda_(1948_film)", -1], ["The_Blue_Veil_(1951_film)", -1]]]
["Lew_Ayres", [["Johnny_Belinda_(1948_film)", -1]]]
["Charles_Bickford", [["Johnny_Belinda_(1948_film)", -1], ["The_Song_of_Bernadette_(film)", -1]]]
["Agnes_Moorehead", [["Johnny_Belinda_(1948_film)", -1], ["The_Seventh_Cross_(film)", -1], ["Caged", -1]]]
["Pierce_Brosnan", [["The_Mirror_Has_Two_Faces", -1]]]
["George_Segal", [["The_Mirror_Has_Two_Faces", -1], ["Who%27s_Afraid_of_Virginia_Woolf%3F_(film)", -1]]]
["Mimi_Rogers", [["The_Mirror_Has_Two_Faces", -1]]]
["Brenda_Vaccaro", [["The_Mirror_Has_Two_Faces", -1]]]
["Lauren_Bacall", [["The_Mirror_Has_Two_Faces", 704610201.0], ["Misery_(film)", 704610201.0]]]
["Laurence_Harvey", [["Room_at_the_Top_(1959_film)", 2400000.0], ["Darling_(1965_film)", 2400000.0]]]
["Simone_Signoret", [["Room_at_the_Top_(1959_film)", -1], ["Ship_of_Fools_(film)", -1]]]
["Heather_Sears", [["Room_at_the_Top_(1959_film)", 2400000.0]]]
["Donald_Wolfit", [["Room_at_the_Top_(1959_film)", 2400000.0]]]
["Mary_Badham", [["To_Kill_a_Mockingbird_(film)", 131000000.0]]]
["Phillip_Alford", [["To_Kill_a_Mockingbird_(film)", -1]]]
["John_Megna", [["To_Kill_a_Mockingbird_(film)", -1]]]
["Ruth_White_(actress)", [["To_Kill_a_Mockingbird_(film)", -1]]]
["Paul_Fix", [["To_Kill_a_Mockingbird_(film)", -1]]]
["Brock_Peters", [["To_Kill_a_Mockingbird_(film)", -1]]]
["Frank_Overton", [["To_Kill_a_Mockingbird_(film)", -1]]]
["Henry_Fonda", [["Jezebel_(film)", -1], ["The_Grapes_of_Wrath_(film)", -1], ["On_Golden_Pond_(1981_film)", -1]]]
["Margaret_Lindsay", [["Jezebel_(film)", 0], ["Dangerous_(film)", 0]]]
["Fay_Bainter", [["Jezebel_(film)", 0]]]
["Richard_Cromwell_(actor)", [["Jezebel_(film)", 0]]]
["Henry_O%27Neill", [["Jezebel_(film)", 0]]]
["Spring_Byington", [["Jezebel_(film)", -1]]]
["John_Litel", [["Jezebel_(film)", 0]]]
["Karl_Malden", [["Baby_Doll", -1], ["On_the_Waterfront", -1]]]
["Carroll_Baker", [["Baby_Doll", 23000000.0]]]
["Eli_Wallach", [["Baby_Doll", -1]]]
["William_H._Macy", [["The_Cooler", -1]]]
["Maria_Bello", [["The_Cooler", -1]]]
["Shawn_Hatosy", [["The_Cooler", -1]]]
["Ron_Livingston", [["The_Cooler", -1], ["Adaptation_(film)", -1]]]
["Jason_Robards", [["A_Thousand_Clowns", -1]]]
["Barbara_Harris_(actress)", [["A_Thousand_Clowns", -1]]]
["Martin_Balsam", [["A_Thousand_Clowns", -1]]]
["Barry_Gordon", [["A_Thousand_Clowns", -1]]]
["Anne_Bancroft", [["The_Miracle_Worker_(1962_film)", -1], ["The_Turning_Point_(1977_film)", -1]]]
["Patty_Duke", [["The_Miracle_Worker_(1962_film)", -1]]]
["George_Bancroft_(actor)", [["Thunderbolt_(1929_film)", 0]]]
["Fay_Wray", [["Thunderbolt_(1929_film)", -1]]]
["Richard_Arlen", [["Thunderbolt_(1929_film)", -1]]]
["Tully_Marshall", [["Thunderbolt_(1929_film)", 0]]]
["Eugenie_Besserer", [["Thunderbolt_(1929_film)", 0]]]
["James_Stewart", [["The_Flight_of_the_Phoenix_(1965_film)", -1], ["You_Can%27t_Take_It_with_You_(film)", -1], ["Broken_Arrow_(1950_film)", -1]]]
["Richard_Attenborough", [["The_Flight_of_the_Phoenix_(1965_film)", -1]]]
["Hardy_Kr%C3%BCger", [["The_Flight_of_the_Phoenix_(1965_film)", -1]]]
["Peter_Finch", [["The_Flight_of_the_Phoenix_(1965_film)", 3.0]]]
["Ernest_Borgnine", [["The_Flight_of_the_Phoenix_(1965_film)", -1], ["The_Dirty_Dozen", -1]]]
["Ian_Bannen", [["The_Flight_of_the_Phoenix_(1965_film)", -1]]]
["Marie-Christine_Barrault", [["Cousin_Cousine", -1]]]
["Victor_Lanoux", [["Cousin_Cousine", 87000000.0]]]
["Marie-France_Pisier", [["Cousin_Cousine", 87000000.0]]]
["Brad_Pitt", [["Babel_(film)", -1], ["12_Years_a_Slave_(film)", -1]]]
["Gael_Garc%C3%ADa_Bernal", [["Babel_(film)", -1]]]
["K%C5%8Dji_Yakusho", [["Babel_(film)", 1353000000.0]]]
["Adriana_Barraza", [["Babel_(film)", -1]]]
["Rinko_Kikuchi", [["Babel_(film)", -1]]]
["Richard_Barthelmess", [["The_Patent_Leather_Kid", 12000000.0]]]
["Cary_Grant", [["None_but_the_Lonely_Heart_(film)", -1], ["The_Awful_Truth", -1], ["Suspicion_(1941_film)", -1]]]
["Ethel_Barrymore", [["None_but_the_Lonely_Heart_(film)", 42000000.0], ["Pinky_(film)", 42000000.0]]]
["Barry_Fitzgerald", [["None_but_the_Lonely_Heart_(film)", 0]]]
["June_Duprez", [["None_but_the_Lonely_Heart_(film)", 0]]]
["Jane_Wyatt", [["None_but_the_Lonely_Heart_(film)", -1]]]
["George_Coulouris", [["None_but_the_Lonely_Heart_(film)", 0]]]
["Dan_Duryea", [["None_but_the_Lonely_Heart_(film)", -1]]]
["Tommy_Lee_Jones", [["No_Country_for_Old_Men_(film)", -1]]]
["Javier_Bardem", [["No_Country_for_Old_Men_(film)", -1], ["Vicky_Cristina_Barcelona", -1]]]
["Josh_Brolin", [["No_Country_for_Old_Men_(film)", -1], ["Milk_(film)", -1], ["American_Gangster_(film)", -1]]]
["Norma_Shearer", [["A_Free_Soul", 0]]]
["Shirley_MacLaine", [["The_Turning_Point_(1977_film)", -1]]]
["Tom_Skerritt", [["The_Turning_Point_(1977_film)", -1]]]
["Mikhail_Baryshnikov", [["The_Turning_Point_(1977_film)", -1]]]
["Leslie_Browne", [["The_Turning_Point_(1977_film)", 336000000.0]]]
["Angela_Bassett", [["What%27s_Love_Got_to_Do_with_It_(film)", -1]]]
["Laurence_Fishburne", [["What%27s_Love_Got_to_Do_with_It_(film)", -1]]]
["Alan_Bates", [["The_Fixer_(1968_film)", -1], ["An_Unmarried_Woman", -1], ["The_Rose_(film)", -1]]]
["Dirk_Bogarde", [["The_Fixer_(1968_film)", 0], ["Darling_(1965_film)", 0]]]
["Georgia_Brown_(English_singer)", [["The_Fixer_(1968_film)", -1]]]
["Laraine_Day", [["Foreign_Correspondent_(film)", -1]]]
["Herbert_Marshall", [["Foreign_Correspondent_(film)", 5.0], ["The_Razor%27s_Edge_(1946_film)", 5.0], ["The_Little_Foxes_(film)", 5.0]]]
["George_Sanders", [["Foreign_Correspondent_(film)", -1]]]
["Albert_Basserman", [["Foreign_Correspondent_(film)", 0]]]
["Kevin_Spacey", [["L.A._Confidential_(film)", -1], ["American_Beauty_(1999_film)", -1]]]
["Russell_Crowe", [["L.A._Confidential_(film)", -1], ["A_Beautiful_Mind_(film)", -1], ["Gladiator_(2000_film)", -1], ["American_Gangster_(film)", -1]]]
["James_Cromwell", [["L.A._Confidential_(film)", -1], ["Babe_(film)", -1], ["The_Green_Mile_(film)", -1]]]
["David_Strathairn", [["L.A._Confidential_(film)", -1]]]
["Kim_Basinger", [["L.A._Confidential_(film)", -1]]]
["Danny_DeVito", [["L.A._Confidential_(film)", -1]]]
["James_Caan", [["Misery_(film)", -1], ["The_Godfather", -1]]]
["Kathy_Bates", [["Misery_(film)", -1], ["The_Blind_Side_(film)", -1]]]
["Frances_Sternhagen", [["Misery_(film)", -1], ["Starting_Over_(1979_film)", -1]]]
["Richard_Farnsworth", [["Misery_(film)", -1], ["The_Straight_Story", -1]]]
["Tyrone_Power", [["The_Razor%27s_Edge_(1946_film)", 25000005.0], ["In_Old_Chicago", 25000005.0]]]
["Gene_Tierney", [["The_Razor%27s_Edge_(1946_film)", -1]]]
["John_Payne_(actor)", [["The_Razor%27s_Edge_(1946_film)", -1]]]
["Anne_Baxter", [["The_Razor%27s_Edge_(1946_film)", -1]]]
["Clifton_Webb", [["The_Razor%27s_Edge_(1946_film)", 5.0]]]
["Warner_Baxter", [["In_Old_Arizona", 13000000.0]]]
["Edmund_Lowe", [["In_Old_Arizona", 13000000.0]]]
["Dorothy_Burgess", [["In_Old_Arizona", 13000000.0]]]
["Wallace_Beery", [["The_Champ_(1931_film)", 16000002.0], ["Min_and_Bill", 16000002.0]]]
["Jackie_Cooper", [["The_Champ_(1931_film)", -1], ["Skippy_(film)", -1]]]
["Irene_Rich", [["The_Champ_(1931_film)", 16000000.0]]]
["Roscoe_Ates", [["The_Champ_(1931_film)", -1]]]
["Michael_J._Pollard", [["Bonnie_and_Clyde_(film)", -1]]]
["Gene_Hackman", [["Bonnie_and_Clyde_(film)", 2292000000.0], ["Unforgiven", 2292000000.0]]]
["Estelle_Parsons", [["Bonnie_and_Clyde_(film)", -1]]]
["Irene_Dunne", [["The_Awful_Truth", -1], ["Cimarron_(1931_film)", -1]]]
["Ralph_Bellamy", [["The_Awful_Truth", -1]]]
["Alexander_D%27Arcy", [["The_Awful_Truth", -1]]]
["Brian_Donlevy", [["Wake_Island_(film)", -1], ["Beau_Geste_(1939_film)", -1]]]
["Robert_Preston_(actor)", [["Wake_Island_(film)", 35000000.0], ["Beau_Geste_(1939_film)", 35000000.0]]]
["William_Bendix", [["Wake_Island_(film)", -1]]]
["Burt_Reynolds", [["Starting_Over_(1979_film)", -1], ["The_Best_Little_Whorehouse_in_Texas_(film)", -1]]]
["Jill_Clayburgh", [["Starting_Over_(1979_film)", -1], ["An_Unmarried_Woman", -1]]]
["Candice_Bergen", [["Starting_Over_(1979_film)", -1]]]
["Charles_Durning", [["Starting_Over_(1979_film)", -1], ["The_Best_Little_Whorehouse_in_Texas_(film)", -1]]]
["Austin_Pendleton", [["Starting_Over_(1979_film)", -1]]]
["Mary_Kay_Place", [["Starting_Over_(1979_film)", -1]]]
["Nicoletta_Braschi", [["Life_Is_Beautiful", 2292000000.0]]]
["Charles_Boyer", [["Gaslight_(1944_film)", -1], ["Conquest_(1937_film)", -1]]]
["Ingrid_Bergman", [["Gaslight_(1944_film)", 6387000.0], ["Spellbound_(1945_film)", 6387000.0]]]
["Joseph_Cotten", [["Gaslight_(1944_film)", -1]]]
["May_Whitty", [["Gaslight_(1944_film)", 0]]]
["Angela_Lansbury", [["Gaslight_(1944_film)", -1]]]
["Tom_Berenger", [["Platoon_(film)", -1]]]
["Willem_Dafoe", [["Platoon_(film)", 5384000000.0], ["The_English_Patient_(film)", 5384000000.0], ["Affliction_(1997_film)", 5384000000.0], ["Born_on_the_Fourth_of_July_(film)", 5384000000.0], ["At_Eternity%27s_Gate_(film)", 5384000000.0]]]
["Charlie_Sheen", [["Platoon_(film)", -1], ["Wall_Street_(1987_film)", -1]]]
["Elisabeth_Bergner", [["Escape_Me_Never_(1935_film)", 0]]]
["Hugh_Sinclair_(actor)", [["Escape_Me_Never_(1935_film)", -1]]]
["Griffith_Jones_(actor)", [["Escape_Me_Never_(1935_film)", -1]]]
["Penelope_Dudley-Ward", [["Escape_Me_Never_(1935_film)", 0]]]
["Charles_Grodin", [["The_Heartbreak_Kid_(1972_film)", -1]]]
["Cybill_Shepherd", [["The_Heartbreak_Kid_(1972_film)", -1]]]
["Jeannie_Berlin", [["The_Heartbreak_Kid_(1972_film)", -1]]]
["Eddie_Albert", [["The_Heartbreak_Kid_(1972_film)", -1], ["Captain_Newman,_M.D.", -1]]]
["Audra_Lindley", [["The_Heartbreak_Kid_(1972_film)", -1]]]
["Annette_Bening", [["American_Beauty_(1999_film)", -1]]]
["Thora_Birch", [["American_Beauty_(1999_film)", -1]]]
["Allison_Janney", [["American_Beauty_(1999_film)", -1]]]
["Peter_Gallagher", [["American_Beauty_(1999_film)", -1]]]
["Mena_Suvari", [["American_Beauty_(1999_film)", -1]]]
["Wes_Bentley", [["American_Beauty_(1999_film)", 3563000000.0]]]
["Chris_Cooper", [["American_Beauty_(1999_film)", 4831000000.0], ["Syriana", 4831000000.0], ["Adaptation_(film)", 4831000000.0]]]
["Billy_Bob_Thornton", [["Monster%27s_Ball", -1]]]
["Halle_Berry", [["Monster%27s_Ball", -1]]]
["Heath_Ledger", [["Monster%27s_Ball", -1]]]
["Peter_Boyle", [["Monster%27s_Ball", -1]]]
["Sean_Combs", [["Monster%27s_Ball", -1]]]
["Mos_Def", [["Monster%27s_Ball", -1]]]
["Demi%C3%A1n_Bichir", [["A_Better_Life", 0]]]
["William_Eythe", [["The_Song_of_Bernadette_(film)", -1]]]
["Vincent_Price", [["The_Song_of_Bernadette_(film)", -1]]]
["Lee_J._Cobb", [["The_Song_of_Bernadette_(film)", 96000005.0], ["On_the_Waterfront", 96000005.0]]]
["Gladys_Cooper", [["The_Song_of_Bernadette_(film)", -1], ["Now,_Voyager", -1]]]
["Sidney_Poitier", [["The_Defiant_Ones_(film)", -1]]]
["Tony_Curtis", [["The_Defiant_Ones_(film)", -1], ["Captain_Newman,_M.D.", -1]]]
["Ralph_Fiennes", [["The_English_Patient_(film)", -1]]]
["Juliette_Binoche", [["The_English_Patient_(film)", 2320000000.0]]]
["Kristin_Scott_Thomas", [["The_English_Patient_(film)", -1]]]
["Naveen_Andrews", [["The_English_Patient_(film)", -1]]]
["Julian_Wadham", [["The_English_Patient_(film)", -1]]]
["J%C3%BCrgen_Prochnow", [["The_English_Patient_(film)", -1]]]
["Karen_Black", [["Five_Easy_Pieces", -1]]]
["Susan_Anspach", [["Five_Easy_Pieces", -1]]]
["Ned_Beatty", [["Nashville_(film)", -1]]]
["Ronee_Blakley", [["Nashville_(film)", 100000000.0]]]
["Keith_Carradine", [["Nashville_(film)", -1]]]
["Geraldine_Chaplin", [["Nashville_(film)", -1]]]
["Henry_Gibson", [["Nashville_(film)", -1]]]
["Michael_Murphy_(actor)", [["Nashville_(film)", -1], ["An_Unmarried_Woman", -1]]]
["Lily_Tomlin", [["Nashville_(film)", -1]]]
["Louis_C.K.", [["Blue_Jasmine", -1], ["Trumbo_(2015_film)", -1]]]
["Bobby_Cannavale", [["Blue_Jasmine", -1]]]
["Andrew_Dice_Clay", [["Blue_Jasmine", -1], ["A_Star_Is_Born_(2018_film)", -1]]]
["Sally_Hawkins", [["Blue_Jasmine", -1]]]
["Peter_Sarsgaard", [["Blue_Jasmine", 975000000.0]]]
["Michael_Stuhlbarg", [["Blue_Jasmine", -1], ["Call_Me_by_Your_Name_(film)", -1], ["Trumbo_(2015_film)", -1]]]
["Brenda_Blethyn", [["Secrets_%26_Lies_(film)", -1]]]
["Phyllis_Logan", [["Secrets_%26_Lies_(film)", -1]]]
["Marianne_Jean-Baptiste", [["Secrets_%26_Lies_(film)", -1]]]
["Claire_Rushbrook", [["Secrets_%26_Lies_(film)", -1]]]
["Ron_Cook", [["Secrets_%26_Lies_(film)", -1]]]
["Lesley_Manville", [["Secrets_%26_Lies_(film)", -1]]]
["Elizabeth_Berrington", [["Secrets_%26_Lies_(film)", -1]]]
["Michele_Austin", [["Secrets_%26_Lies_(film)", -1]]]
["Lee_Ross_(actor)", [["Secrets_%26_Lies_(film)", -1]]]
["Emma_Amos_(actress)", [["Secrets_%26_Lies_(film)", -1]]]
["Charles_Laughton", [["The_Blue_Veil_(1951_film)", 0]]]
["Joan_Blondell", [["The_Blue_Veil_(1951_film)", 3.0], ["A_Tree_Grows_in_Brooklyn_(1945_film)", 3.0]]]
["Carey_Mulligan", [["Mudbound_(film)", -1]]]
["Jason_Clarke", [["Mudbound_(film)", -1], ["Zero_Dark_Thirty", -1]]]
["Jason_Mitchell_(actor)", [["Mudbound_(film)", 0]]]
["Mary_J._Blige", [["Mudbound_(film)", -1]]]
["Rob_Morgan_(actor)", [["Mudbound_(film)", -1]]]
["Jonathan_Banks", [["Mudbound_(film)", -1]]]
["Garrett_Hedlund", [["Mudbound_(film)", 0]]]
["Robert_Taylor_(actor)", [["The_Gorgeous_Hussy", -1]]]
["Lionel_Barrymore", [["The_Gorgeous_Hussy", 2137575.0], ["You_Can%27t_Take_It_with_You_(film)", 2137575.0]]]
["Franchot_Tone", [["The_Gorgeous_Hussy", -1], ["Dangerous_(film)", -1]]]
["Humphrey_Bogart", [["The_African_Queen_(film)", 0]]]
["Katharine_Hepburn", [["The_African_Queen_(film)", -1], ["On_Golden_Pond_(1981_film)", -1]]]
["Robert_Morley", [["The_African_Queen_(film)", 0]]]
["Linus_Roache", [["The_Wings_of_the_Dove_(1997_film)", -1]]]
["Alison_Elliott", [["The_Wings_of_the_Dove_(1997_film)", -1]]]
["Elizabeth_McGovern", [["The_Wings_of_the_Dove_(1997_film)", -1]]]
["Alex_Jennings", [["The_Wings_of_the_Dove_(1997_film)", -1]]]
["Charlotte_Rampling", [["The_Wings_of_the_Dove_(1997_film)", -1]]]
["Burt_Lancaster", [["Come_Back,_Little_Sheba_(1952_film)", 35000000.0]]]
["Shirley_Booth", [["Come_Back,_Little_Sheba_(1952_film)", -1]]]
["Terry_Moore_(actress)", [["Come_Back,_Little_Sheba_(1952_film)", -1]]]
["Greta_Garbo", [["Conquest_(1937_film)", 2141000.0]]]
["Alan_Marshal_(actor)", [["Conquest_(1937_film)", 2141000.0]]]
["Alice_Faye", [["In_Old_Chicago", 25000000.0]]]
["Paul_Scofield", [["Henry_V_(1989_film)", -1]]]
["Emma_Thompson", [["Henry_V_(1989_film)", -1]]]
["Alec_McCowen", [["Henry_V_(1989_film)", -1]]]
["Judi_Dench", [["Henry_V_(1989_film)", -1], ["Iris_(2001_film)", -1], ["A_Room_with_a_View_(1985_film)", -1]]]
["Robert_De_Niro", [["Goodfellas", 3813000000.0], ["Silver_Linings_Playbook", 3813000000.0], ["Raging_Bull", 3813000000.0], ["Jackie_Brown", 3813000000.0]]]
["Ray_Liotta", [["Goodfellas", -1]]]
["Joe_Pesci", [["Goodfellas", 468000000.0]]]
["Lorraine_Bracco", [["Goodfellas", -1]]]
["Paul_Sorvino", [["Goodfellas", -1]]]
["Robert_Redford", [["Out_of_Africa_(film)", 2275000000.0]]]
["Meryl_Streep", [["Out_of_Africa_(film)", -1], ["Adaptation_(film)", -1]]]
["Klaus_Maria_Brandauer", [["Out_of_Africa_(film)", 2275000000.0]]]
["Edward_Arnold_(actor)", [["Come_and_Get_It_(1936_film)", 2137575.0], ["You_Can%27t_Take_It_with_You_(film)", 2137575.0]]]
["Frances_Farmer", [["Come_and_Get_It_(1936_film)", -1]]]
["Walter_Brennan", [["Come_and_Get_It_(1936_film)", -1], ["Sergeant_York_(film)", -1]]]
["Marlon_Brando", [["On_the_Waterfront", -1], ["Sayonara", -1], ["The_Godfather", -1]]]
["Rod_Steiger", [["On_the_Waterfront", -1]]]
["Pat_Henning", [["On_the_Waterfront", -1]]]
["Eva_Marie_Saint", [["On_the_Waterfront", -1], ["A_Hatful_of_Rain", -1]]]
["Kate_Winslet", [["Iris_(2001_film)", -1], ["Steve_Jobs_(film)", -1]]]
["Jim_Broadbent", [["Iris_(2001_film)", -1]]]
["Hugh_Bonneville", [["Iris_(2001_film)", -1]]]
["Maggie_Gyllenhaal", [["Crazy_Heart", -1], ["Adaptation_(film)", -1]]]
["Colin_Farrell", [["Crazy_Heart", -1]]]
["Adrien_Brody", [["The_Pianist_(2002_film)", 1201000000.0]]]
["Thomas_Kretschmann", [["The_Pianist_(2002_film)", -1]]]
["Frank_Finlay", [["The_Pianist_(2002_film)", -1], ["Othello_(1965_British_film)", -1]]]
["Maureen_Lipman", [["The_Pianist_(2002_film)", -1]]]
["Emilia_Fox", [["The_Pianist_(2002_film)", -1]]]
["Micha%C5%82_%C5%BBebrowski", [["The_Pianist_(2002_film)", 1201000000.0]]]
["Sean_Penn", [["Milk_(film)", -1]]]
["Emile_Hirsch", [["Milk_(film)", -1]]]
["Diego_Luna", [["Milk_(film)", -1]]]
["Alison_Pill", [["Milk_(film)", -1], ["Pieces_of_April", -1]]]
["Victor_Garber", [["Milk_(film)", -1]]]
["Denis_O%27Hare", [["Milk_(film)", -1]]]
["Joseph_Cross_(actor)", [["Milk_(film)", -1]]]
["James_Franco", [["Milk_(film)", -1], ["127_Hours", -1]]]
["Richard_Burton", [["Anne_of_the_Thousand_Days", 766134264.0], ["The_Robe_(film)", 766134264.0], ["Who%27s_Afraid_of_Virginia_Woolf%3F_(film)", 766134264.0], ["Equus_(film)", 766134264.0]]]
["Genevi%C3%A8ve_Bujold", [["Anne_of_the_Thousand_Days", -1]]]
["Anthony_Quayle", [["Anne_of_the_Thousand_Days", -1]]]
["John_Colicos", [["Anne_of_the_Thousand_Days", -1]]]
["Irene_Papas", [["Anne_of_the_Thousand_Days", 6134264.0]]]
["Sandra_Bullock", [["The_Blind_Side_(film)", -1]]]
["Tim_McGraw", [["The_Blind_Side_(film)", 3092000000.0]]]
["Quinton_Aaron", [["The_Blind_Side_(film)", -1]]]
["Jae_Head", [["The_Blind_Side_(film)", 3092000000.0]]]
["Lily_Collins", [["The_Blind_Side_(film)", -1]]]
["Ray_McKinnon_(actor)", [["The_Blind_Side_(film)", -1]]]
["Constance_Bennett", [["Merrily_We_Live", 0]]]
["Catherine_Burns", [["Last_Summer", -1]]]
["Bruce_Davison", [["Last_Summer", -1], ["Six_Degrees_of_Separation_(film)", -1], ["Longtime_Companion", -1]]]
["Richard_Thomas_(actor)", [["Last_Summer", -1]]]
["Walter_Matthau", [["The_Sunshine_Boys_(1975_film)", -1]]]
["George_Burns", [["The_Sunshine_Boys_(1975_film)", -1]]]
["Richard_Benjamin", [["The_Sunshine_Boys_(1975_film)", -1]]]
["Lee_Meredith", [["The_Sunshine_Boys_(1975_film)", -1]]]
["Gary_Busey", [["The_Buddy_Holly_Story", -1]]]
["Don_Stroud", [["The_Buddy_Holly_Story", -1]]]
["Charles_Martin_Smith", [["The_Buddy_Holly_Story", -1], ["American_Graffiti", -1]]]
["Conrad_Janis", [["The_Buddy_Holly_Story", -1]]]
["Paul_Mooney_(comedian)", [["The_Buddy_Holly_Story", -1]]]
["Jean_Simmons", [["The_Robe_(film)", -1]]]
["Victor_Mature", [["The_Robe_(film)", -1]]]
["Michael_Rennie", [["The_Robe_(film)", -1]]]
["Patricia_Owens", [["Sayonara", -1]]]
["James_Garner", [["Sayonara", -1]]]
["Martha_Scott", [["Sayonara", -1]]]
["Miiko_Taka", [["Sayonara", -1]]]
["Miyoshi_Umeki", [["Sayonara", -1]]]
["Red_Buttons", [["Sayonara", -1]]]
["Ricardo_Montalb%C3%A1n", [["Sayonara", -1]]]
["Howard_Rollins", [["A_Soldier%27s_Story", -1]]]
["Nicolas_Cage", [["Leaving_Las_Vegas", 1632000000.0], ["Moonstruck", 1632000000.0], ["Adaptation_(film)", 1632000000.0]]]
["Elisabeth_Shue", [["Leaving_Las_Vegas", -1]]]
["Julian_Sands", [["Leaving_Las_Vegas", -1], ["A_Room_with_a_View_(1985_film)", -1]]]
["Michael_Caine", [["Hannah_and_Her_Sisters", -1]]]
["Mia_Farrow", [["Hannah_and_Her_Sisters", -1]]]
["Carrie_Fisher", [["Hannah_and_Her_Sisters", -1]]]
["Lloyd_Nolan", [["Hannah_and_Her_Sisters", -1], ["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["Maureen_O%27Sullivan", [["Hannah_and_Her_Sisters", -1]]]
["Daniel_Stern_(actor)", [["Hannah_and_Her_Sisters", -1]]]
["Max_von_Sydow", [["Hannah_and_Her_Sisters", -1]]]
["Dianne_Wiest", [["Hannah_and_Her_Sisters", -1]]]
["Louis_Calhern", [["The_Magnificent_Yankee_(1950_film)", 0]]]
["Ann_Harding", [["The_Magnificent_Yankee_(1950_film)", -1]]]
["Eduard_Franz", [["The_Magnificent_Yankee_(1950_film)", -1]]]
["Philip_Ober", [["The_Magnificent_Yankee_(1950_film)", -1]]]
["James_Cagney", [["Yankee_Doodle_Dandy", -1]]]
["Joan_Leslie", [["Yankee_Doodle_Dandy", -1], ["Sergeant_York_(film)", -1]]]
["Walter_Huston", [["Yankee_Doodle_Dandy", 0]]]
["Richard_Whorf", [["Yankee_Doodle_Dandy", -1]]]
["Al_Pacino", [["The_Godfather", 0]]]
["Richard_Castellano", [["The_Godfather", -1]]]
["Robert_Duvall", [["The_Godfather", -1], ["Captain_Newman,_M.D.", -1], ["Rambling_Rose_(film)", -1], ["Tender_Mercies", -1]]]
["Sterling_Hayden", [["The_Godfather", -1]]]
["John_Marley", [["The_Godfather", -1], ["Faces_(film)", -1]]]
["Richard_Conte", [["The_Godfather", -1]]]
["Gena_Rowlands", [["Faces_(film)", -1]]]
["Lynn_Carlin", [["Faces_(film)", -1]]]
["Seymour_Cassel", [["Faces_(film)", -1]]]
["Fred_Draper", [["Faces_(film)", -1]]]
["Val_Avery", [["Faces_(film)", -1]]]
["Dorothy_Gulliver", [["Faces_(film)", 0]]]
["Channing_Tatum", [["Foxcatcher", -1]]]
["Mark_Ruffalo", [["Foxcatcher", -1]]]
["Vanessa_Redgrave", [["Foxcatcher", -1]]]
["Art_Carney", [["Harry_and_Tonto", -1]]]
["Herbert_Berghof", [["Harry_and_Tonto", 46000000.0]]]
["Philip_Bruns", [["Harry_and_Tonto", -1]]]
["Ellen_Burstyn", [["Harry_and_Tonto", -1]]]
["Geraldine_Fitzgerald", [["Harry_and_Tonto", -1], ["Wuthering_Heights_(1939_film)", -1]]]
["Larry_Hagman", [["Harry_and_Tonto", -1]]]
["Chief_Dan_George", [["Harry_and_Tonto", -1]]]
["Melanie_Mayron", [["Harry_and_Tonto", -1]]]
["Josh_Mostel", [["Harry_and_Tonto", 46000000.0]]]
["Arthur_Hunnicutt", [["Harry_and_Tonto", 46000000.0]]]
["Barbara_Rhoades", [["Harry_and_Tonto", -1]]]
["Cliff_DeYoung", [["Harry_and_Tonto", -1]]]
["Avon_Long", [["Harry_and_Tonto", -1]]]
["Leslie_Caron", [["Lili", -1]]]
["Mel_Ferrer", [["Lili", 0]]]
["Jean-Pierre_Aumont", [["Lili", 0], ["Day_for_Night_(film)", 0]]]
["Zsa_Zsa_Gabor", [["Lili", -1]]]
["Diahann_Carroll", [["Claudine_(film)", -1]]]
["Lawrence_Hilton-Jacobs", [["Claudine_(film)", -1]]]
["Adam_Wade_(singer)", [["Claudine_(film)", -1]]]
["Roxie_Roker", [["Claudine_(film)", -1]]]
["Rosalind_Russell", [["Auntie_Mame_(film)", 93000000.0]]]
["Forrest_Tucker", [["Auntie_Mame_(film)", -1]]]
["Coral_Browne", [["Auntie_Mame_(film)", -1]]]
["Roger_Smith_(actor)", [["Auntie_Mame_(film)", -1]]]
["Peggy_Cass", [["Auntie_Mame_(film)", -1]]]
["Joanna_Barnes", [["Auntie_Mame_(film)", -1]]]
["Robin_Hughes", [["Auntie_Mame_(film)", -1]]]
["Pippa_Scott", [["Auntie_Mame_(film)", -1]]]
["Nancy_Carroll", [["The_Devil%27s_Holiday", -1]]]
["Lee_Marvin", [["The_Dirty_Dozen", -1], ["Ship_of_Fools_(film)", -1]]]
["Charles_Bronson", [["The_Dirty_Dozen", -1]]]
["Jim_Brown", [["The_Dirty_Dozen", -1]]]
["John_Cassavetes", [["The_Dirty_Dozen", 453000000.0]]]
["Richard_Jaeckel", [["The_Dirty_Dozen", -1]]]
["George_Kennedy", [["The_Dirty_Dozen", -1]]]
["Trini_Lopez", [["The_Dirty_Dozen", -1]]]
["Ralph_Meeker", [["The_Dirty_Dozen", -1]]]
["Robert_Ryan", [["The_Dirty_Dozen", -1]]]
["Telly_Savalas", [["The_Dirty_Dozen", -1]]]
["Clint_Walker", [["The_Dirty_Dozen", -1]]]
["Robert_Webber", [["The_Dirty_Dozen", -1]]]
["Beatrice_Arthur", [["Lovers_and_Other_Strangers", -1]]]
["Richard_S._Castellano", [["Lovers_and_Other_Strangers", -1]]]
["Bonnie_Bedelia", [["Lovers_and_Other_Strangers", -1]]]
["Gig_Young", [["Lovers_and_Other_Strangers", -1]]]
["Keisha_Castle-Hughes", [["Whale_Rider", -1]]]
["Rawiri_Paratene", [["Whale_Rider", -1]]]
["Cliff_Curtis", [["Whale_Rider", -1]]]
["Jeff_Chandler", [["Broken_Arrow_(1950_film)", 3550000.0]]]
["Debra_Paget", [["Broken_Arrow_(1950_film)", -1]]]
["Natalie_Wood", [["West_Side_Story_(film)", -1]]]
["Richard_Beymer", [["West_Side_Story_(film)", -1]]]
["Rita_Moreno", [["West_Side_Story_(film)", -1]]]
["George_Chakiris", [["West_Side_Story_(film)", -1]]]
["Russ_Tamblyn", [["West_Side_Story_(film)", -1]]]
["Mary_Tyler_Moore", [["Thoroughly_Modern_Millie", -1]]]
["Carol_Channing", [["Thoroughly_Modern_Millie", -1]]]
["John_Gavin", [["Thoroughly_Modern_Millie", -1]]]
["Beatrice_Lillie", [["Thoroughly_Modern_Millie", 400000000.0]]]
["Stockard_Channing", [["Six_Degrees_of_Separation_(film)", -1]]]
["Will_Smith", [["Six_Degrees_of_Separation_(film)", -1]]]
["Donald_Sutherland", [["Six_Degrees_of_Separation_(film)", -1], ["Klute", -1]]]
["Mary_Beth_Hurt", [["Six_Degrees_of_Separation_(film)", -1], ["Affliction_(1997_film)", -1]]]
["Ian_McKellen", [["Six_Degrees_of_Separation_(film)", -1]]]
["Paulette_Goddard", [["The_Great_Dictator", -1]]]
["Jack_Oakie", [["The_Great_Dictator", 5.0]]]
["Henry_Daniell", [["The_Great_Dictator", -1]]]
["Reginald_Gardiner", [["The_Great_Dictator", -1]]]
["Billy_Gilbert", [["The_Great_Dictator", 5.0]]]
["Maurice_Moscovich", [["The_Great_Dictator", 5.0]]]
["Ruth_Chatterton", [["Madame_X_(1929_film)", -1]]]
["Lewis_Stone", [["Madame_X_(1929_film)", 0]]]
["Jessica_Chastain", [["Zero_Dark_Thirty", -1]]]
["Joel_Edgerton", [["Zero_Dark_Thirty", -1]]]
["Mark_Strong", [["Zero_Dark_Thirty", -1], ["The_Imitation_Game", -1]]]
["Chris_Pratt", [["Zero_Dark_Thirty", -1]]]
["James_Gandolfini", [["Zero_Dark_Thirty", -1]]]
["Armie_Hammer", [["Call_Me_by_Your_Name_(film)", -1], ["The_Social_Network", -1]]]
["Timoth%C3%A9e_Chalamet", [["Call_Me_by_Your_Name_(film)", -1]]]
["Amira_Casar", [["Call_Me_by_Your_Name_(film)", 419000000.0]]]
["Esther_Garrel", [["Call_Me_by_Your_Name_(film)", 419000000.0]]]
["Victoire_Du_Bois", [["Call_Me_by_Your_Name_(film)", -1]]]
["Cher", [["Moonstruck", -1]]]
["Vincent_Gardenia", [["Moonstruck", -1]]]
["Olympia_Dukakis", [["Moonstruck", -1]]]
["Don_Cheadle", [["Hotel_Rwanda", -1]]]
["Sophie_Okonedo", [["Hotel_Rwanda", -1]]]
["Joaquin_Phoenix", [["Hotel_Rwanda", -1], ["Gladiator_(2000_film)", -1]]]
["Nick_Nolte", [["Hotel_Rwanda", -1], ["Affliction_(1997_film)", -1]]]
["Maurice_Chevalier", [["The_Love_Parade", 0]]]
["Jeanette_MacDonald", [["The_Love_Parade", 0]]]
["Lillian_Roth", [["The_Love_Parade", 0]]]
["Michael_Chekhov", [["Spellbound_(1945_film)", 6387000.0]]]
["Julie_Christie", [["Darling_(1965_film)", -1]]]
["Cliff_Gorman", [["An_Unmarried_Woman", -1]]]
["Albert_Finney", [["Tom_Jones_(1963_film)", -1]]]
["Susannah_York", [["Tom_Jones_(1963_film)", -1]]]
["Hugh_Griffith", [["Tom_Jones_(1963_film)", -1]]]
["Edith_Evans", [["Tom_Jones_(1963_film)", 37600000.0], ["The_Whisperers", 37600000.0]]]
["Joan_Greenwood", [["Tom_Jones_(1963_film)", -1]]]
["Diane_Cilento", [["Tom_Jones_(1963_film)", 37600000.0]]]
["George_Devine", [["Tom_Jones_(1963_film)", 37600000.0]]]
["Katie_Holmes", [["Pieces_of_April", -1]]]
["Derek_Luke_(actor)", [["Pieces_of_April", -1]]]
["Sean_Hayes_(actor)", [["Pieces_of_April", -1]]]
["Oliver_Platt", [["Pieces_of_April", -1]]]
["Patricia_Clarkson", [["Pieces_of_April", -1], ["Vicky_Cristina_Barcelona", -1], ["The_Green_Mile_(film)", -1]]]
["Richard_Dreyfuss", [["American_Graffiti", -1], ["Close_Encounters_of_the_Third_Kind", -1]]]
["Ron_Howard", [["American_Graffiti", -1]]]
["Paul_Le_Mat", [["American_Graffiti", -1]]]
["Candy_Clark", [["American_Graffiti", -1]]]
["Mackenzie_Phillips", [["American_Graffiti", -1]]]
["Cindy_Williams", [["American_Graffiti", -1]]]
["Wolfman_Jack", [["American_Graffiti", -1]]]
["Aline_MacMahon", [["The_Search", 0]]]
["Jarmila_Novotn%C3%A1", [["The_Search", -1]]]
["Wendell_Corey", [["The_Search", -1]]]
["Ivan_Jandl", [["The_Search", 0]]]
["George_Clooney", [["Syriana", -1], ["Up_in_the_Air_(2009_film)", -1]]]
["Matt_Damon", [["Syriana", 940000000.0]]]
["Jeffrey_Wright_(actor)", [["Syriana", -1]]]
["William_Hurt", [["Syriana", 972632093.0], ["The_Accidental_Tourist_(film)", 972632093.0]]]
["Mazhar_Munir", [["Syriana", -1]]]
["Tim_Blake_Nelson", [["Syriana", -1]]]
["Amanda_Peet", [["Syriana", -1]]]
["Christopher_Plummer", [["Syriana", -1], ["A_Beautiful_Mind_(film)", -1]]]
["Alexander_Siddig", [["Syriana", 940000000.0]]]
["Sissy_Spacek", [["Affliction_(1997_film)", 62000000.0], ["The_Straight_Story", 62000000.0]]]
["James_Coburn", [["Affliction_(1997_film)", -1]]]
["Jim_True-Frost", [["Affliction_(1997_film)", -1]]]
["Clark_Gable", [["It_Happened_One_Night", 0]]]
["Claudette_Colbert", [["It_Happened_One_Night", -1]]]
["Bruce_Willis", [["The_Sixth_Sense", -1]]]
["Olivia_Williams", [["The_Sixth_Sense", -1]]]
["Haley_Joel_Osment", [["The_Sixth_Sense", -1]]]
["Pauline_Collins", [["Shirley_Valentine_(film)", -1]]]
["Tom_Conti", [["Shirley_Valentine_(film)", 6353913.0], ["Reuben,_Reuben", 6353913.0]]]
["Teresa_Wright", [["The_Little_Foxes_(film)", -1]]]
["Milton_Sills", [["The_Barker", 0]]]
["Dorothy_Mackaill", [["The_Barker", -1]]]
["Betty_Compson", [["The_Barker", 0]]]
["Douglas_Fairbanks_Jr.", [["The_Barker", 0]]]
["Kelly_McGillis", [["Reuben,_Reuben", -1], ["The_Accused_(1988_film)", -1]]]
["Olivia_Colman", [["The_Favourite", -1]]]
["Emma_Stone", [["The_Favourite", -1]]]
["Rachel_Weisz", [["The_Favourite", -1]]]
["Nicholas_Hoult", [["The_Favourite", -1]]]
["Joe_Alwyn", [["The_Favourite", 826000000.0]]]
["Ed_Harris", [["A_Beautiful_Mind_(film)", -1], ["Places_in_the_Heart", -1]]]
["Paul_Bettany", [["A_Beautiful_Mind_(film)", 3130000000.0]]]
["Adam_Goldberg", [["A_Beautiful_Mind_(film)", -1]]]
["Judd_Hirsch", [["A_Beautiful_Mind_(film)", -1]]]
["Josh_Lucas", [["A_Beautiful_Mind_(film)", -1]]]
["Anthony_Rapp", [["A_Beautiful_Mind_(film)", -1]]]
["Gary_Cooper", [["Sergeant_York_(film)", -1], ["Morocco_(film)", -1], ["Beau_Geste_(1939_film)", -1]]]
["Brian_Cox_(actor)", [["Adaptation_(film)", -1]]]
["Tilda_Swinton", [["Adaptation_(film)", -1]]]
["Paul_Henreid", [["Now,_Voyager", 22000000.0]]]
["Claude_Rains", [["Now,_Voyager", -1]]]
["Jacki_Weaver", [["Silver_Linings_Playbook", -1]]]
["Anupam_Kher", [["Silver_Linings_Playbook", 2364000000.0]]]
["Chris_Tucker", [["Silver_Linings_Playbook", -1]]]
["Robert_Coogan", [["Skippy_(film)", -1]]]
["Mitzi_Green", [["Skippy_(film)", -1]]]
["Jackie_Searl", [["Skippy_(film)", -1]]]
["Marion_Cotillard", [["La_Vie_en_rose_(film)", -1]]]
["G%C3%A9rard_Depardieu", [["La_Vie_en_rose_(film)", 1276000000.0], ["Cyrano_de_Bergerac_(1990_film)", 1276000000.0]]]
["Sylvie_Testud", [["La_Vie_en_rose_(film)", 863000000.0]]]
["Jacqueline_Bisset", [["Day_for_Night_(film)", -1]]]
["Valentina_Cortese", [["Day_for_Night_(film)", -1]]]
["Dani_(singer)", [["Day_for_Night_(film)", -1]]]
["Alexandra_Stewart", [["Day_for_Night_(film)", -1]]]
["Jean_Champion", [["Day_for_Night_(film)", 0]]]
["Jean-Pierre_L%C3%A9aud", [["Day_for_Night_(film)", 0]]]
["Fran%C3%A7ois_Truffaut", [["Day_for_Night_(film)", 3061000000.0], ["Close_Encounters_of_the_Third_Kind", 3061000000.0]]]
["Mary_McDonnell", [["Dances_with_Wolves", -1]]]
["Graham_Greene_(actor)", [["Dances_with_Wolves", -1], ["The_Green_Mile_(film)", -1]]]
["Rodney_A._Grant", [["Dances_with_Wolves", -1]]]
["Jeanne_Crain", [["Pinky_(film)", -1]]]
["Ethel_Waters", [["Pinky_(film)", 42000000.0]]]
["Bryan_Cranston", [["Trumbo_(2015_film)", -1]]]
["Adewale_Akinnuoye-Agbaje", [["Trumbo_(2015_film)", -1]]]
["David_James_Elliott", [["Trumbo_(2015_film)", -1]]]
["Elle_Fanning", [["Trumbo_(2015_film)", -1]]]
["John_Goodman", [["Trumbo_(2015_film)", -1]]]
["Diane_Lane", [["Trumbo_(2015_film)", -1]]]
["Alan_Tudyk", [["Trumbo_(2015_film)", -1]]]
["Helen_Mirren", [["Trumbo_(2015_film)", -1]]]
["Broderick_Crawford", [["All_the_King%27s_Men_(1949_film)", -1]]]
["John_Ireland_(actor)", [["All_the_King%27s_Men_(1949_film)", -1]]]
["Mercedes_McCambridge", [["All_the_King%27s_Men_(1949_film)", -1]]]
["Joanne_Dru", [["All_the_King%27s_Men_(1949_film)", -1]]]
["John_Derek", [["All_the_King%27s_Men_(1949_film)", -1]]]
["Shepperd_Strudwick", [["All_the_King%27s_Men_(1949_film)", -1]]]
["Spencer_Tracy", [["The_Seventh_Cross_(film)", 36000000.0]]]
["Signe_Hasso", [["The_Seventh_Cross_(film)", -1]]]
["Herbert_Rudley", [["The_Seventh_Cross_(film)", -1]]]
["Felix_Bressart", [["The_Seventh_Cross_(film)", -1]]]
["Ray_Collins_(actor)", [["The_Seventh_Cross_(film)", -1]]]
["Magda_Szubanski", [["Babe_(film)", -1]]]
["Sharon_Farrell", [["The_Reivers_(film)", -1]]]
["Mitch_Vogel", [["The_Reivers_(film)", -1]]]
["Rupert_Crosse", [["The_Reivers_(film)", -1]]]
["Burgess_Meredith", [["The_Reivers_(film)", -1]]]
["Will_Geer", [["The_Reivers_(film)", -1]]]
["Sally_Field", [["Places_in_the_Heart", -1], ["Norma_Rae", -1]]]
["Lindsay_Crouse", [["Places_in_the_Heart", -1]]]
["Ray_Baker_(actor)", [["Places_in_the_Heart", -1]]]
["Amy_Madigan", [["Places_in_the_Heart", -1]]]
["John_Malkovich", [["Places_in_the_Heart", -1]]]
["Terry_O%27Quinn", [["Places_in_the_Heart", -1]]]
["Pen%C3%A9lope_Cruz", [["Vicky_Cristina_Barcelona", -1]]]
["Scarlett_Johansson", [["Vicky_Cristina_Barcelona", -1]]]
["Kevin_Dunn", [["Vicky_Cristina_Barcelona", -1]]]
["Rebecca_Hall", [["Vicky_Cristina_Barcelona", -1]]]
["Chris_Messina", [["Vicky_Cristina_Barcelona", -1]]]
["Tom_Cruise", [["Born_on_the_Fourth_of_July_(film)", 1610000000.0]]]
["Kyra_Sedgwick", [["Born_on_the_Fourth_of_July_(film)", -1]]]
["Raymond_J._Barry", [["Born_on_the_Fourth_of_July_(film)", -1]]]
["Jerry_Levine", [["Born_on_the_Fourth_of_July_(film)", -1]]]
["Frank_Whaley", [["Born_on_the_Fourth_of_July_(film)", -1]]]
["Connie_Nielsen", [["Gladiator_(2000_film)", -1]]]
["Djimon_Hounsou", [["Gladiator_(2000_film)", -1]]]
["Richard_Harris", [["Gladiator_(2000_film)", 6197000000.0], ["Unforgiven", 6197000000.0]]]
["Benedict_Cumberbatch", [["The_Imitation_Game", -1], ["12_Years_a_Slave_(film)", -1]]]
["Keira_Knightley", [["The_Imitation_Game", -1], ["Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", -1]]]
["Matthew_Goode", [["The_Imitation_Game", -1]]]
["Rory_Kinnear", [["The_Imitation_Game", -1]]]
["Charles_Dance", [["The_Imitation_Game", -1]]]
["Betty_Grable", [["When_My_Baby_Smiles_at_Me_(film)", -1], ["Pigskin_Parade", -1]]]
["Dan_Dailey", [["When_My_Baby_Smiles_at_Me_(film)", -1]]]
["Rupert_Friend", [["At_Eternity%27s_Gate_(film)", -1]]]
["Mads_Mikkelsen", [["At_Eternity%27s_Gate_(film)", -1]]]
["Mathieu_Amalric", [["At_Eternity%27s_Gate_(film)", -1]]]
["Emmanuelle_Seigner", [["At_Eternity%27s_Gate_(film)", -1]]]
["Oscar_Isaac", [["At_Eternity%27s_Gate_(film)", -1]]]
["Nigel_Bruce", [["The_Corn_Is_Green_(1945_film)", -1], ["Suspicion_(1941_film)", -1]]]
["John_Dall", [["The_Corn_Is_Green_(1945_film)", -1]]]
["Angie_Dickinson", [["Captain_Newman,_M.D.", -1]]]
["Bobby_Darin", [["Captain_Newman,_M.D.", 42500000.0]]]
["Harry_Belafonte", [["Carmen_Jones_(film)", -1]]]
["Dorothy_Dandridge", [["Carmen_Jones_(film)", -1]]]
["Pearl_Bailey", [["Carmen_Jones_(film)", -1]]]
["Robin_Williams", [["Good_Will_Hunting", -1]]]
["Stellan_Skarsg%C3%A5rd", [["Good_Will_Hunting", -1]]]
["Minnie_Driver", [["Good_Will_Hunting", -1]]]
["Stephen_Rea", [["The_Crying_Game", -1]]]
["Miranda_Richardson", [["The_Crying_Game", -1]]]
["Jaye_Davidson", [["The_Crying_Game", 625000000.0]]]
["Forest_Whitaker", [["The_Crying_Game", -1]]]
["Jane_Darwell", [["The_Grapes_of_Wrath_(film)", 25000000.0]]]
["John_Carradine", [["The_Grapes_of_Wrath_(film)", -1]]]
["Shirley_Mills", [["The_Grapes_of_Wrath_(film)", -1]]]
["John_Qualen", [["The_Grapes_of_Wrath_(film)", -1]]]
["Eddie_Quillan", [["The_Grapes_of_Wrath_(film)", -1]]]
["Kathleen_Turner", [["The_Accidental_Tourist_(film)", 32632093.0]]]
["Geena_Davis", [["The_Accidental_Tourist_(film)", -1]]]
["Viola_Davis", [["Fences_(film)", -1]]]
["Stephen_Henderson_(actor)", [["Fences_(film)", -1]]]
["Jovan_Adepo", [["Fences_(film)", -1]]]
["Russell_Hornsby", [["Fences_(film)", -1]]]
["Mykelti_Williamson", [["Fences_(film)", -1]]]
["Saniyya_Sidney", [["Fences_(film)", -1]]]
["Stephen_Caffrey_(actor)", [["Longtime_Companion", -1]]]
["Patrick_Cassidy_(actor)", [["Longtime_Companion", -1]]]
["John_Dossett", [["Longtime_Companion", -1]]]
["Mark_Lamos", [["Longtime_Companion", -1]]]
["Dermot_Mulroney", [["Longtime_Companion", -1]]]
["Mary-Louise_Parker", [["Longtime_Companion", -1]]]
["Michael_Schoeffling", [["Longtime_Companion", -1]]]
["Campbell_Scott", [["Longtime_Companion", -1]]]
["Rock_Hudson", [["Pillow_Talk_(film)", -1], ["A_Farewell_to_Arms_(1957_film)", -1]]]
["Doris_Day", [["Pillow_Talk_(film)", -1]]]
["Tony_Randall", [["Pillow_Talk_(film)", -1]]]
["Thelma_Ritter", [["Pillow_Talk_(film)", -1]]]
["Olivia_de_Havilland", [["To_Each_His_Own_(film)", -1]]]
["Mary_Anderson_(actress,_born_1918)", [["To_Each_His_Own_(film)", -1]]]
["John_Lund_(actor)", [["To_Each_His_Own_(film)", -1]]]
["Daniel_Day-Lewis", [["My_Left_Foot", -1], ["A_Room_with_a_View_(1985_film)", -1]]]
["Ray_McAnally", [["My_Left_Foot", -1]]]
["Brenda_Fricker", [["My_Left_Foot", -1]]]
["Cyril_Cusack", [["My_Left_Foot", -1]]]
["Fiona_Shaw", [["My_Left_Foot", -1]]]
["Hugh_O%27Conor", [["My_Left_Foot", -1]]]
["Adrian_Dunbar", [["My_Left_Foot", -1]]]
["Vittorio_De_Sica", [["A_Farewell_to_Arms_(1957_film)", 200000000.0]]]
["Elaine_Stritch", [["A_Farewell_to_Arms_(1957_film)", -1]]]
["James_Dean", [["East_of_Eden_(film)", -1]]]
["Julie_Harris_(actress)", [["East_of_Eden_(film)", -1]]]
["Raymond_Massey", [["East_of_Eden_(film)", 5.0]]]
["Jo_Van_Fleet", [["East_of_Eden_(film)", 5.0]]]
["Larry_Parks", [["The_Jolson_Story", 8.0]]]
["Evelyn_Keyes", [["The_Jolson_Story", -1]]]
["William_Demarest", [["The_Jolson_Story", -1]]]
["Bill_Goodwin", [["The_Jolson_Story", -1]]]
["Denzel_Washington", [["American_Gangster_(film)", 2665000000.0]]]
["Chiwetel_Ejiofor", [["American_Gangster_(film)", -1], ["12_Years_a_Slave_(film)", -1]]]
["Cuba_Gooding_Jr.", [["American_Gangster_(film)", -1]]]
["Ted_Levine", [["American_Gangster_(film)", -1]]]
["Armand_Assante", [["American_Gangster_(film)", -1]]]
["John_Ortiz", [["American_Gangster_(film)", -1]]]
["John_Hawkes_(actor)", [["American_Gangster_(film)", -1]]]
["Rza", [["American_Gangster_(film)", -1]]]
["Catherine_Deneuve", [["Indochine_(film)", -1]]]
["Vincent_P%C3%A9rez", [["Indochine_(film)", -1], ["Cyrano_de_Bergerac_(1990_film)", -1]]]
["Linh_Dan_Pham", [["Indochine_(film)", -1]]]
["Jean_Yanne", [["Indochine_(film)", -1]]]
["Dominique_Blanc", [["Indochine_(film)", -1]]]
["Anne_Brochet", [["Cyrano_de_Bergerac_(1990_film)", -1]]]
["Jacques_Weber", [["Cyrano_de_Bergerac_(1990_film)", -1]]]
["Elizabeth_Taylor", [["Who%27s_Afraid_of_Virginia_Woolf%3F_(film)", -1]]]
["Sandy_Dennis", [["Who%27s_Afraid_of_Virginia_Woolf%3F_(film)", -1]]]
["Bruce_Dern", [["Nebraska_(film)", -1]]]
["Will_Forte", [["Nebraska_(film)", -1]]]
["June_Squibb", [["Nebraska_(film)", -1]]]
["Stacy_Keach", [["Nebraska_(film)", -1]]]
["Bob_Odenkirk", [["Nebraska_(film)", -1]]]
["Laura_Dern", [["Rambling_Rose_(film)", -1]]]
["Diane_Ladd", [["Rambling_Rose_(film)", -1]]]
["Lukas_Haas", [["Rambling_Rose_(film)", -1]]]
["John_Heard_(actor)", [["Rambling_Rose_(film)", -1]]]
["Johnny_Depp", [["Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", -1]]]
["Orlando_Bloom", [["Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", -1]]]
["Jonathan_Pryce", [["Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", -1]]]
["Marlene_Dietrich", [["Morocco_(film)", -1]]]
["Adolphe_Menjou", [["Morocco_(film)", 0]]]
["Tom_Hardy", [["The_Revenant_(2015_film)", -1]]]
["Domhnall_Gleeson", [["The_Revenant_(2015_film)", -1]]]
["Will_Poulter", [["The_Revenant_(2015_film)", -1]]]
["Richard_Dix", [["Cimarron_(1931_film)", 0]]]
["Robert_Donat", [["Goodbye,_Mr._Chips_(1939_film)", 0]]]
["Greer_Garson", [["Goodbye,_Mr._Chips_(1939_film)", -1]]]
["Terry_Kilburn", [["Goodbye,_Mr._Chips_(1939_film)", -1]]]
["Ray_Milland", [["Beau_Geste_(1939_film)", -1]]]
["Susan_Hayward", [["Beau_Geste_(1939_film)", -1]]]
["Teri_Garr", [["Close_Encounters_of_the_Third_Kind", -1]]]
["Melinda_Dillon", [["Close_Encounters_of_the_Third_Kind", -1]]]
["Kirk_Douglas", [["Champion_(1949_film)", -1]]]
["Marilyn_Maxwell", [["Champion_(1949_film)", -1]]]
["Arthur_Kennedy", [["Champion_(1949_film)", 25000000.0]]]
["Melvyn_Douglas", [["Hud_(1963_film)", -1]]]
["Brandon_deWilde", [["Hud_(1963_film)", -1]]]
["Daryl_Hannah", [["Wall_Street_(1987_film)", -1]]]
["Hal_Holbrook", [["Wall_Street_(1987_film)", -1]]]
["Terence_Stamp", [["Wall_Street_(1987_film)", -1], ["The_Collector_(1965_film)", -1]]]
["Louise_Fletcher", [["One_Flew_Over_the_Cuckoo%27s_Nest_(film)", -1]]]
["William_Redfield_(actor)", [["One_Flew_Over_the_Cuckoo%27s_Nest_(film)", -1]]]
["Rudolph_Schildkraut", [["A_Ship_Comes_In", -1]]]
["Louise_Dresser", [["A_Ship_Comes_In", 0]]]
["index.php?title=Milton_Holmes&action=edit&redlink=1", [["A_Ship_Comes_In", -1]]]
["index.php?title=Linda_Landi&action=edit&redlink=1", [["A_Ship_Comes_In", -1]]]
["Marie_Dressler", [["Min_and_Bill", 2.0]]]
["John_David_Washington", [["BlacKkKlansman", -1]]]
["Adam_Driver", [["BlacKkKlansman", -1]]]
["Laura_Harrier", [["BlacKkKlansman", -1]]]
["Topher_Grace", [["BlacKkKlansman", -1]]]
["David_Morse_(actor)", [["The_Green_Mile_(film)", -1]]]
["Bonnie_Hunt", [["The_Green_Mile_(film)", -1]]]
["Michael_Clarke_Duncan", [["The_Green_Mile_(film)", -1]]]
["Michael_Jeter", [["The_Green_Mile_(film)", -1]]]
["Doug_Hutchison", [["The_Green_Mile_(film)", -1]]]
["Sam_Rockwell", [["The_Green_Mile_(film)", 2907000000.0]]]
["Barry_Pepper", [["The_Green_Mile_(film)", -1]]]
["Jeffrey_DeMunn", [["The_Green_Mile_(film)", -1]]]
["Harry_Dean_Stanton", [["The_Green_Mile_(film)", -1], ["The_Straight_Story", -1], ["The_Rose_(film)", -1]]]
["Dorothy_McGuire", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["James_Dunn_(actor)", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["Peggy_Ann_Garner", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["Ted_Donaldson", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["James_Gleason", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["Ruth_Nelson_(actress)", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["John_Alexander_(actor)", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["B.S._Pully", [["A_Tree_Grows_in_Brooklyn_(1945_film)", -1]]]
["Vivien_Leigh", [["Ship_of_Fools_(film)", 3500000.0]]]
["Jos%C3%A9_Ferrer", [["Ship_of_Fools_(film)", 22500000.0], ["Cyrano_de_Bergerac_(1950_film)", 22500000.0]]]
["Fredric_March", [["Death_of_a_Salesman_(1951_film)", 12000000.0]]]
["Mildred_Dunnock", [["Death_of_a_Salesman_(1951_film)", -1]]]
["Kevin_McCarthy_(actor)", [["Death_of_a_Salesman_(1951_film)", -1]]]
["Cameron_Mitchell_(actor)", [["Death_of_a_Salesman_(1951_film)", -1]]]
["Dolly_Parton", [["The_Best_Little_Whorehouse_in_Texas_(film)", -1]]]
["Dom_DeLuise", [["The_Best_Little_Whorehouse_in_Texas_(film)", -1]]]
["Jim_Nabors", [["The_Best_Little_Whorehouse_in_Texas_(film)", -1]]]
["Jeanne_Eagels", [["The_Letter_(1929_film)", 0]]]
["O._P._Heggie", [["The_Letter_(1929_film)", -1]]]
["Samantha_Eggar", [["The_Collector_(1965_film)", -1]]]
["Mona_Washbourne", [["The_Collector_(1965_film)", -1]]]
["Tess_Harper", [["Tender_Mercies", -1]]]
["Betty_Buckley", [["Tender_Mercies", -1]]]
["Ellen_Barkin", [["Tender_Mercies", -1]]]
["Maggie_Smith", [["A_Room_with_a_View_(1985_film)", -1], ["Othello_(1965_British_film)", -1]]]
["Denholm_Elliott", [["A_Room_with_a_View_(1985_film)", -1]]]
["Fabia_Drake", [["A_Room_with_a_View_(1985_film)", -1]]]
["Patrick_Godfrey", [["A_Room_with_a_View_(1985_film)", -1]]]
["Rupert_Graves", [["A_Room_with_a_View_(1985_film)", -1]]]
["Rosemary_Leach", [["A_Room_with_a_View_(1985_film)", -1]]]
["Michael_Fassbender", [["12_Years_a_Slave_(film)", -1], ["Steve_Jobs_(film)", -1]]]
["Paul_Giamatti", [["12_Years_a_Slave_(film)", -1]]]
["Lupita_Nyong%27o", [["12_Years_a_Slave_(film)", -1]]]
["Sarah_Paulson", [["12_Years_a_Slave_(film)", -1]]]
["Alfre_Woodard", [["12_Years_a_Slave_(film)", -1]]]
["Eleanor_Parker", [["Caged", -1]]]
["Betty_Garde", [["Caged", -1]]]
["Hope_Emerson", [["Caged", -1]]]
["Ellen_Corby", [["Caged", -1]]]
["Stuart_Erwin", [["Pigskin_Parade", -1]]]
["Patsy_Kelly", [["Pigskin_Parade", -1]]]
["Jack_Haley", [["Pigskin_Parade", -1]]]
["Judy_Garland", [["Pigskin_Parade", -1]]]
["Jesse_Eisenberg", [["The_Social_Network", -1]]]
["Andrew_Garfield", [["The_Social_Network", -1]]]
["Justin_Timberlake", [["The_Social_Network", -1]]]
["Max_Minghella", [["The_Social_Network", -1]]]
["Lady_Gaga", [["A_Star_Is_Born_(2018_film)", -1]]]
["Dave_Chappelle", [["A_Star_Is_Born_(2018_film)", -1]]]
["Stuart_Whitman", [["Murder,_Inc._(1960_film)", -1]]]
["May_Britt", [["Murder,_Inc._(1960_film)", -1]]]
["Henry_Morgan_(comedian)", [["Murder,_Inc._(1960_film)", -1]]]
["Peter_Falk", [["Murder,_Inc._(1960_film)", -1]]]
["Mala_Powers", [["Cyrano_de_Bergerac_(1950_film)", -1]]]
["William_Prince_(actor)", [["Cyrano_de_Bergerac_(1950_film)", -1]]]
["Beau_Bridges", [["Norma_Rae", -1]]]
["Ron_Leibman", [["Norma_Rae", -1]]]
["Vera_Farmiga", [["Up_in_the_Air_(2009_film)", -1]]]
["Anna_Kendrick", [["Up_in_the_Air_(2009_film)", -1]]]
["Danny_McBride", [["Up_in_the_Air_(2009_film)", -1]]]
["Seth_Rogen", [["Steve_Jobs_(film)", -1]]]
["Jeff_Daniels", [["Steve_Jobs_(film)", -1]]]
["Joyce_Redman", [["Othello_(1965_British_film)", -1]]]
["Peter_Firth", [["Equus_(film)", -1]]]
["Jenny_Agutter", [["Equus_(film)", -1]]]
["Joan_Plowright", [["Equus_(film)", -1]]]
["Colin_Blakely", [["Equus_(film)", -1]]]
["Merle_Oberon", [["Wuthering_Heights_(1939_film)", 0]]]
["David_Niven", [["Wuthering_Heights_(1939_film)", -1]]]
["Jane_Fonda", [["On_Golden_Pond_(1981_film)", -1], ["Klute", -1]]]
["Doug_McKeon", [["On_Golden_Pond_(1981_film)", -1]]]
["Dabney_Coleman", [["On_Golden_Pond_(1981_film)", -1]]]
["William_Lanteau", [["On_Golden_Pond_(1981_film)", -1]]]
["Charles_Cioffi", [["Klute", -1]]]
["Roy_Scheider", [["Klute", -1]]]
["Peter_Fonda", [["Ulee%27s_Gold", -1]]]
["Patricia_Richardson", [["Ulee%27s_Gold", -1]]]
["Jessica_Biel", [["Ulee%27s_Gold", -1]]]
["J._Kenneth_Campbell", [["Ulee%27s_Gold", -1]]]
["Christine_Dunford", [["Ulee%27s_Gold", -1]]]
["Thomas_Mills_Wood", [["Ulee%27s_Gold", -1]]]
["Vanessa_Zima", [["Ulee%27s_Gold", -1]]]
["Cedric_Hardwicke", [["Suspicion_(1941_film)", -1]]]
["Dame_May_Whitty", [["Suspicion_(1941_film)", -1]]]
["Alfred_Lunt", [["The_Guardsman", -1]]]
["Lynn_Fontanne", [["The_Guardsman", -1]]]
["Harrison_Ford", [["Witness_(1985_film)", -1]]]
["Bette_Midler", [["The_Rose_(film)", -1]]]
["Frederic_Forrest", [["The_Rose_(film)", -1]]]
["Pam_Grier", [["Jackie_Brown", -1]]]
["Samuel_L._Jackson", [["Jackie_Brown", -1]]]
["Robert_Forster", [["Jackie_Brown", -1]]]
["Bridget_Fonda", [["Jackie_Brown", -1]]]
["Michael_Keaton", [["Jackie_Brown", -1]]]
["Jodie_Foster", [["The_Accused_(1988_film)", -1]]]
["Bernie_Coulson", [["The_Accused_(1988_film)", -1]]]
["Leo_Rossi", [["The_Accused_(1988_film)", -1]]]
["Ann_Hearn", [["The_Accused_(1988_film)", -1]]]
["Carmen_Argenziano", [["The_Accused_(1988_film)", -1]]]
["Steve_Antin", [["The_Accused_(1988_film)", -1]]]
["Don_Murray_(actor)", [["A_Hatful_of_Rain", -1]]]
["Anthony_Franciosa", [["A_Hatful_of_Rain", -1]]]
["Jamie_Foxx", [["Ray_(film)", -1]]]
["Kerry_Washington", [["Ray_(film)", -1]]]
["Clifton_Powell", [["Ray_(film)", -1]]]
["Harry_Lennix", [["Ray_(film)", -1]]]
["Terrence_Howard", [["Ray_(film)", -1]]]
["Larenz_Tate", [["Ray_(film)", -1]]]
["Richard_Schiff", [["Ray_(film)", -1]]]
["Regina_King", [["Ray_(film)", -1]]]
["Kate_Mara", [["127_Hours", -1]]]
["Amber_Tamblyn", [["127_Hours", -1]]]
["Chaim_Topol", [["Fiddler_on_the_Roof_(film)", 833000000.0]]]
["Norma_Crane", [["Fiddler_on_the_Roof_(film)", -1]]]
["Leonard_Frey", [["Fiddler_on_the_Roof_(film)", -1]]]
["Molly_Picon", [["Fiddler_on_the_Roof_(film)", -1]]]
["Paul_Mann", [["Fiddler_on_the_Roof_(film)", -1]]]
