{"id": "Black_Swan_(film)", "name": "Black Swan", "release": "2010-09-01", "box_office": 3294000000.0, "actors_id": ["Natalie_Portman", "Vincent_Cassel", "Mila_Kunis", "Barbara_Hershey", "Winona_Ryder"], "total_actors": 5}
{"id": "The_Fighter", "name": "The Fighter", "release": "2010-12-06", "box_office": 1292000000.0, "actors_id": ["Christian_Bale", "Amy_Adams", "Melissa_Leo", "Jack_McGee_(actor)"], "total_actors": 4}
{"id": "The_King%27s_Speech", "name": "The King's Speech", "release": "2010-09-06", "box_office": 4142000000.0, "actors_id": ["Colin_Firth", "Geoffrey_Rush", "Helena_Bonham_Carter", "Guy_Pearce", "Timothy_Spall", "Derek_Jacobi", "Jennifer_Ehle", "Michael_Gambon"], "total_actors": 8}
{"id": "Twilight_of_Honor", "name": "Twilight of Honor", "release": ["16", "1963", "1963", "10", "16"], "box_office": null, "actors_id": ["Richard_Chamberlain", "Nick_Adams_(actor,_born_1931)"], "total_actors": 2}
{"id": "The_Story_of_Adele_H.", "name": "The Story of Ad\u00e8le H.", "release": "1975-10-08", "box_office": null, "actors_id": ["Isabelle_Adjani", "Bruce_Robinson"], "total_actors": 2}
{"id": "American_Hustle", "name": "American Hustle", "release": "2013-12-08", "box_office": 2512000000.0, "actors_id": ["Christian_Bale", "Bradley_Cooper", "Amy_Adams", "Jeremy_Renner", "Jennifer_Lawrence", "Louis_C._K.", "Michael_Pe%C3%B1a", "Alessandro_Nivola"], "total_actors": 8}
{"id": "Captain_Phillips_(film)", "name": "Captain Phillips", "release": "2013-09-27", "box_office": 2188000000.0, "actors_id": ["Tom_Hanks", "Barkhad_Abdi"], "total_actors": 2}
{"id": "Amadeus_(film)", "name": "Amadeus", "release": "1984-09-06", "box_office": 520000000.0, "actors_id": ["F._Murray_Abraham", "Tom_Hulce", "Elizabeth_Berridge_(actress)", "Simon_Callow", "Roy_Dotrice", "Christine_Ebersole", "Jeffrey_Jones", "Charles_Kay"], "total_actors": 8}
{"id": "Manchester_by_the_Sea_(film)", "name": "Manchester by the Sea", "release": "2016-01-23", "box_office": 790000000.0, "actors_id": ["Casey_Affleck", "Michelle_Williams_(actress)", "Kyle_Chandler", "Gretchen_Mol", "Lucas_Hedges"], "total_actors": 5}
{"id": "House_of_Sand_and_Fog_(film)", "name": "House of Sand and Fog", "release": "2003-12-19", "box_office": 169000000.0, "actors_id": ["Ben_Kingsley", "Shohreh_Aghdashloo", "Jennifer_Connelly", "Ron_Eldard", "Frances_Fisher", "Kim_Dickens"], "total_actors": 6}
{"id": "Juarez_(film)", "name": "Juarez", "release": "1939-04-24", "box_office": null, "actors_id": ["Paul_Muni", "Bette_Davis", "Brian_Aherne", "John_Garfield"], "total_actors": 4}
{"id": "Do_the_Right_Thing", "name": "Do the Right Thing", "release": "1989-05-19", "box_office": 373000000.0, "actors_id": ["Danny_Aiello", "Ossie_Davis", "Ruby_Dee", "Richard_Edson", "Giancarlo_Esposito", "Bill_Nunn", "John_Turturro", "John_Savage_(actor)"], "total_actors": 8}
{"id": "Roman_Holiday", "name": "Roman Holiday", "release": "1953-07-21", "box_office": 120000000.0, "actors_id": ["Gregory_Peck", "Audrey_Hepburn"], "total_actors": 2}
{"id": "The_Subject_Was_Roses_(film)", "name": "The Subject Was Roses", "release": "1968-10-13", "box_office": 1375000.0, "actors_id": ["Patricia_Neal", "Jack_Albertson", "Martin_Sheen"], "total_actors": 3}
{"id": "A_Man_and_a_Woman", "name": "A Man and a Woman", "release": "1966-07-12", "box_office": 14000000.0, "actors_id": ["Anouk_Aim%C3%A9e", "Jean-Louis_Trintignant"], "total_actors": 2}
{"id": "Gaby:_A_True_Story", "name": "Gaby: A True Story", "release": ["30", "1987"], "box_office": 125400.0, "actors_id": ["Liv_Ullmann", "Norma_Aleandro", "Robert_Loggia", "Lawrence_Monoson", "Rachel_Chagall"], "total_actors": 5}
{"id": "The_Great_White_Hope_(film)", "name": "The Great White Hope", "release": ["11", "1970", "1970", "10", "11"], "box_office": null, "actors_id": ["James_Earl_Jones", "Jane_Alexander"], "total_actors": 2}
{"id": "The_Aviator_(2004_film)", "name": "The Aviator", "release": "2004-12-14", "box_office": 2137000000.0, "actors_id": ["Leonardo_DiCaprio", "Cate_Blanchett", "Kate_Beckinsale", "John_C._Reilly", "Alec_Baldwin", "Alan_Alda", "Ian_Holm", "Danny_Huston", "Gwen_Stefani", "Jude_Law"], "total_actors": 10}
{"id": "The_Contender_(2000_film)", "name": "The Contender", "release": "2000-10-13", "box_office": 22361811.0, "actors_id": ["Gary_Oldman", "Joan_Allen", "Jeff_Bridges", "Christian_Slater", "William_Petersen", "Philip_Baker_Hall", "Saul_Rubinek", "Sam_Elliott"], "total_actors": 8}
{"id": "Moonlight_(2016_film)", "name": "Moonlight", "release": "2016-09-02", "box_office": 652000000.0, "actors_id": ["Trevante_Rhodes", "Andr%C3%A9_Holland", "Janelle_Mon%C3%A1e", "Ashton_Sanders", "Naomie_Harris", "Mahershala_Ali"], "total_actors": 6}
{"id": "How_Green_Was_My_Valley_(film)", "name": "How Green Was My Valley", "release": "1941-10-28", "box_office": 28000000.0, "actors_id": ["Walter_Pidgeon", "Maureen_O%27Hara", "Donald_Crisp", "Anna_Lee", "Roddy_McDowall"], "total_actors": 5}
{"id": "Cocoon_(film)", "name": "Cocoon", "release": "1985-06-21", "box_office": 853000000.0, "actors_id": ["Don_Ameche", "Wilford_Brimley", "Hume_Cronyn", "Brian_Dennehy", "Jack_Gilford", "Steve_Guttenberg", "Maureen_Stapleton", "Jessica_Tandy", "Gwen_Verdon", "Herta_Ware", "Tahnee_Welch"], "total_actors": 11}
{"id": "Rebecca_(1940_film)", "name": "Rebecca", "release": "1940-03-21", "box_office": 6.0, "actors_id": ["Laurence_Olivier", "Joan_Fontaine"], "total_actors": 2}
{"id": "Annie_Hall", "name": "Annie Hall", "release": "1977-04-20", "box_office": 383000000.0, "actors_id": ["Diane_Keaton", "Tony_Roberts_(actor)", "Carol_Kane", "Paul_Simon", "Janet_Margolin", "Shelley_Duvall", "Christopher_Walken", "Colleen_Dewhurst"], "total_actors": 8}
{"id": "Tommy_(1975_film)", "name": "Tommy", "release": "1975-03-19", "box_office": 343000000.0, "actors_id": ["Ann-Margret", "Oliver_Reed", "Roger_Daltrey", "Elton_John", "Eric_Clapton", "John_Entwistle", "Keith_Moon", "Paul_Nicholas", "Jack_Nicholson", "Robert_Powell", "Arthur_Brown_(musician)", "Pete_Townshend", "Tina_Turner"], "total_actors": 13}
{"id": "Mary_Poppins_(film)", "name": "Mary Poppins", "release": "1964-08-27", "box_office": 1023000000.0, "actors_id": ["Julie_Andrews", "Dick_Van_Dyke", "David_Tomlinson", "Glynis_Johns", "Hermione_Baddeley", "Karen_Dotrice", "Matthew_Garber", "Elsa_Lanchester", "Arthur_Treacher", "Reginald_Owen", "Ed_Wynn"], "total_actors": 11}
{"id": "Fatal_Attraction", "name": "Fatal Attraction", "release": "1987-09-18", "box_office": 3201000000.0, "actors_id": ["Michael_Douglas", "Glenn_Close", "Anne_Archer"], "total_actors": 3}
{"id": "Mildred_Pierce_(film)", "name": "Mildred Pierce", "release": "1945-09-28", "box_office": null, "actors_id": ["Joan_Crawford", "Jack_Carson", "Zachary_Scott", "Eve_Arden", "Ann_Blyth", "Bruce_Bennett"], "total_actors": 6}
{"id": "Roma_(2018_film)", "name": "Roma", "release": "2018-08-30", "box_office": 41000000.0, "actors_id": ["Yalitza_Aparicio", "Marina_de_Tavira"], "total_actors": 2}
{"id": "Disraeli_(1929_film)", "name": "Disraeli", "release": ["1", "1929", "1929", "11", "01"], "box_office": null, "actors_id": ["George_Arliss", "Doris_Lloyd", "David_Torrence", "Joan_Bennett"], "total_actors": 4}
{"id": "Little_Miss_Sunshine", "name": "Little Miss Sunshine", "release": "2006-01-20", "box_office": 1005000000.0, "actors_id": ["Greg_Kinnear", "Steve_Carell", "Toni_Collette", "Paul_Dano", "Abigail_Breslin", "Alan_Arkin"], "total_actors": 6}
{"id": "The_More_the_Merrier", "name": "The More the Merrier", "release": "1943-05-13", "box_office": 18000000.0, "actors_id": ["Jean_Arthur", "Joel_McCrea", "Charles_Coburn"], "total_actors": 3}
{"id": "Boyhood_(film)", "name": "Boyhood", "release": "2014-01-19", "box_office": 573000000.0, "actors_id": ["Patricia_Arquette", "Ellar_Coltrane", "Lorelei_Linklater", "Ethan_Hawke"], "total_actors": 4}
{"id": "A_Passage_to_India_(film)", "name": "A Passage to India", "release": "1984-12-14", "box_office": 272000000.0, "actors_id": ["Peggy_Ashcroft", "Judy_Davis", "James_Fox", "Alec_Guinness", "Nigel_Havers", "Victor_Banerjee", "Roshan_Seth"], "total_actors": 7}
{"id": "The_Great_Lie", "name": "The Great Lie", "release": "1941-04-12", "box_office": null, "actors_id": ["Bette_Davis", "George_Brent", "Mary_Astor"], "total_actors": 3}
{"id": "My_Man_Godfrey", "name": "My Man Godfrey", "release": "1936-09-06", "box_office": null, "actors_id": ["William_Powell", "Carole_Lombard", "Alice_Brady", "Gail_Patrick", "Eugene_Pallette", "Jean_Dixon", "Alan_Mowbray"], "total_actors": 7}
{"id": "The_Towering_Inferno", "name": "The Towering Inferno", "release": ["14", "1974"], "box_office": 1397000000.0, "actors_id": ["Steve_McQueen", "Paul_Newman", "William_Holden", "Faye_Dunaway", "Fred_Astaire", "Susan_Blakely", "Richard_Chamberlain", "Jennifer_Jones", "O._J._Simpson", "Robert_Vaughn", "Robert_Wagner"], "total_actors": 11}
{"id": "Driving_Miss_Daisy", "name": "Driving Miss Daisy", "release": "1989-12-15", "box_office": 1458000000.0, "actors_id": ["Morgan_Freeman", "Jessica_Tandy", "Dan_Aykroyd", "Patti_LuPone", "Esther_Rolle"], "total_actors": 5}
{"id": "The_Color_Purple_(film)", "name": "The Color Purple", "release": "1985-12-18", "box_office": 1420000000.0, "actors_id": ["Danny_Glover", "Adolph_Caesar", "Margaret_Avery", "Rae_Dawn_Chong", "Whoopi_Goldberg"], "total_actors": 5}
{"id": "The_Mirror_Has_Two_Faces", "name": "The Mirror Has Two Faces", "release": "1996-11-15", "box_office": 91610201.0, "actors_id": ["Jeff_Bridges", "Pierce_Brosnan", "George_Segal", "Mimi_Rogers", "Brenda_Vaccaro", "Lauren_Bacall"], "total_actors": 6}
{"id": "Johnny_Belinda_(1948_film)", "name": "Johnny Belinda", "release": "1948-09-14", "box_office": 41000000.0, "actors_id": ["Jane_Wyman", "Lew_Ayres", "Charles_Bickford", "Agnes_Moorehead"], "total_actors": 4}
{"id": "Room_at_the_Top_(1959_film)", "name": "Room at the Top", "release": "1959-01-22", "box_office": 2400000.0, "actors_id": ["Laurence_Harvey", "Simone_Signoret", "Heather_Sears", "Donald_Wolfit", "Hermione_Baddeley"], "total_actors": 5}
{"id": "To_Kill_a_Mockingbird_(film)", "name": "To Kill a Mockingbird", "release": "1962-12-25", "box_office": 131000000.0, "actors_id": ["Gregory_Peck", "Mary_Badham", "Phillip_Alford", "John_Megna", "Ruth_White_(actress)", "Paul_Fix", "Brock_Peters", "Frank_Overton"], "total_actors": 8}
{"id": "The_Cooler", "name": "The Cooler", "release": "2003-11-26", "box_office": 100000000.0, "actors_id": ["William_H._Macy", "Alec_Baldwin", "Maria_Bello", "Shawn_Hatosy", "Ron_Livingston"], "total_actors": 5}
{"id": "Jezebel_(film)", "name": "Jezebel", "release": "1938-03-10", "box_office": null, "actors_id": ["Bette_Davis", "Henry_Fonda", "George_Brent", "Margaret_Lindsay", "Donald_Crisp", "Fay_Bainter", "Richard_Cromwell_(actor)", "Henry_O%27Neill", "Spring_Byington", "John_Litel"], "total_actors": 10}
{"id": "Baby_Doll", "name": "Baby Doll", "release": "1956-12-18", "box_office": 23000000.0, "actors_id": ["Karl_Malden", "Carroll_Baker", "Eli_Wallach"], "total_actors": 3}
{"id": "A_Thousand_Clowns", "name": "A Thousand Clowns", "release": "1965-12-13", "box_office": 24000000.0, "actors_id": ["Jason_Robards", "Barbara_Harris_(actress)", "Martin_Balsam", "Barry_Gordon"], "total_actors": 4}
{"id": "Thunderbolt_(1929_film)", "name": "Thunderbolt", "release": "1929-07-20", "box_office": null, "actors_id": ["George_Bancroft_(actor)", "Fay_Wray", "Richard_Arlen", "Tully_Marshall", "Eugenie_Besserer"], "total_actors": 5}
{"id": "The_Flight_of_the_Phoenix_(1965_film)", "name": "The Flight of the Phoenix", "release": ["15", "1965", "1965", "12", "15"], "box_office": 3.0, "actors_id": ["James_Stewart", "Richard_Attenborough", "Hardy_Kr%C3%BCger", "Peter_Finch", "Ernest_Borgnine", "Ian_Bannen"], "total_actors": 6}
{"id": "The_Miracle_Worker_(1962_film)", "name": "The Miracle Worker", "release": "1962-07-28", "box_office": 25000000.0, "actors_id": ["Anne_Bancroft", "Patty_Duke"], "total_actors": 2}
{"id": "Cousin_Cousine", "name": "Cousin Cousine", "release": "1975-11-19", "box_office": 87000000.0, "actors_id": ["Marie-Christine_Barrault", "Victor_Lanoux", "Marie-France_Pisier"], "total_actors": 3}
{"id": "Babel_(film)", "name": "Babel", "release": "2006-05-23", "box_office": 1353000000.0, "actors_id": ["Brad_Pitt", "Cate_Blanchett", "Gael_Garc%C3%ADa_Bernal", "K%C5%8Dji_Yakusho", "Adriana_Barraza", "Rinko_Kikuchi"], "total_actors": 6}
{"id": "None_but_the_Lonely_Heart_(film)", "name": "None But the Lonely Heart", "release": "1944-10-17", "box_office": null, "actors_id": ["Cary_Grant", "Ethel_Barrymore", "Barry_Fitzgerald", "June_Duprez", "Jane_Wyatt", "George_Coulouris", "Dan_Duryea"], "total_actors": 7}
{"id": "A_Free_Soul", "name": "A Free Soul", "release": "1931-06-02", "box_office": null, "actors_id": ["Norma_Shearer"], "total_actors": 1}
{"id": "The_Patent_Leather_Kid", "name": "The Patent Leather Kid", "release": "1927-09-01", "box_office": 12000000.0, "actors_id": ["Richard_Barthelmess"], "total_actors": 1}
{"id": "No_Country_for_Old_Men_(film)", "name": "No Country for Old Men", "release": "2007-05-19", "box_office": 1716000000.0, "actors_id": ["Tommy_Lee_Jones", "Javier_Bardem", "Josh_Brolin"], "total_actors": 3}
{"id": "The_Turning_Point_(1977_film)", "name": "The Turning Point", "release": "1977-11-14", "box_office": 336000000.0, "actors_id": ["Shirley_MacLaine", "Anne_Bancroft", "Tom_Skerritt", "Mikhail_Baryshnikov", "Leslie_Browne"], "total_actors": 5}
{"id": "Foreign_Correspondent_(film)", "name": "Foreign Correspondent", "release": "1940-08-16", "box_office": null, "actors_id": ["Joel_McCrea", "Laraine_Day", "Herbert_Marshall", "George_Sanders", "Albert_Basserman"], "total_actors": 5}
{"id": "L.A._Confidential_(film)", "name": "L.A. Confidential", "release": "1997-05-14", "box_office": 1262000000.0, "actors_id": ["Kevin_Spacey", "Russell_Crowe", "Guy_Pearce", "James_Cromwell", "David_Strathairn", "Kim_Basinger", "Danny_DeVito"], "total_actors": 7}
{"id": "The_Fixer_(1968_film)", "name": "The Fixer", "release": ["8", "1968"], "box_office": null, "actors_id": ["Alan_Bates", "Dirk_Bogarde", "Georgia_Brown_(English_singer)"], "total_actors": 3}
{"id": "What%27s_Love_Got_to_Do_with_It_(film)", "name": "What's Love Got to Do with It", "release": "1993-06-06", "box_office": 39100956.0, "actors_id": ["Angela_Bassett", "Laurence_Fishburne"], "total_actors": 2}
{"id": "The_Razor%27s_Edge_(1946_film)", "name": "The Razor's Edge", "release": ["25", "1946", "1946", "12", "25"], "box_office": 5.0, "actors_id": ["Tyrone_Power", "Gene_Tierney", "John_Payne_(actor)", "Herbert_Marshall", "Anne_Baxter", "Clifton_Webb"], "total_actors": 6}
{"id": "In_Old_Arizona", "name": "In Old Arizona", "release": ["25", "1928", "1928", "12", "25", "20", "1929", "1929", "01", "20"], "box_office": 13000000.0, "actors_id": ["Warner_Baxter", "Edmund_Lowe", "Dorothy_Burgess"], "total_actors": 3}
{"id": "Misery_(film)", "name": "Misery", "release": "1990-11-30", "box_office": 613000000.0, "actors_id": ["James_Caan", "Kathy_Bates", "Frances_Sternhagen", "Richard_Farnsworth", "Lauren_Bacall"], "total_actors": 5}
{"id": "Bonnie_and_Clyde_(film)", "name": "Bonnie and Clyde", "release": "1967-08-13", "box_office": 700000000.0, "actors_id": ["Faye_Dunaway", "Michael_J._Pollard", "Gene_Hackman", "Estelle_Parsons"], "total_actors": 4}
{"id": "The_Champ_(1931_film)", "name": "The Champ", "release": "1931-11-09", "box_office": 16000000.0, "actors_id": ["Wallace_Beery", "Jackie_Cooper", "Irene_Rich", "Roscoe_Ates"], "total_actors": 4}
{"id": "Wake_Island_(film)", "name": "Wake Island", "release": "1942-08-11", "box_office": 35000000.0, "actors_id": ["Brian_Donlevy", "Robert_Preston_(actor)", "William_Bendix"], "total_actors": 3}
{"id": "The_Awful_Truth", "name": "The Awful Truth", "release": "1937-10-21", "box_office": 3.0, "actors_id": ["Irene_Dunne", "Cary_Grant", "Ralph_Bellamy", "Alexander_D%27Arcy"], "total_actors": 4}
{"id": "Life_Is_Beautiful", "name": "Life Is Beautiful", "release": "1997-12-20", "box_office": 2292000000.0, "actors_id": ["Nicoletta_Braschi"], "total_actors": 1}
{"id": "Starting_Over_(1979_film)", "name": "Starting Over", "release": "1979-10-05", "box_office": null, "actors_id": ["Burt_Reynolds", "Jill_Clayburgh", "Candice_Bergen", "Charles_Durning", "Frances_Sternhagen", "Austin_Pendleton", "Mary_Kay_Place"], "total_actors": 7}
{"id": "Gaslight_(1944_film)", "name": "Gaslight", "release": "1944-05-04", "box_office": null, "actors_id": ["Charles_Boyer", "Ingrid_Bergman", "Joseph_Cotten", "May_Whitty", "Angela_Lansbury"], "total_actors": 5}
{"id": "Platoon_(film)", "name": "Platoon", "release": ["19", "1986"], "box_office": 1385000000.0, "actors_id": ["Tom_Berenger", "Willem_Dafoe", "Charlie_Sheen"], "total_actors": 3}
{"id": "Escape_Me_Never_(1935_film)", "name": "Escape Me Never", "release": ["1", "1935"], "box_office": null, "actors_id": ["Elisabeth_Bergner", "Hugh_Sinclair_(actor)", "Griffith_Jones_(actor)", "Penelope_Dudley-Ward"], "total_actors": 4}
{"id": "American_Beauty_(1999_film)", "name": "American Beauty", "release": "1999-09-08", "box_office": 3563000000.0, "actors_id": ["Kevin_Spacey", "Annette_Bening", "Thora_Birch", "Allison_Janney", "Peter_Gallagher", "Mena_Suvari", "Wes_Bentley", "Chris_Cooper"], "total_actors": 8}
{"id": "A_Better_Life", "name": "A Better Life", "release": "2011-06-24", "box_office": null, "actors_id": ["Demi%C3%A1n_Bichir"], "total_actors": 1}
{"id": "The_Heartbreak_Kid_(1972_film)", "name": "The Heartbreak Kid", "release": ["17", "1972", "1972", "12", "17"], "box_office": 56000000.0, "actors_id": ["Charles_Grodin", "Cybill_Shepherd", "Jeannie_Berlin", "Eddie_Albert", "Audra_Lindley"], "total_actors": 5}
{"id": "Monster%27s_Ball", "name": "Monster's Ball", "release": "2001-11-11", "box_office": 449000000.0, "actors_id": ["Billy_Bob_Thornton", "Halle_Berry", "Heath_Ledger", "Peter_Boyle", "Sean_Combs", "Mos_Def"], "total_actors": 6}
{"id": "The_Song_of_Bernadette_(film)", "name": "The Song of Bernadette", "release": "1943-12-21", "box_office": 5.0, "actors_id": ["Jennifer_Jones", "William_Eythe", "Charles_Bickford", "Vincent_Price", "Lee_J._Cobb", "Gladys_Cooper"], "total_actors": 6}
{"id": "The_Defiant_Ones_(film)", "name": "The Defiant Ones", "release": "1958-09-24", "box_office": null, "actors_id": ["Sidney_Poitier", "Tony_Curtis"], "total_actors": 2}
{"id": "Five_Easy_Pieces", "name": "Five Easy Pieces", "release": ["12", "1970"], "box_office": 181000000.0, "actors_id": ["Jack_Nicholson", "Karen_Black", "Susan_Anspach"], "total_actors": 3}
{"id": "The_English_Patient_(film)", "name": "The English Patient", "release": "1996-11-15", "box_office": 2320000000.0, "actors_id": ["Ralph_Fiennes", "Juliette_Binoche", "Willem_Dafoe", "Kristin_Scott_Thomas", "Naveen_Andrews", "Colin_Firth", "Julian_Wadham", "J%C3%BCrgen_Prochnow"], "total_actors": 8}
{"id": "Nashville_(film)", "name": "Nashville", "release": "1975-06-11", "box_office": 100000000.0, "actors_id": ["Ned_Beatty", "Ronee_Blakley", "Keith_Carradine", "Geraldine_Chaplin", "Henry_Gibson", "Michael_Murphy_(actor)", "Lily_Tomlin"], "total_actors": 7}
{"id": "Blue_Jasmine", "name": "Blue Jasmine", "release": "2013-07-26", "box_office": 975000000.0, "actors_id": ["Cate_Blanchett", "Alec_Baldwin", "Louis_C.K.", "Bobby_Cannavale", "Andrew_Dice_Clay", "Sally_Hawkins", "Peter_Sarsgaard", "Michael_Stuhlbarg"], "total_actors": 8}
{"id": "Secrets_%26_Lies_(film)", "name": "Secrets & Lies", "release": ["1996", "1996", "05", "24", "1996", "1996", "05", "24"], "box_office": 134000000.0, "actors_id": ["Timothy_Spall", "Brenda_Blethyn", "Phyllis_Logan", "Marianne_Jean-Baptiste", "Claire_Rushbrook", "Ron_Cook", "Lesley_Manville", "Elizabeth_Berrington", "Michele_Austin", "Lee_Ross_(actor)", "Emma_Amos_(actress)"], "total_actors": 11}
{"id": "Mudbound_(film)", "name": "Mudbound", "release": "2017-01-21", "box_office": null, "actors_id": ["Carey_Mulligan", "Jason_Clarke", "Jason_Mitchell_(actor)", "Mary_J._Blige", "Rob_Morgan_(actor)", "Jonathan_Banks", "Garrett_Hedlund"], "total_actors": 7}
{"id": "The_Blue_Veil_(1951_film)", "name": "The Blue Veil", "release": "1951-09-05", "box_office": null, "actors_id": ["Jane_Wyman", "Charles_Laughton", "Joan_Blondell"], "total_actors": 3}
{"id": "The_African_Queen_(film)", "name": "The African Queen", "release": "1951-12-26", "box_office": null, "actors_id": ["Humphrey_Bogart", "Katharine_Hepburn", "Robert_Morley"], "total_actors": 3}
{"id": "The_Gorgeous_Hussy", "name": "The Gorgeous Hussy", "release": "1936-08-28", "box_office": null, "actors_id": ["Joan_Crawford", "Robert_Taylor_(actor)", "Lionel_Barrymore", "Franchot_Tone"], "total_actors": 4}
{"id": "The_Wings_of_the_Dove_(1997_film)", "name": "The Wings of the Dove", "release": "1997-11-07", "box_office": 137000000.0, "actors_id": ["Helena_Bonham_Carter", "Linus_Roache", "Alison_Elliott", "Elizabeth_McGovern", "Michael_Gambon", "Alex_Jennings", "Charlotte_Rampling"], "total_actors": 7}
{"id": "Come_Back,_Little_Sheba_(1952_film)", "name": "Come Back, Little Sheba", "release": ["24", "1952", "1952", "12", "24"], "box_office": 35000000.0, "actors_id": ["Burt_Lancaster", "Shirley_Booth", "Terry_Moore_(actress)"], "total_actors": 3}
{"id": "Conquest_(1937_film)", "name": "Conquest", "release": "1937-10-22", "box_office": 2141000.0, "actors_id": ["Greta_Garbo", "Charles_Boyer", "Reginald_Owen", "Alan_Marshal_(actor)"], "total_actors": 4}
{"id": "In_Old_Chicago", "name": "In Old Chicago", "release": "1938-01-06", "box_office": 25000000.0, "actors_id": ["Tyrone_Power", "Alice_Faye", "Don_Ameche", "Alice_Brady"], "total_actors": 4}
{"id": "Henry_V_(1989_film)", "name": "Henry V", "release": "1989-10-06", "box_office": 102000000.0, "actors_id": ["Paul_Scofield", "Derek_Jacobi", "Ian_Holm", "Emma_Thompson", "Alec_McCowen", "Judi_Dench", "Christian_Bale"], "total_actors": 7}
{"id": "Goodfellas", "name": "Goodfellas", "release": "1990-09-09", "box_office": 468000000.0, "actors_id": ["Robert_De_Niro", "Ray_Liotta", "Joe_Pesci", "Lorraine_Bracco", "Paul_Sorvino"], "total_actors": 5}
{"id": "Out_of_Africa_(film)", "name": "Out of Africa", "release": "1985-12-18", "box_office": 2275000000.0, "actors_id": ["Robert_Redford", "Meryl_Streep", "Klaus_Maria_Brandauer"], "total_actors": 3}
{"id": "On_the_Waterfront", "name": "On the Waterfront", "release": "1954-07-28", "box_office": 96000000.0, "actors_id": ["Marlon_Brando", "Karl_Malden", "Lee_J._Cobb", "Rod_Steiger", "Pat_Henning", "Eva_Marie_Saint"], "total_actors": 6}
{"id": "Come_and_Get_It_(1936_film)", "name": "Come and Get It", "release": "1936-11-06", "box_office": null, "actors_id": ["Edward_Arnold_(actor)", "Joel_McCrea", "Frances_Farmer", "Walter_Brennan"], "total_actors": 4}
{"id": "Crazy_Heart", "name": "Crazy Heart", "release": "2009-12-06", "box_office": 474000000.0, "actors_id": ["Jeff_Bridges", "Maggie_Gyllenhaal", "Colin_Farrell"], "total_actors": 3}
{"id": "Iris_(2001_film)", "name": "Iris", "release": "2001-12-14", "box_office": 162000000.0, "actors_id": ["Judi_Dench", "Kate_Winslet", "Jim_Broadbent", "Hugh_Bonneville"], "total_actors": 4}
{"id": "The_Pianist_(2002_film)", "name": "The Pianist", "release": "2002-05-24", "box_office": 1201000000.0, "actors_id": ["Adrien_Brody", "Thomas_Kretschmann", "Frank_Finlay", "Maureen_Lipman", "Emilia_Fox", "Micha%C5%82_%C5%BBebrowski"], "total_actors": 6}
{"id": "Anne_of_the_Thousand_Days", "name": "Anne of the Thousand Days", "release": "1969-12-18", "box_office": 6134264.0, "actors_id": ["Richard_Burton", "Genevi%C3%A8ve_Bujold", "Anthony_Quayle", "John_Colicos", "Irene_Papas"], "total_actors": 5}
{"id": "Milk_(film)", "name": "Milk", "release": "2008-10-28", "box_office": 546000000.0, "actors_id": ["Sean_Penn", "Emile_Hirsch", "Josh_Brolin", "Diego_Luna", "Alison_Pill", "Victor_Garber", "Denis_O%27Hare", "Joseph_Cross_(actor)", "James_Franco"], "total_actors": 9}
{"id": "The_Blind_Side_(film)", "name": "The Blind Side", "release": "2009-11-20", "box_office": 3092000000.0, "actors_id": ["Sandra_Bullock", "Tim_McGraw", "Quinton_Aaron", "Jae_Head", "Lily_Collins", "Ray_McKinnon_(actor)", "Kathy_Bates"], "total_actors": 7}
{"id": "Merrily_We_Live", "name": "Merrily We Live", "release": "1938-03-04", "box_office": null, "actors_id": ["Constance_Bennett", "Brian_Aherne"], "total_actors": 2}
{"id": "Last_Summer", "name": "Last Summer", "release": "1969-06-19", "box_office": 3.0, "actors_id": ["Catherine_Burns", "Barbara_Hershey", "Bruce_Davison", "Richard_Thomas_(actor)"], "total_actors": 4}
{"id": "The_Sunshine_Boys_(1975_film)", "name": "The Sunshine Boys", "release": "1975-11-06", "box_office": null, "actors_id": ["Walter_Matthau", "George_Burns", "Richard_Benjamin", "Lee_Meredith"], "total_actors": 4}
{"id": "The_Buddy_Holly_Story", "name": "The Buddy Holly Story", "release": "1978-05-18", "box_office": 143000000.0, "actors_id": ["Gary_Busey", "Don_Stroud", "Charles_Martin_Smith", "Conrad_Janis", "Paul_Mooney_(comedian)"], "total_actors": 5}
{"id": "The_Robe_(film)", "name": "The Robe", "release": "1953-09-16", "box_office": 360000000.0, "actors_id": ["Richard_Burton", "Jean_Simmons", "Victor_Mature", "Michael_Rennie"], "total_actors": 4}
{"id": "Sayonara", "name": "Sayonara", "release": "1957-12-05", "box_office": 22000115.0, "actors_id": ["Marlon_Brando", "Patricia_Owens", "James_Garner", "Martha_Scott", "Miiko_Taka", "Miyoshi_Umeki", "Red_Buttons", "Ricardo_Montalb%C3%A1n"], "total_actors": 8}
{"id": "You_Can%27t_Take_It_with_You_(film)", "name": "You Can't Take It with You", "release": "1938-08-23", "box_office": 2137575.0, "actors_id": ["Jean_Arthur", "Lionel_Barrymore", "James_Stewart", "Edward_Arnold_(actor)"], "total_actors": 4}
{"id": "A_Soldier%27s_Story", "name": "A Soldier's Story", "release": "1984-09-13", "box_office": null, "actors_id": ["Howard_Rollins", "Adolph_Caesar"], "total_actors": 2}
{"id": "Leaving_Las_Vegas", "name": "Leaving Las Vegas", "release": "1995-10-27", "box_office": 498000000.0, "actors_id": ["Nicolas_Cage", "Elisabeth_Shue", "Julian_Sands"], "total_actors": 3}
{"id": "Yankee_Doodle_Dandy", "name": "Yankee Doodle Dandy", "release": "1942-05-29", "box_office": null, "actors_id": ["James_Cagney", "Joan_Leslie", "Walter_Huston", "Richard_Whorf"], "total_actors": 4}
{"id": "The_Magnificent_Yankee_(1950_film)", "name": "The Magnificent Yankee", "release": ["1950", "1950"], "box_office": null, "actors_id": ["Louis_Calhern", "Ann_Harding", "Eduard_Franz", "Philip_Ober"], "total_actors": 4}
{"id": "The_Godfather", "name": "The Godfather", "release": "1972-03-15", "box_office": null, "actors_id": ["Marlon_Brando", "Al_Pacino", "James_Caan", "Richard_Castellano", "Robert_Duvall", "Sterling_Hayden", "John_Marley", "Richard_Conte", "Diane_Keaton"], "total_actors": 9}
{"id": "Hannah_and_Her_Sisters", "name": "Hannah and Her Sisters", "release": "1986-02-07", "box_office": 401000000.0, "actors_id": ["Michael_Caine", "Mia_Farrow", "Carrie_Fisher", "Barbara_Hershey", "Lloyd_Nolan", "Maureen_O%27Sullivan", "Daniel_Stern_(actor)", "Max_von_Sydow", "Dianne_Wiest"], "total_actors": 9}
{"id": "Faces_(film)", "name": "Faces", "release": ["1968", "1968", "03"], "box_office": null, "actors_id": ["John_Marley", "Gena_Rowlands", "Lynn_Carlin", "Seymour_Cassel", "Fred_Draper", "Val_Avery", "Dorothy_Gulliver"], "total_actors": 7}
{"id": "Foxcatcher", "name": "Foxcatcher", "release": "2014-05-19", "box_office": 192000000.0, "actors_id": ["Steve_Carell", "Channing_Tatum", "Mark_Ruffalo", "Vanessa_Redgrave"], "total_actors": 4}
{"id": "Harry_and_Tonto", "name": "Harry and Tonto", "release": "1974-08-12", "box_office": 46000000.0, "actors_id": ["Art_Carney", "Herbert_Berghof", "Philip_Bruns", "Ellen_Burstyn", "Geraldine_Fitzgerald", "Larry_Hagman", "Chief_Dan_George", "Melanie_Mayron", "Josh_Mostel", "Arthur_Hunnicutt", "Barbara_Rhoades", "Cliff_DeYoung", "Avon_Long"], "total_actors": 13}
{"id": "Lili", "name": "Lili", "release": "1953-03-10", "box_office": null, "actors_id": ["Leslie_Caron", "Mel_Ferrer", "Jean-Pierre_Aumont", "Zsa_Zsa_Gabor"], "total_actors": 4}
{"id": "The_Devil%27s_Holiday", "name": "The Devil's Holiday", "release": ["9", "1930"], "box_office": null, "actors_id": ["Nancy_Carroll"], "total_actors": 1}
{"id": "Claudine_(film)", "name": "Claudine", "release": "1974-04-22", "box_office": null, "actors_id": ["Diahann_Carroll", "James_Earl_Jones", "Lawrence_Hilton-Jacobs", "Adam_Wade_(singer)", "Roxie_Roker"], "total_actors": 5}
{"id": "Auntie_Mame_(film)", "name": "Auntie Mame", "release": "1958-12-04", "box_office": 93000000.0, "actors_id": ["Rosalind_Russell", "Forrest_Tucker", "Coral_Browne", "Roger_Smith_(actor)", "Peggy_Cass", "Joanna_Barnes", "Robin_Hughes", "Pippa_Scott"], "total_actors": 8}
{"id": "The_Dirty_Dozen", "name": "The Dirty Dozen", "release": "1967-06-15", "box_office": 453000000.0, "actors_id": ["Lee_Marvin", "Ernest_Borgnine", "Charles_Bronson", "Jim_Brown", "John_Cassavetes", "Richard_Jaeckel", "George_Kennedy", "Trini_Lopez", "Ralph_Meeker", "Robert_Ryan", "Telly_Savalas", "Clint_Walker", "Robert_Webber"], "total_actors": 13}
{"id": "Lovers_and_Other_Strangers", "name": "Lovers and Other Strangers", "release": ["12", "1970", "1970", "08", "12"], "box_office": null, "actors_id": ["Beatrice_Arthur", "Richard_S._Castellano", "Bonnie_Bedelia", "Gig_Young"], "total_actors": 4}
{"id": "Whale_Rider", "name": "Whale Rider", "release": "2002-09-09", "box_office": 414000000.0, "actors_id": ["Keisha_Castle-Hughes", "Rawiri_Paratene", "Cliff_Curtis"], "total_actors": 3}
{"id": "West_Side_Story_(film)", "name": "West Side Story", "release": "1961-10-18", "box_office": 441000000.0, "actors_id": ["Natalie_Wood", "Richard_Beymer", "Rita_Moreno", "George_Chakiris", "Russ_Tamblyn"], "total_actors": 5}
{"id": "Broken_Arrow_(1950_film)", "name": "Broken Arrow", "release": ["20", "1950", "1950", "07", "20"], "box_office": 3550000.0, "actors_id": ["James_Stewart", "Jeff_Chandler", "Debra_Paget"], "total_actors": 3}
{"id": "Thoroughly_Modern_Millie", "name": "Thoroughly Modern Millie", "release": "1967-03-21", "box_office": 400000000.0, "actors_id": ["Julie_Andrews", "Mary_Tyler_Moore", "Carol_Channing", "James_Fox", "John_Gavin", "Beatrice_Lillie"], "total_actors": 6}
{"id": "Six_Degrees_of_Separation_(film)", "name": "Six Degrees of Separation", "release": "1993-12-08", "box_office": 64000000.0, "actors_id": ["Stockard_Channing", "Will_Smith", "Donald_Sutherland", "Mary_Beth_Hurt", "Bruce_Davison", "Ian_McKellen"], "total_actors": 6}
{"id": "The_Great_Dictator", "name": "The  Great Dictator", "release": "1940-10-15", "box_office": 5.0, "actors_id": ["Paulette_Goddard", "Jack_Oakie", "Henry_Daniell", "Reginald_Gardiner", "Billy_Gilbert", "Maurice_Moscovich"], "total_actors": 6}
{"id": "Madame_X_(1929_film)", "name": "Madame X", "release": "1929-08-17", "box_office": null, "actors_id": ["Ruth_Chatterton", "Lewis_Stone"], "total_actors": 2}
{"id": "Zero_Dark_Thirty", "name": "Zero Dark Thirty", "release": "2012-12-19", "box_office": 1328000000.0, "actors_id": ["Jessica_Chastain", "Jason_Clarke", "Joel_Edgerton", "Kyle_Chandler", "Mark_Strong", "Chris_Pratt", "James_Gandolfini"], "total_actors": 7}
{"id": "Moonstruck", "name": "Moonstruck", "release": "1987-12-16", "box_office": 806000000.0, "actors_id": ["Cher", "Nicolas_Cage", "Vincent_Gardenia", "Olympia_Dukakis", "Danny_Aiello"], "total_actors": 5}
{"id": "Call_Me_by_Your_Name_(film)", "name": "Call Me by Your Name", "release": "2017-01-22", "box_office": 419000000.0, "actors_id": ["Armie_Hammer", "Timoth%C3%A9e_Chalamet", "Michael_Stuhlbarg", "Amira_Casar", "Esther_Garrel", "Victoire_Du_Bois"], "total_actors": 6}
{"id": "The_Love_Parade", "name": "The Love Parade", "release": ["19", "1929", "18", "1930", "1"], "box_office": null, "actors_id": ["Maurice_Chevalier", "Jeanette_MacDonald", "Lillian_Roth", "Eugene_Pallette"], "total_actors": 4}
{"id": "Hotel_Rwanda", "name": "Hotel Rwanda", "release": "2004-12-22", "box_office": 339000000.0, "actors_id": ["Don_Cheadle", "Sophie_Okonedo", "Joaquin_Phoenix", "Nick_Nolte"], "total_actors": 4}
{"id": "Spellbound_(1945_film)", "name": "Spellbound", "release": "1945-10-31", "box_office": 6387000.0, "actors_id": ["Ingrid_Bergman", "Gregory_Peck", "Michael_Chekhov"], "total_actors": 3}
{"id": "Darling_(1965_film)", "name": "Darling", "release": "1965-07-15", "box_office": null, "actors_id": ["Julie_Christie", "Laurence_Harvey", "Dirk_Bogarde"], "total_actors": 3}
{"id": "Tom_Jones_(1963_film)", "name": "Tom Jones", "release": "1963-09-29", "box_office": 37600000.0, "actors_id": ["Albert_Finney", "Susannah_York", "Hugh_Griffith", "Edith_Evans", "Joan_Greenwood", "Diane_Cilento", "George_Devine", "David_Tomlinson"], "total_actors": 8}
{"id": "An_Unmarried_Woman", "name": "An Unmarried Woman", "release": "1978-03-05", "box_office": null, "actors_id": ["Jill_Clayburgh", "Alan_Bates", "Michael_Murphy_(actor)", "Cliff_Gorman"], "total_actors": 4}
{"id": "Pieces_of_April", "name": "Pieces of April", "release": "2003-10-17", "box_office": 33000000.0, "actors_id": ["Katie_Holmes", "Derek_Luke_(actor)", "Sean_Hayes_(actor)", "Alison_Pill", "Oliver_Platt", "Patricia_Clarkson"], "total_actors": 6}
{"id": "The_Search", "name": "The Search", "release": "1948-03-23", "box_office": null, "actors_id": ["Aline_MacMahon", "Jarmila_Novotn%C3%A1", "Wendell_Corey", "Ivan_Jandl"], "total_actors": 4}
{"id": "American_Graffiti", "name": "American Graffiti", "release": "1973-08-02", "box_office": 1400000000.0, "actors_id": ["Richard_Dreyfuss", "Ron_Howard", "Paul_Le_Mat", "Charles_Martin_Smith", "Candy_Clark", "Mackenzie_Phillips", "Cindy_Williams", "Wolfman_Jack"], "total_actors": 8}
{"id": "Syriana", "name": "Syriana", "release": "2005-11-20", "box_office": 940000000.0, "actors_id": ["George_Clooney", "Matt_Damon", "Jeffrey_Wright_(actor)", "Chris_Cooper", "William_Hurt", "Mazhar_Munir", "Tim_Blake_Nelson", "Amanda_Peet", "Christopher_Plummer", "Alexander_Siddig"], "total_actors": 10}
{"id": "Affliction_(1997_film)", "name": "Affliction", "release": "1997-08-28", "box_office": null, "actors_id": ["Nick_Nolte", "Sissy_Spacek", "James_Coburn", "Willem_Dafoe", "Mary_Beth_Hurt", "Jim_True-Frost"], "total_actors": 6}
{"id": "It_Happened_One_Night", "name": "It Happened One Night", "release": "1934-02-22", "box_office": null, "actors_id": ["Clark_Gable", "Claudette_Colbert"], "total_actors": 2}
{"id": "The_Sixth_Sense", "name": "The Sixth Sense", "release": "1999-08-02", "box_office": 6728000000.0, "actors_id": ["Bruce_Willis", "Toni_Collette", "Olivia_Williams", "Haley_Joel_Osment"], "total_actors": 4}
{"id": "Shirley_Valentine_(film)", "name": "Shirley Valentine", "release": "1989-08-30", "box_office": 6353913.0, "actors_id": ["Pauline_Collins", "Tom_Conti"], "total_actors": 2}
{"id": "The_Little_Foxes_(film)", "name": "The Little Foxes", "release": "1941-08-29", "box_office": null, "actors_id": ["Bette_Davis", "Herbert_Marshall", "Teresa_Wright"], "total_actors": 3}
{"id": "The_Barker", "name": "The Barker", "release": ["9", "1928"], "box_office": null, "actors_id": ["Milton_Sills", "Dorothy_Mackaill", "Betty_Compson", "Douglas_Fairbanks_Jr."], "total_actors": 4}
{"id": "The_Favourite", "name": "The Favourite", "release": "2018-08-30", "box_office": 826000000.0, "actors_id": ["Olivia_Colman", "Emma_Stone", "Rachel_Weisz", "Nicholas_Hoult", "Joe_Alwyn"], "total_actors": 5}
{"id": "A_Beautiful_Mind_(film)", "name": "A Beautiful Mind", "release": "2001-12-13", "box_office": 3130000000.0, "actors_id": ["Russell_Crowe", "Ed_Harris", "Jennifer_Connelly", "Paul_Bettany", "Adam_Goldberg", "Judd_Hirsch", "Josh_Lucas", "Anthony_Rapp", "Christopher_Plummer"], "total_actors": 9}
{"id": "Reuben,_Reuben", "name": "Reuben, Reuben", "release": "1983-12-19", "box_office": null, "actors_id": ["Tom_Conti", "Kelly_McGillis"], "total_actors": 2}
{"id": "Adaptation_(film)", "name": "Adaptation.", "release": "2002-12-06", "box_office": 328000000.0, "actors_id": ["Nicolas_Cage", "Meryl_Streep", "Chris_Cooper", "Brian_Cox_(actor)", "Tilda_Swinton", "Ron_Livingston", "Maggie_Gyllenhaal"], "total_actors": 7}
{"id": "Sergeant_York_(film)", "name": "Sergeant York", "release": "1941-07-02", "box_office": null, "actors_id": ["Gary_Cooper", "Walter_Brennan", "Joan_Leslie"], "total_actors": 3}
{"id": "Silver_Linings_Playbook", "name": "Silver Linings Playbook", "release": "2012-09-08", "box_office": 2364000000.0, "actors_id": ["Bradley_Cooper", "Jennifer_Lawrence", "Robert_De_Niro", "Jacki_Weaver", "Anupam_Kher", "Chris_Tucker"], "total_actors": 6}
{"id": "Skippy_(film)", "name": "Skippy", "release": "1931-04-05", "box_office": null, "actors_id": ["Jackie_Cooper", "Robert_Coogan", "Mitzi_Green", "Jackie_Searl"], "total_actors": 4}
{"id": "Now,_Voyager", "name": "Now, Voyager", "release": "1942-10-22", "box_office": 22000000.0, "actors_id": ["Bette_Davis", "Paul_Henreid", "Claude_Rains", "Gladys_Cooper"], "total_actors": 4}
{"id": "Day_for_Night_(film)", "name": "Day for Night", "release": "1973-05-14", "box_office": null, "actors_id": ["Jacqueline_Bisset", "Valentina_Cortese", "Dani_(singer)", "Alexandra_Stewart", "Jean-Pierre_Aumont", "Jean_Champion", "Jean-Pierre_L%C3%A9aud", "Fran%C3%A7ois_Truffaut"], "total_actors": 8}
{"id": "La_Vie_en_rose_(film)", "name": "La Vie en Rose", "release": "2007-02-08", "box_office": 863000000.0, "actors_id": ["Marion_Cotillard", "G%C3%A9rard_Depardieu", "Sylvie_Testud"], "total_actors": 3}
{"id": "Dances_with_Wolves", "name": "Dances with Wolves", "release": "1990-10-19", "box_office": 4242000000.0, "actors_id": ["Mary_McDonnell", "Graham_Greene_(actor)", "Rodney_A._Grant"], "total_actors": 3}
{"id": "Pinky_(film)", "name": "Pinky", "release": "1949-09-29", "box_office": 42000000.0, "actors_id": ["Jeanne_Crain", "Ethel_Barrymore", "Ethel_Waters"], "total_actors": 3}
{"id": "Trumbo_(2015_film)", "name": "Trumbo", "release": "2015-09-12", "box_office": 121000000.0, "actors_id": ["Bryan_Cranston", "Adewale_Akinnuoye-Agbaje", "Louis_C.K.", "David_James_Elliott", "Elle_Fanning", "John_Goodman", "Diane_Lane", "Michael_Stuhlbarg", "Alan_Tudyk", "Helen_Mirren"], "total_actors": 10}
{"id": "All_the_King%27s_Men_(1949_film)", "name": "All the King's Men", "release": "1949-11-08", "box_office": 24000000.0, "actors_id": ["Broderick_Crawford", "John_Ireland_(actor)", "Mercedes_McCambridge", "Joanne_Dru", "John_Derek", "Shepperd_Strudwick"], "total_actors": 6}
{"id": "Babe_(film)", "name": "Babe", "release": "1995-08-04", "box_office": 2541000000.0, "actors_id": ["James_Cromwell", "Magda_Szubanski"], "total_actors": 2}
{"id": "The_Seventh_Cross_(film)", "name": "The Seventh Cross", "release": "1944-07-24", "box_office": 36000000.0, "actors_id": ["Spencer_Tracy", "Signe_Hasso", "Hume_Cronyn", "Jessica_Tandy", "Agnes_Moorehead", "Herbert_Rudley", "Felix_Bressart", "Ray_Collins_(actor)"], "total_actors": 8}
{"id": "The_Reivers_(film)", "name": "The Reivers", "release": "1969-12-25", "box_office": null, "actors_id": ["Steve_McQueen", "Sharon_Farrell", "Mitch_Vogel", "Rupert_Crosse", "Burgess_Meredith", "Will_Geer"], "total_actors": 6}
{"id": "Places_in_the_Heart", "name": "Places in the Heart", "release": ["21", "1984"], "box_office": 349000000.0, "actors_id": ["Sally_Field", "Lindsay_Crouse", "Ed_Harris", "Ray_Baker_(actor)", "Amy_Madigan", "John_Malkovich", "Danny_Glover", "Terry_O%27Quinn"], "total_actors": 8}
{"id": "Vicky_Cristina_Barcelona", "name": "Vicky Cristina Barcelona", "release": "2008-05-17", "box_office": 964000000.0, "actors_id": ["Javier_Bardem", "Pen%C3%A9lope_Cruz", "Scarlett_Johansson", "Patricia_Clarkson", "Kevin_Dunn", "Rebecca_Hall", "Chris_Messina"], "total_actors": 7}
{"id": "Gladiator_(2000_film)", "name": "Gladiator", "release": "2000-05-01", "box_office": 4605000000.0, "actors_id": ["Russell_Crowe", "Joaquin_Phoenix", "Connie_Nielsen", "Oliver_Reed", "Derek_Jacobi", "Djimon_Hounsou", "Richard_Harris"], "total_actors": 7}
{"id": "Born_on_the_Fourth_of_July_(film)", "name": "Born on the Fourth of July", "release": "1989-12-20", "box_office": 1610000000.0, "actors_id": ["Tom_Cruise", "Kyra_Sedgwick", "Raymond_J._Barry", "Jerry_Levine", "Frank_Whaley", "Willem_Dafoe"], "total_actors": 6}
{"id": "The_Imitation_Game", "name": "The Imitation Game", "release": "2014-08-29", "box_office": 2336000000.0, "actors_id": ["Benedict_Cumberbatch", "Keira_Knightley", "Matthew_Goode", "Rory_Kinnear", "Charles_Dance", "Mark_Strong"], "total_actors": 6}
{"id": "When_My_Baby_Smiles_at_Me_(film)", "name": "When My Baby Smiles at Me", "release": "1948-11-10", "box_office": 34000000.0, "actors_id": ["Betty_Grable", "Dan_Dailey"], "total_actors": 2}
{"id": "The_Corn_Is_Green_(1945_film)", "name": "The Corn Is Green", "release": "1945-07-14", "box_office": 3649000.0, "actors_id": ["Bette_Davis", "Nigel_Bruce", "John_Dall"], "total_actors": 3}
{"id": "At_Eternity%27s_Gate_(film)", "name": "At Eternity's Gate", "release": "2018-09-03", "box_office": 69000000.0, "actors_id": ["Willem_Dafoe", "Rupert_Friend", "Mads_Mikkelsen", "Mathieu_Amalric", "Emmanuelle_Seigner", "Oscar_Isaac"], "total_actors": 6}
{"id": "Carmen_Jones_(film)", "name": "Carmen Jones", "release": "1954-10-28", "box_office": 98000000.0, "actors_id": ["Harry_Belafonte", "Dorothy_Dandridge", "Pearl_Bailey"], "total_actors": 3}
{"id": "Captain_Newman,_M.D.", "name": "Captain Newman, M.D.", "release": "1963-12-23", "box_office": 42500000.0, "actors_id": ["Gregory_Peck", "Tony_Curtis", "Angie_Dickinson", "Robert_Duvall", "Eddie_Albert", "Bobby_Darin"], "total_actors": 6}
{"id": "Dangerous_(film)", "name": "Dangerous", "release": "1935-12-25", "box_office": null, "actors_id": ["Bette_Davis", "Franchot_Tone", "Margaret_Lindsay"], "total_actors": 3}
{"id": "Good_Will_Hunting", "name": "Good Will Hunting", "release": "1997-12-02", "box_office": 2259000000.0, "actors_id": ["Robin_Williams", "Stellan_Skarsg%C3%A5rd", "Minnie_Driver"], "total_actors": 3}
{"id": "The_Grapes_of_Wrath_(film)", "name": "The Grapes of Wrath", "release": "1940-01-24", "box_office": 25000000.0, "actors_id": ["Henry_Fonda", "Jane_Darwell", "John_Carradine", "Shirley_Mills", "John_Qualen", "Eddie_Quillan"], "total_actors": 6}
{"id": "The_Crying_Game", "name": "The Crying Game", "release": "1992-09-18", "box_office": 625000000.0, "actors_id": ["Stephen_Rea", "Miranda_Richardson", "Jaye_Davidson", "Forest_Whitaker"], "total_actors": 4}
{"id": "The_Accidental_Tourist_(film)", "name": "The Accidental Tourist", "release": "1988-12-23", "box_office": 32632093.0, "actors_id": ["William_Hurt", "Kathleen_Turner", "Geena_Davis"], "total_actors": 3}
{"id": "Longtime_Companion", "name": "Longtime Companion", "release": ["11", "1989", "1"], "box_office": null, "actors_id": ["Stephen_Caffrey_(actor)", "Patrick_Cassidy_(actor)", "Bruce_Davison", "John_Dossett", "Mark_Lamos", "Dermot_Mulroney", "Mary-Louise_Parker", "Michael_Schoeffling", "Campbell_Scott"], "total_actors": 9}
{"id": "Fences_(film)", "name": "Fences", "release": "2016-12-15", "box_office": 644000000.0, "actors_id": ["Viola_Davis", "Stephen_Henderson_(actor)", "Jovan_Adepo", "Russell_Hornsby", "Mykelti_Williamson", "Saniyya_Sidney"], "total_actors": 6}
{"id": "My_Left_Foot", "name": "My Left Foot", "release": "1989-02-24", "box_office": 147000000.0, "actors_id": ["Daniel_Day-Lewis", "Ray_McAnally", "Brenda_Fricker", "Cyril_Cusack", "Fiona_Shaw", "Hugh_O%27Conor", "Adrian_Dunbar"], "total_actors": 7}
{"id": "Pillow_Talk_(film)", "name": "Pillow Talk", "release": "1959-10-06", "box_office": 76000000.0, "actors_id": ["Rock_Hudson", "Doris_Day", "Tony_Randall", "Thelma_Ritter"], "total_actors": 4}
{"id": "To_Each_His_Own_(film)", "name": "To Each His Own", "release": ["12", "1946", "1946", "03", "12"], "box_office": 36000000.0, "actors_id": ["Olivia_de_Havilland", "Mary_Anderson_(actress,_born_1918)", "John_Lund_(actor)"], "total_actors": 3}
{"id": "A_Farewell_to_Arms_(1957_film)", "name": "A Farewell to Arms", "release": "1957-12-14", "box_office": 200000000.0, "actors_id": ["Rock_Hudson", "Jennifer_Jones", "Vittorio_De_Sica", "Elaine_Stritch"], "total_actors": 4}
{"id": "Raging_Bull", "name": "Raging Bull", "release": "1980-11-14", "box_office": 234000000.0, "actors_id": ["Robert_De_Niro"], "total_actors": 1}
{"id": "East_of_Eden_(film)", "name": "East of Eden", "release": "1955-03-09", "box_office": 5.0, "actors_id": ["James_Dean", "Julie_Harris_(actress)", "Raymond_Massey", "Jo_Van_Fleet"], "total_actors": 4}
{"id": "American_Gangster_(film)", "name": "American Gangster", "release": "2007-10-19", "box_office": 2665000000.0, "actors_id": ["Denzel_Washington", "Russell_Crowe", "Chiwetel_Ejiofor", "Cuba_Gooding_Jr.", "Josh_Brolin", "Ted_Levine", "Armand_Assante", "John_Ortiz", "John_Hawkes_(actor)", "Rza"], "total_actors": 10}
{"id": "The_Jolson_Story", "name": "The Jolson Story", "release": "1946-10-10", "box_office": 8.0, "actors_id": ["Larry_Parks", "Evelyn_Keyes", "William_Demarest", "Bill_Goodwin"], "total_actors": 4}
{"id": "Indochine_(film)", "name": "Indochine", "release": "1992-04-15", "box_office": 296000000.0, "actors_id": ["Catherine_Deneuve", "Vincent_P%C3%A9rez", "Linh_Dan_Pham", "Jean_Yanne", "Dominique_Blanc"], "total_actors": 5}
{"id": "Who%27s_Afraid_of_Virginia_Woolf%3F_(film)", "name": "Who's Afraid of Virginia Woolf?", "release": "1966-06-21", "box_office": 400000000.0, "actors_id": ["Elizabeth_Taylor", "Richard_Burton", "George_Segal", "Sandy_Dennis"], "total_actors": 4}
{"id": "Cyrano_de_Bergerac_(1990_film)", "name": "Cyrano de Bergerac", "release": "1990-03-28", "box_office": 413000000.0, "actors_id": ["G%C3%A9rard_Depardieu", "Anne_Brochet", "Vincent_P%C3%A9rez", "Jacques_Weber"], "total_actors": 4}
{"id": "Rambling_Rose_(film)", "name": "Rambling Rose", "release": "1991-09-20", "box_office": 63000000.0, "actors_id": ["Laura_Dern", "Diane_Ladd", "Lukas_Haas", "Robert_Duvall", "John_Heard_(actor)"], "total_actors": 5}
{"id": "Nebraska_(film)", "name": "Nebraska", "release": "2013-05-23", "box_office": 277000000.0, "actors_id": ["Bruce_Dern", "Will_Forte", "June_Squibb", "Stacy_Keach", "Bob_Odenkirk"], "total_actors": 5}
{"id": "Pirates_of_the_Caribbean:_The_Curse_of_the_Black_Pearl", "name": "Pirates of the Caribbean:  The Curse of the Black Pearl", "release": "2003-06-28", "box_office": 6543000000.0, "actors_id": ["Johnny_Depp", "Geoffrey_Rush", "Orlando_Bloom", "Keira_Knightley", "Jonathan_Pryce"], "total_actors": 5}
{"id": "Morocco_(film)", "name": "Morocco", "release": "1930-11-14", "box_office": null, "actors_id": ["Gary_Cooper", "Marlene_Dietrich", "Adolphe_Menjou"], "total_actors": 3}
{"id": "The_Revenant_(2015_film)", "name": "The Revenant", "release": "2015-12-16", "box_office": 5330000000.0, "actors_id": ["Leonardo_DiCaprio", "Tom_Hardy", "Domhnall_Gleeson", "Will_Poulter"], "total_actors": 4}
{"id": "Cimarron_(1931_film)", "name": "Cimarron", "release": "1931-01-26", "box_office": null, "actors_id": ["Richard_Dix", "Irene_Dunne"], "total_actors": 2}
{"id": "Close_Encounters_of_the_Third_Kind", "name": "Close Encountersof the Third Kind", "release": "1977-11-16", "box_office": 3061000000.0, "actors_id": ["Richard_Dreyfuss", "Teri_Garr", "Melinda_Dillon", "Fran%C3%A7ois_Truffaut"], "total_actors": 4}
{"id": "Goodbye,_Mr._Chips_(1939_film)", "name": "Goodbye, Mr. Chips", "release": "1939-05-15", "box_office": null, "actors_id": ["Robert_Donat", "Greer_Garson", "Terry_Kilburn"], "total_actors": 3}
{"id": "Champion_(1949_film)", "name": "Champion", "release": "1949-04-09", "box_office": 25000000.0, "actors_id": ["Kirk_Douglas", "Marilyn_Maxwell", "Arthur_Kennedy"], "total_actors": 3}
{"id": "Beau_Geste_(1939_film)", "name": "Beau Geste", "release": "1939-08-02", "box_office": null, "actors_id": ["Gary_Cooper", "Ray_Milland", "Robert_Preston_(actor)", "Brian_Donlevy", "Susan_Hayward"], "total_actors": 5}
{"id": "Hud_(1963_film)", "name": "Hud", "release": "1963-05-29", "box_office": 100000000.0, "actors_id": ["Paul_Newman", "Melvyn_Douglas", "Patricia_Neal", "Brandon_deWilde"], "total_actors": 4}
{"id": "A_Ship_Comes_In", "name": "A Ship Comes In", "release": "1928-01-04", "box_office": null, "actors_id": ["Rudolph_Schildkraut", "Louise_Dresser", "index.php?title=Milton_Holmes&action=edit&redlink=1", "index.php?title=Linda_Landi&action=edit&redlink=1"], "total_actors": 4}
{"id": "Wall_Street_(1987_film)", "name": "Wall Street", "release": "1987-12-11", "box_office": 439000000.0, "actors_id": ["Michael_Douglas", "Charlie_Sheen", "Daryl_Hannah", "Martin_Sheen", "Hal_Holbrook", "Terence_Stamp"], "total_actors": 6}
{"id": "Min_and_Bill", "name": "Min and Bill", "release": ["29", "1930", "1930"], "box_office": 2.0, "actors_id": ["Marie_Dressler", "Wallace_Beery"], "total_actors": 2}
{"id": "One_Flew_Over_the_Cuckoo%27s_Nest_(film)", "name": "One Flew Over the Cuckoo's Nest", "release": "1975-11-19", "box_office": 1090000000.0, "actors_id": ["Jack_Nicholson", "Louise_Fletcher", "William_Redfield_(actor)"], "total_actors": 3}
{"id": "BlacKkKlansman", "name": "BlacKkKlansman", "release": "2018-05-14", "box_office": 906000000.0, "actors_id": ["John_David_Washington", "Adam_Driver", "Laura_Harrier", "Topher_Grace"], "total_actors": 4}
{"id": "The_Green_Mile_(film)", "name": "The Green Mile", "release": "1999-12-10", "box_office": 2907000000.0, "actors_id": ["Tom_Hanks", "David_Morse_(actor)", "Bonnie_Hunt", "Michael_Clarke_Duncan", "James_Cromwell", "Michael_Jeter", "Graham_Greene_(actor)", "Doug_Hutchison", "Sam_Rockwell", "Barry_Pepper", "Jeffrey_DeMunn", "Patricia_Clarkson", "Harry_Dean_Stanton"], "total_actors": 13}
{"id": "A_Tree_Grows_in_Brooklyn_(1945_film)", "name": "A Tree Grows in Brooklyn", "release": "1945-02-28", "box_office": 3.0, "actors_id": ["Dorothy_McGuire", "Joan_Blondell", "James_Dunn_(actor)", "Lloyd_Nolan", "Peggy_Ann_Garner", "Ted_Donaldson", "James_Gleason", "Ruth_Nelson_(actress)", "John_Alexander_(actor)", "B.S._Pully"], "total_actors": 10}
{"id": "Ship_of_Fools_(film)", "name": "Ship of Fools", "release": "1965-07-29", "box_office": 3500000.0, "actors_id": ["Vivien_Leigh", "Jos%C3%A9_Ferrer", "Lee_Marvin", "Simone_Signoret"], "total_actors": 4}
{"id": "Death_of_a_Salesman_(1951_film)", "name": "Death of a Salesman", "release": "1951-12-20", "box_office": 12000000.0, "actors_id": ["Fredric_March", "Mildred_Dunnock", "Kevin_McCarthy_(actor)", "Cameron_Mitchell_(actor)"], "total_actors": 4}
{"id": "The_Best_Little_Whorehouse_in_Texas_(film)", "name": "The Best Little Whorehouse in Texas", "release": "1982-07-23", "box_office": 697000000.0, "actors_id": ["Burt_Reynolds", "Dolly_Parton", "Dom_DeLuise", "Charles_Durning", "Jim_Nabors"], "total_actors": 5}
{"id": "The_Letter_(1929_film)", "name": "The Letter", "release": ["13", "1929", "1929", "04", "13"], "box_office": null, "actors_id": ["Jeanne_Eagels", "O._P._Heggie"], "total_actors": 2}
{"id": "The_Collector_(1965_film)", "name": "The Collector", "release": ["17", "1965", "1965", "06", "17"], "box_office": 3500000.0, "actors_id": ["Terence_Stamp", "Samantha_Eggar", "Mona_Washbourne"], "total_actors": 3}
{"id": "Tender_Mercies", "name": "Tender Mercies", "release": "1983-03-04", "box_office": 84000000.0, "actors_id": ["Robert_Duvall", "Tess_Harper", "Betty_Buckley", "Wilford_Brimley", "Ellen_Barkin"], "total_actors": 5}
{"id": "Unforgiven", "name": "Unforgiven", "release": "1992-08-03", "box_office": 1592000000.0, "actors_id": ["Gene_Hackman", "Morgan_Freeman", "Richard_Harris"], "total_actors": 3}
{"id": "A_Room_with_a_View_(1985_film)", "name": "A Room with a View", "release": "1985-12-13", "box_office": 210000000.0, "actors_id": ["Maggie_Smith", "Denholm_Elliott", "Judi_Dench", "Simon_Callow", "Helena_Bonham_Carter", "Julian_Sands", "Daniel_Day-Lewis", "Fabia_Drake", "Patrick_Godfrey", "Rupert_Graves", "Rosemary_Leach"], "total_actors": 11}
{"id": "Caged", "name": "Caged", "release": "1950-05-19", "box_office": 15000000.0, "actors_id": ["Eleanor_Parker", "Agnes_Moorehead", "Betty_Garde", "Hope_Emerson", "Ellen_Corby"], "total_actors": 5}
{"id": "A_Star_Is_Born_(2018_film)", "name": "A Star Is Born", "release": "2018-08-31", "box_office": 4254000000.0, "actors_id": ["Lady_Gaga", "Andrew_Dice_Clay", "Dave_Chappelle", "Sam_Elliott"], "total_actors": 4}
{"id": "Pigskin_Parade", "name": "Pigskin Parade", "release": ["23", "1936", "1936", "10", "23"], "box_office": null, "actors_id": ["Stuart_Erwin", "Patsy_Kelly", "Jack_Haley", "Betty_Grable", "Judy_Garland"], "total_actors": 5}
{"id": "The_Social_Network", "name": "The Social Network", "release": "2010-09-24", "box_office": 2249000000.0, "actors_id": ["Jesse_Eisenberg", "Andrew_Garfield", "Justin_Timberlake", "Armie_Hammer", "Max_Minghella"], "total_actors": 5}
{"id": "The_Whisperers", "name": "The Whisperers", "release": ["24", "1967"], "box_office": null, "actors_id": ["Edith_Evans"], "total_actors": 1}
{"id": "12_Years_a_Slave_(film)", "name": "12 Years a Slave", "release": "2013-08-30", "box_office": 1877000000.0, "actors_id": ["Chiwetel_Ejiofor", "Michael_Fassbender", "Benedict_Cumberbatch", "Paul_Dano", "Paul_Giamatti", "Lupita_Nyong%27o", "Sarah_Paulson", "Brad_Pitt", "Alfre_Woodard"], "total_actors": 9}
{"id": "Murder,_Inc._(1960_film)", "name": "Murder, Inc.", "release": ["28", "1960", "1960", "06", "28"], "box_office": null, "actors_id": ["Stuart_Whitman", "May_Britt", "Henry_Morgan_(comedian)", "Peter_Falk"], "total_actors": 4}
{"id": "The_Straight_Story", "name": "The Straight Story", "release": "1999-10-21", "box_office": 62000000.0, "actors_id": ["Richard_Farnsworth", "Sissy_Spacek", "Harry_Dean_Stanton"], "total_actors": 3}
{"id": "Norma_Rae", "name": "Norma Rae", "release": "1979-03-02", "box_office": 220000000.0, "actors_id": ["Sally_Field", "Beau_Bridges", "Ron_Leibman"], "total_actors": 3}
{"id": "Cyrano_de_Bergerac_(1950_film)", "name": "Cyrano de Bergerac", "release": "1950-11-16", "box_office": 19000000.0, "actors_id": ["Jos%C3%A9_Ferrer", "Mala_Powers", "William_Prince_(actor)"], "total_actors": 3}
{"id": "Up_in_the_Air_(2009_film)", "name": "Up in the Air", "release": "2009-09-05", "box_office": 1668000000.0, "actors_id": ["George_Clooney", "Vera_Farmiga", "Anna_Kendrick", "Danny_McBride"], "total_actors": 4}
{"id": "Othello_(1965_British_film)", "name": "Othello", "release": "1965-12-15", "box_office": null, "actors_id": ["Laurence_Olivier", "Maggie_Smith", "Joyce_Redman", "Frank_Finlay"], "total_actors": 4}
{"id": "Steve_Jobs_(film)", "name": "Steve Jobs", "release": "2015-09-05", "box_office": 344000000.0, "actors_id": ["Michael_Fassbender", "Kate_Winslet", "Seth_Rogen", "Jeff_Daniels"], "total_actors": 4}
{"id": "Equus_(film)", "name": "Equus", "release": "1977-10-14", "box_office": null, "actors_id": ["Richard_Burton", "Peter_Firth", "Jenny_Agutter", "Joan_Plowright", "Colin_Blakely"], "total_actors": 5}
{"id": "Wuthering_Heights_(1939_film)", "name": "Wuthering Heights", "release": "1939-03-24", "box_office": null, "actors_id": ["Merle_Oberon", "Laurence_Olivier", "David_Niven", "Geraldine_Fitzgerald"], "total_actors": 4}
{"id": "On_Golden_Pond_(1981_film)", "name": "On Golden Pond", "release": "1981-12-04", "box_office": 1193000000.0, "actors_id": ["Katharine_Hepburn", "Henry_Fonda", "Jane_Fonda", "Doug_McKeon", "Dabney_Coleman", "William_Lanteau"], "total_actors": 6}
{"id": "Klute", "name": "Klute", "release": "1971-06-25", "box_office": null, "actors_id": ["Jane_Fonda", "Donald_Sutherland", "Charles_Cioffi", "Roy_Scheider"], "total_actors": 4}
{"id": "Ulee%27s_Gold", "name": "Ulee's Gold", "release": "1997-06-13", "box_office": 9054736.0, "actors_id": ["Peter_Fonda", "Patricia_Richardson", "Jessica_Biel", "J._Kenneth_Campbell", "Christine_Dunford", "Thomas_Mills_Wood", "Vanessa_Zima"], "total_actors": 7}
{"id": "Suspicion_(1941_film)", "name": "Suspicion", "release": "1941-11-14", "box_office": 4.5, "actors_id": ["Cary_Grant", "Joan_Fontaine", "Cedric_Hardwicke", "Nigel_Bruce", "Dame_May_Whitty"], "total_actors": 5}
{"id": "The_Guardsman", "name": "The Guardsman", "release": ["7", "1931"], "box_office": null, "actors_id": ["Alfred_Lunt", "Lynn_Fontanne"], "total_actors": 2}
{"id": "Witness_(1985_film)", "name": "Witness", "release": "1985-02-08", "box_office": 687000000.0, "actors_id": ["Harrison_Ford"], "total_actors": 1}
{"id": "The_Rose_(film)", "name": "The Rose", "release": "1979-11-09", "box_office": 292000000.0, "actors_id": ["Bette_Midler", "Alan_Bates", "Frederic_Forrest", "Harry_Dean_Stanton"], "total_actors": 4}
{"id": "The_Accused_(1988_film)", "name": "The Accused", "release": "1988-10-14", "box_office": 377000000.0, "actors_id": ["Jodie_Foster", "Kelly_McGillis", "Bernie_Coulson", "Leo_Rossi", "Ann_Hearn", "Carmen_Argenziano", "Steve_Antin"], "total_actors": 7}
{"id": "Jackie_Brown", "name": "Jackie Brown", "release": "1997-12-08", "box_office": 747000000.0, "actors_id": ["Pam_Grier", "Samuel_L._Jackson", "Robert_Forster", "Bridget_Fonda", "Michael_Keaton", "Robert_De_Niro"], "total_actors": 6}
{"id": "Ray_(film)", "name": "Ray", "release": "2004-10-29", "box_office": 1247000000.0, "actors_id": ["Jamie_Foxx", "Kerry_Washington", "Clifton_Powell", "Harry_Lennix", "Terrence_Howard", "Larenz_Tate", "Richard_Schiff", "Regina_King"], "total_actors": 8}
{"id": "A_Hatful_of_Rain", "name": "A Hatful of Rain", "release": "1957-07-17", "box_office": 15000000.0, "actors_id": ["Don_Murray_(actor)", "Eva_Marie_Saint", "Anthony_Franciosa"], "total_actors": 3}
{"id": "127_Hours", "name": "127 Hours", "release": "2010-09-04", "box_office": 607000000.0, "actors_id": ["James_Franco", "Kate_Mara", "Amber_Tamblyn"], "total_actors": 3}
{"id": "Fiddler_on_the_Roof_(film)", "name": "Fiddler on the Roof", "release": "1971-11-03", "box_office": 833000000.0, "actors_id": ["Chaim_Topol", "Norma_Crane", "Leonard_Frey", "Molly_Picon", "Paul_Mann"], "total_actors": 5}
