{"id": "Avatar_2", "name": "Avatar 2", "release": "2020-12-18", "box_office": null, "actors_id": ["Sam_Worthington", "Zoe_Saldana", "Stephen_Lang", "Sigourney_Weaver"], "total_actors": 4}
{"id": "Avatar_3", "name": "Avatar 3", "release": "2021-12-17", "box_office": null, "actors_id": ["Sam_Worthington", "Zoe_Saldana", "Stephen_Lang", "Sigourney_Weaver"], "total_actors": 4}
{"id": "Titanic_(1997_film)", "name": "Titanic", "release": "1997-11-01", "box_office": "$2.187 billion", "actors_id": ["Leonardo_DiCaprio", "Kate_Winslet", "Billy_Zane", "Kathy_Bates", "Frances_Fisher", "Bernard_Hill", "Jonathan_Hyde", "Danny_Nucci", "David_Warner_(actor)", "Bill_Paxton"], "total_actors": 10}
{"id": "Girlfight", "name": "Girlfight", "release": "2000-01-22", "box_office": "$1.7 million", "actors_id": ["Michelle_Rodriguez", "Paul_Calder%C3%B3n"], "total_actors": 2}
{"id": "Aliens_(film)", "name": "Aliens", "release": "1986-07-18", "box_office": null, "actors_id": ["Sigourney_Weaver"], "total_actors": 1}
{"id": "King_Kong_(2005_film)", "name": "King Kong", "release": "2005-12-05", "box_office": "$550.5 million", "actors_id": ["Naomi_Watts", "Jack_Black", "Adrien_Brody", "Thomas_Kretschmann", "Colin_Hanks", "Jamie_Bell", "Evan_Parke", "Lobo_Chan", "Kyle_Chandler", "Andy_Serkis"], "total_actors": 10}
{"id": "Alita:_Battle_Angel", "name": "Alita: Battle Angel", "release": "2019-01-31", "box_office": "$264.8 million", "actors_id": ["Rosa_Salazar", "Christoph_Waltz", "Jennifer_Connelly", "Mahershala_Ali", "Ed_Skrein", "Jackie_Earle_Haley"], "total_actors": 6}
{"id": "At_Play_in_the_Fields_of_the_Lord", "name": "At Play in the Fields of the Lord", "release": "1991-12-06", "box_office": null, "actors_id": ["Tom_Berenger", "John_Lithgow", "Daryl_Hannah", "Aidan_Quinn", "Tom_Waits", "Kathy_Bates"], "total_actors": 6}
{"id": "The_Emerald_Forest", "name": "The Emerald Forest", "release": ["5", "1985"], "box_office": null, "actors_id": ["Powers_Boothe", "Meg_Foster", "Charley_Boorman"], "total_actors": 3}
{"id": "Dances_with_Wolves", "name": "Dances with Wolves", "release": "1990-10-19", "box_office": "$424.2 million", "actors_id": ["Mary_McDonnell", "Graham_Greene_(actor)", "Rodney_A._Grant"], "total_actors": 3}
{"id": "Tarzan_(1999_film)", "name": "Tarzan", "release": "1999-06-12", "box_office": "$448.2 million", "actors_id": ["Tony_Goldwyn", "Minnie_Driver", "Glenn_Close", "Alex_D._Linz", "Rosie_O%27Donnell", "Brian_Blessed", "Nigel_Hawthorne", "Lance_Henriksen", "Wayne_Knight"], "total_actors": 9}
{"id": "Princess_Mononoke", "name": "Princess Mononoke", "release": "1997-07-12", "box_office": "$159.4 million", "actors_id": ["Y%C5%8Dji_Matsuda", "Yuriko_Ishida", "Y%C5%ABko_Tanaka", "Kaoru_Kobayashi_(actor)", "Masahiko_Nishimura", "Tsunehiko_Kamijo", "Akihiro_Miwa", "Mitsuko_Mori", "Hisaya_Morishige"], "total_actors": 9}
{"id": "I_See_You_(Theme_from_Avatar)", "name": "\"I See You (Theme from Avatar)\"", "release": null, "box_office": null, "actors_id": [], "total_actors": 0}
{"id": "The_Day_After_Tomorrow", "name": "The Day After Tomorrow", "release": "2004-05-17", "box_office": "$544.3 million", "actors_id": ["Dennis_Quaid", "Jake_Gyllenhaal", "Ian_Holm", "Emmy_Rossum", "Sela_Ward"], "total_actors": 5}
{"id": "I_Am_Legend_(film)", "name": "I Am Legend", "release": "2007-12-14", "box_office": "$585.3 million", "actors_id": ["Will_Smith", "Alice_Braga", "Dash_Mihok"], "total_actors": 3}
{"id": "Harry_Potter_and_the_Half-Blood_Prince_(film)", "name": "Harry Potter and the Half-Blood Prince", "release": "2009-07-07", "box_office": "$934.4 million", "actors_id": ["Daniel_Radcliffe", "Rupert_Grint", "Emma_Watson", "Jim_Broadbent", "Helena_Bonham_Carter", "Robbie_Coltrane", "Warwick_Davis", "Michael_Gambon", "Alan_Rickman", "Maggie_Smith", "Timothy_Spall", "David_Thewlis", "Julie_Walters"], "total_actors": 13}
{"id": "The_Incredibles_(film)", "name": "The Incredibles", "release": "2004-10-27", "box_office": "$633\u00a0million", "actors_id": ["Craig_T._Nelson", "Holly_Hunter", "Sarah_Vowell", "Spencer_Fox", "Jason_Lee_(actor)", "Samuel_L._Jackson", "Elizabeth_Pe%C3%B1a"], "total_actors": 7}
{"id": "Up_(2009_film)", "name": "Up", "release": "2009-05-29", "box_office": "$735.1 million", "actors_id": ["Ed_Asner", "Jordan_Nagai", "Christopher_Plummer"], "total_actors": 3}
{"id": "Pirates_of_the_Caribbean:_Dead_Man%27s_Chest", "name": "Pirates of the Caribbean:  Dead Man's Chest", "release": "2006-06-24", "box_office": "$1.096 billion", "actors_id": ["Johnny_Depp", "Orlando_Bloom", "Keira_Knightley", "Stellan_Skarsg%C3%A5rd", "Bill_Nighy", "Jack_Davenport", "Kevin_R._McNally", "Jonathan_Pryce"], "total_actors": 8}
{"id": "Star_Wars_Episode_I:_The_Phantom_Menace", "name": "Star Wars: Episode I \u2013The Phantom Menace", "release": "1999-05-16", "box_office": "$1.027 billion", "actors_id": ["Liam_Neeson", "Ewan_McGregor", "Natalie_Portman", "Jake_Lloyd", "Ian_McDiarmid", "Anthony_Daniels", "Kenny_Baker_(English_actor)", "Pernilla_August", "Frank_Oz"], "total_actors": 9}
{"id": "Gone_with_the_Wind_(film)", "name": "Gone with the Wind", "release": "1939-12-15", "box_office": "$390 million", "actors_id": ["Clark_Gable", "Vivien_Leigh", "Leslie_Howard", "Olivia_de_Havilland"], "total_actors": 4}
{"id": "Alvin_and_the_Chipmunks:_The_Squeakquel", "name": "Alvin and the Chipmunks:The Squeakquel", "release": "2009-12-23", "box_office": "$443.1 million", "actors_id": ["Justin_Long", "Matthew_Gray_Gubler", "Jesse_McCartney", "Christina_Applegate", "Anna_Faris", "Amy_Poehler", "David_Cross", "Zachary_Levi", "Jason_Lee_(actor)"], "total_actors": 9}
{"id": "Star_Wars_(film)", "name": "Star Wars", "release": "1977-05-25", "box_office": "$775.4 million", "actors_id": ["Mark_Hamill", "Harrison_Ford", "Carrie_Fisher", "Peter_Cushing", "Alec_Guinness"], "total_actors": 5}
{"id": "The_Dark_Knight_(film)", "name": "The Dark Knight", "release": "2008-07-14", "box_office": "$1.005 billion", "actors_id": ["Christian_Bale", "Michael_Caine", "Heath_Ledger", "Gary_Oldman", "Aaron_Eckhart", "Maggie_Gyllenhaal", "Morgan_Freeman"], "total_actors": 7}
{"id": "The_Lord_of_the_Rings:_The_Fellowship_of_the_Ring", "name": "The Lord of the Rings: The Fellowship of the Ring", "release": "2001-12-10", "box_office": "$871.5\u00a0million", "actors_id": ["Elijah_Wood", "Ian_McKellen", "Liv_Tyler", "Viggo_Mortensen", "Sean_Astin", "Cate_Blanchett", "John_Rhys-Davies", "Billy_Boyd_(actor)", "Dominic_Monaghan", "Orlando_Bloom", "Christopher_Lee", "Hugo_Weaving", "Sean_Bean", "Ian_Holm", "Andy_Serkis", "Sala_Baker"], "total_actors": 16}
{"id": "FernGully:_The_Last_Rainforest", "name": "FernGully: The Last Rainforest", "release": "1992-04-10", "box_office": "$32.7 million", "actors_id": ["Jonathan_Ward_(actor)", "Samantha_Mathis", "Tim_Curry", "Christian_Slater", "Robin_Williams", "Grace_Zabriskie", "Geoffrey_Blake_(actor)", "Robert_Pastorelli"], "total_actors": 8}
{"id": "The_Last_Samurai", "name": "The Last Samurai", "release": "2003-11-20", "box_office": "$456.8 million", "actors_id": ["Timothy_Spall", "Ken_Watanabe", "Billy_Connolly", "Tony_Goldwyn", "Hiroyuki_Sanada", "Koyuki"], "total_actors": 6}
{"id": "Pocahontas_(1995_film)", "name": "Pocahontas", "release": "1995-06-23", "box_office": "$346.1 million", "actors_id": ["Irene_Bedard", "Mel_Gibson", "David_Ogden_Stiers", "John_Kassir", "Russell_Means", "Christian_Bale", "Linda_Hunt", "Danny_Mann", "Billy_Connolly", "Frank_Welker"], "total_actors": 10}
{"id": "Valerian_and_the_City_of_a_Thousand_Planets", "name": "Valerian and the Cityof a Thousand Planets", "release": "2017-07-17", "box_office": "$225.9 million", "actors_id": ["Dane_DeHaan", "Cara_Delevingne", "Clive_Owen", "Rihanna", "Ethan_Hawke", "Herbie_Hancock", "Kris_Wu", "Rutger_Hauer"], "total_actors": 8}
{"id": "Toruk_-_The_First_Flight", "name": "Toruk - The First Flight", "release": null, "box_office": null, "actors_id": [], "total_actors": 0}
{"id": "Frozen_(2013_film)", "name": "Frozen", "release": "2013-11-19", "box_office": "$1.276 billion", "actors_id": ["Kristen_Bell", "Idina_Menzel", "Jonathan_Groff", "Josh_Gad", "Santino_Fontana"], "total_actors": 5}
